# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/014 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: In the United States, dates are typically formatted in month-day-year order (MM/DD/YYYY), otherwise known as middle-endian order, which is ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/014', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "9/8/1636"\nExpected Output: "1636-09-08"
    check_stdout(run_program(candidate_path, stdin='9/8/1636\n'), '1636-09-08', 'tail')


def test_t2(candidate_path):
    # release: Input: "September 8, 1636"\nExpected Output: "1636-09-08"
    check_stdout(run_program(candidate_path, stdin='September 8, 1636\n'), '1636-09-08', 'tail')


def test_t3(candidate_path):
    # release: Input: "12/25/2023"\nExpected Output: "2023-12-25"
    check_stdout(run_program(candidate_path, stdin='12/25/2023\n'), '2023-12-25', 'tail')


def test_t4(candidate_path):
    # release: Input: "December 25, 2023"\nExpected Output: "2023-12-25"
    check_stdout(run_program(candidate_path, stdin='December 25, 2023\n'), '2023-12-25', 'tail')


def test_t5(candidate_path):
    # release: Input: "2/29/2000"\nExpected Output: "2000-02-29"
    check_stdout(run_program(candidate_path, stdin='2/29/2000\n'), '2000-02-29', 'tail')
