# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/090 | mode: original | kind: custom | entry: RightTriangle | comparison: eq
# Well-posed: yes
# Note: The release has no tests (only the prompt that was sent to an LLM to write them). Validated mode
# Note: uses five authored tests written from the prompt.
# Prompt: #Create a class called RightTriangle. RightTriangle should\n#have two attributes (instance variables): opposite and\n#adjacent. Make sure the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/090', 'kind': 'custom', 'entry': 'RightTriangle'}
ENV = None


# This task has no usable tests in this mode (see the manifest).
