# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/047 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: current_day = 31\ncurrent_month = 5\ncurrent_year = 2018\nbirth_day = 19\nbirth_month = 12\nbirth_year = 1990\n\n#You may modify the lines of code ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/047', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\ncurrent_day = 31\ncurrent_month = 5\ncurrent_year = 2018\nbirth_day = 19\nbirth_month = ...
    check_stdout(run_program(candidate_path, assignments={'current_day': '31', 'current_month': '5', 'current_year': '2018', 'birth_day': '19', 'birth_month': '12', 'birth_year': '1990'}), '27', 'tail')


def test_t2(candidate_path):
    # release: Input:\ncurrent_day = 31\ncurrent_month = 12\ncurrent_year = 2018\nbirth_day = 19\nbirth_month = ...
    check_stdout(run_program(candidate_path, assignments={'current_day': '31', 'current_month': '12', 'current_year': '2018', 'birth_day': '19', 'birth_month': '12', 'birth_year': '1990'}), '28', 'tail')


def test_t3(candidate_path):
    # release: Input:\ncurrent_day = 18\ncurrent_month = 12\ncurrent_year = 2018\nbirth_day = 19\nbirth_month = ...
    check_stdout(run_program(candidate_path, assignments={'current_day': '18', 'current_month': '12', 'current_year': '2018', 'birth_day': '19', 'birth_month': '12', 'birth_year': '1990'}), '27', 'tail')


def test_t4(candidate_path):
    # release: Input:\ncurrent_day = 1\ncurrent_month = 1\ncurrent_year = 2000\nbirth_day = 1\nbirth_month = ...
    check_stdout(run_program(candidate_path, assignments={'current_day': '1', 'current_month': '1', 'current_year': '2000', 'birth_day': '1', 'birth_month': '1', 'birth_year': '1990'}), '10', 'tail')


def test_t5(candidate_path):
    # release: Input:\ncurrent_day = 31\ncurrent_month = 12\ncurrent_year = 1999\nbirth_day = 1\nbirth_month = ...
    check_stdout(run_program(candidate_path, assignments={'current_day': '31', 'current_month': '12', 'current_year': '1999', 'birth_day': '1', 'birth_month': '1', 'birth_year': '1990'}), '9', 'tail')
