# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/033 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: yes
# Prompt: Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/033', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: Hours = 45, Rate = 10.50\nExpected Output: Gross Pay = 498.75
    check_stdout(run_program(candidate_path, stdin='45\n10.50\n'), '498.75', 'num')


def test_t2(candidate_path):
    # release: Input: Hours = 40, Rate = 10\nExpected Output: Gross Pay = 400.00
    check_stdout(run_program(candidate_path, stdin='40\n10\n'), '400.00', 'num')


def test_t3(candidate_path):
    # release: Input: Hours = 50, Rate = 20\nExpected Output: Gross Pay = 1100.00
    check_stdout(run_program(candidate_path, stdin='50\n20\n'), '1100.00', 'num')


def test_t4(candidate_path):
    # release: Input: Hours = 30, Rate = 100\nExpected Output: Gross Pay = 3000.00
    check_stdout(run_program(candidate_path, stdin='30\n100\n'), '3000.00', 'num')


def test_t5(candidate_path):
    # release: Input: Hours = 60, Rate = 10\nExpected Output: Gross Pay = 700.00
    check_stdout(run_program(candidate_path, stdin='60\n10\n'), '700.00', 'num')
