# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/054 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: int1 = 7\nint2 = 5\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change these lines ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/054', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nint1 = 7\nint2 = 5\nOutput:\n"int1 is greater"
    check_stdout(run_program(candidate_path, assignments={'int1': '7', 'int2': '5'}), 'int1 is greater', 'tail')


def test_t2(candidate_path):
    # release: Input:\nint1 = 5\nint2 = 7\nOutput:\n"int2 is greater"
    check_stdout(run_program(candidate_path, assignments={'int1': '5', 'int2': '7'}), 'int2 is greater', 'tail')


def test_t3(candidate_path):
    # release: Input:\nint1 = 5\nint2 = 5\nOutput:\n"int1 and int2 are equal"
    check_stdout(run_program(candidate_path, assignments={'int1': '5', 'int2': '5'}), 'int1 and int2 are equal', 'tail')


def test_t4(candidate_path):
    # release: Input:\nint1 = 0\nint2 = 0\nOutput:\n"int1 and int2 are equal"
    check_stdout(run_program(candidate_path, assignments={'int1': '0', 'int2': '0'}), 'int1 and int2 are equal', 'tail')


def test_t5(candidate_path):
    # release: Input:\nint1 = -1\nint2 = 1\nOutput:\n"int2 is greater"
    check_stdout(run_program(candidate_path, assignments={'int1': '-1', 'int2': '1'}), 'int2 is greater', 'tail')
