# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/039 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: hot = True\ncold = False\nrainy = True\nwindy = False\nsnowy = False\n\n#You may modify the lines of code above, but don't move them!\n#When you ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/039', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nhot = True\ncold = False\nrainy = True\nwindy = False\nsnowy = False\nOutput:\nHat: ...
    check_stdout(run_program(candidate_path, assignments={'hot': 'True', 'cold': 'False', 'rainy': 'True', 'windy': 'False', 'snowy': 'False'}), 'Hat: True\nGloves: False\nUmbrella: True\nScarf: False', 'tail')


def test_t2(candidate_path):
    # release: Input:\nhot = False\ncold = True\nrainy = True\nwindy = True\nsnowy = False\nOutput:\nHat: ...
    check_stdout(run_program(candidate_path, assignments={'hot': 'False', 'cold': 'True', 'rainy': 'True', 'windy': 'True', 'snowy': 'False'}), 'Hat: True\nGloves: True\nUmbrella: True\nScarf: False', 'tail')


def test_t3(candidate_path):
    # release: Input:\nhot = False\ncold = True\nrainy = False\nwindy = True\nsnowy = True\nOutput:\nHat: ...
    check_stdout(run_program(candidate_path, assignments={'hot': 'False', 'cold': 'True', 'rainy': 'False', 'windy': 'True', 'snowy': 'True'}), 'Hat: True\nGloves: True\nUmbrella: True\nScarf: True', 'tail')


def test_t4(candidate_path):
    # release: Input:\nhot = True\ncold = False\nrainy = False\nwindy = False\nsnowy = False\nOutput:\nHat: ...
    check_stdout(run_program(candidate_path, assignments={'hot': 'True', 'cold': 'False', 'rainy': 'False', 'windy': 'False', 'snowy': 'False'}), 'Hat: True\nGloves: False\nUmbrella: False\nScarf: False', 'tail')


def test_t5(candidate_path):
    # release: Input:\nhot = False\ncold = True\nrainy = False\nwindy = False\nsnowy = True\nOutput:\nHat: ...
    check_stdout(run_program(candidate_path, assignments={'hot': 'False', 'cold': 'True', 'rainy': 'False', 'windy': 'False', 'snowy': 'True'}), 'Hat: True\nGloves: True\nUmbrella: True\nScarf: True', 'tail')
