# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/052 | mode: original | kind: function | entry: remainder | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called remainder. remainder should take\n#two parameters: a dividend and a divisor. It should return\n#the remainder when you ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/052', 'kind': 'function', 'entry': 'remainder'}
ENV = None


def test_t1(m):
    # release: Input:\n(9, 3)\nOutput:\n0
    check(call(m, TASK, (9, 3), {}), 0, 'eq')


def test_t2(m):
    # release: Input:\n(8, 3)\nOutput:\n2
    check(call(m, TASK, (8, 3), {}), 2, 'eq')


def test_t3(m):
    # release: Input:\n(7, 3)\nOutput:\n1
    check(call(m, TASK, (7, 3), {}), 1, 'eq')


def test_t4(m):
    # release: Input:\n(6, 3)\nOutput:\n0
    check(call(m, TASK, (6, 3), {}), 0, 'eq')


def test_t5(m):
    # release: Input:\n(10, 2)\nOutput:\n0
    check(call(m, TASK, (10, 2), {}), 0, 'eq')
