# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/066 | mode: original | kind: function | entry: is_prime | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called is_prime. is_prime should take\n#as input one integer. It should return True if the integer\n#is prime, False if the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/066', 'kind': 'function', 'entry': 'is_prime'}
ENV = None


def test_t1(m):
    # release: Input: 7\nOutput: True
    check(call(m, TASK, (7,), {}), True, 'eq')


def test_t2(m):
    # release: Input: 12\nOutput: False
    check(call(m, TASK, (12,), {}), False, 'eq')


def test_t3(m):
    # release: Input: 13\nOutput: True
    check(call(m, TASK, (13,), {}), True, 'eq')


def test_t4(m):
    # release: Input: 100\nOutput: False
    check(call(m, TASK, (100,), {}), False, 'eq')


def test_t5(m):
    # release: Input: 997\nOutput: True
    check(call(m, TASK, (997,), {}), True, 'eq')
