# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/068 | mode: original | kind: function | entry: count_characters | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called count_characters. count_characters\n#should take as input a single string, and return a\n#dictionary. In the dictionary, ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/068', 'kind': 'function', 'entry': 'count_characters'}
ENV = None


def test_t1(m):
    # release: Input: "hello"\nOutput: {'h': 1, 'e': 1, 'l': 2, 'o': 1}
    check(call(m, TASK, ('hello',), {}), {'h': 1, 'e': 1, 'l': 2, 'o': 1}, 'eq')


def test_t2(m):
    # release: Input: "Aardvark"\nOutput: {'A': 1, 'a': 2, 'r': 2, 'd': 1, 'v': 1, 'k': 1}
    check(call(m, TASK, ('Aardvark',), {}), {'A': 1, 'a': 2, 'r': 2, 'd': 1, 'v': 1, 'k': 1}, 'eq')


def test_t3(m):
    # release: Input: "Spaces are also characters"\nOutput: {'S': 1, 'p': 1, 'a': 4, 'c': 2, 'e': 3, 's': 2, ' ': ...
    check(call(m, TASK, ('Spaces are also characters',), {}), {'S': 1, 'p': 1, 'a': 4, 'c': 2, 'e': 3, 's': 2, ' ': 3, 'r': 2, 'l': 1, 'o': 1, 'h': 1}, 'eq')


def test_t4(m):
    # release: Input: "!@#$%^&()"\nOutput: {'!': 1, '@': 1, '#': 1, '$': 1, '%': 1, '^': 1, '&': 1, '': 1, '(': 1, ...
    check(call(m, TASK, ('!@#$%^&()',), {}), {'!': 1, '@': 1, '#': 1, '$': 1, '%': 1, '^': 1, '&': 1, '': 1, '(': 1, ')': 1}, 'eq')


def test_t5(m):
    # release: Input: "1234567890"\nOutput: {'1': 1, '2': 1, '3': 1, '4': 1, '5': 1, '6': 1, '7': 1, '8': 1, '9': ...
    check(call(m, TASK, ('1234567890',), {}), {'1': 1, '2': 1, '3': 1, '4': 1, '5': 1, '6': 1, '7': 1, '8': 1, '9': 1, '0': 1}, 'eq')
