# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/082 | mode: original | kind: function | entry: no_you_pick | comparison: eq
# Well-posed: yes
# Prompt: #-----------------------------------------------------------\n#Write a function called no_you_pick. no_you_pick should\n#have two parameters. The ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/082', 'kind': 'function', 'entry': 'no_you_pick'}
ENV = None


def test_t1(m):
    # release: Input:\ngrading_scale = {\n"blossom": ["vegetarian", "vegan", "kosher", "gluten-free", "dairy- ...
    check(call(m, TASK, ({'blossom': ['vegetarian', 'vegan', 'kosher', 'gluten-free', 'dairy-free'], "jacob's pickles": ['vegetarian', 'gluten-free'], 'sweetgreen': ['vegetarian', 'vegan', 'gluten-free', 'kosher']}, ['dairy-free']), {}), ['blossom'], 'eq')


def test_t2(m):
    # release: Input:\ngrading_scale = {\n"pizza hut": ["vegetarian", "kosher", "dairy-free"],\n"dominos": ...
    check(call(m, TASK, ({'pizza hut': ['vegetarian', 'kosher', 'dairy-free'], 'dominos': ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'], 'papa johns': ['vegetarian', 'dairy-free'], 'popeyes': ['gluten-free', 'dairy-free']}, ['vegetarian', 'dairy-free']), {}), ['dominos', 'papa johns', 'pizza hut'], 'eq')


def test_t3(m):
    # release: Input:\ngrading_scale = {\n"mcdonalds": ["vegetarian"],\n"wendys": ["vegetarian", "gluten- ...
    check(call(m, TASK, ({'mcdonalds': ['vegetarian'], 'wendys': ['vegetarian', 'gluten-free'], 'burger king': ['gluten-free', 'dairy-free'], 'subway': ['vegetarian', 'vegan', 'gluten-free', 'dairy-free']}, ['vegan', 'dairy-free']), {}), ['subway'], 'eq')


def test_t4(m):
    # release: Input:\ngrading_scale = {\n"chipotle": ["vegetarian", "vegan", "gluten-free", "dairy-free"],\n"taco ...
    check(call(m, TASK, ({'chipotle': ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'], 'taco bell': ['vegetarian', 'gluten-free'], 'qdoba': ['gluten-free', 'dairy-free']}, ['vegetarian', 'vegan', 'dairy-free']), {}), ['chipotle'], 'eq')


def test_t5(m):
    # release: Input:\ngrading_scale = {\n"panera": ["vegetarian", "vegan", "gluten-free", "dairy- ...
    check(call(m, TASK, ({'panera': ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'], 'starbucks': ['vegetarian', 'gluten-free'], 'dunkin': ['gluten-free', 'dairy-free']}, ['kosher']), {}), 'Sorry, no restaurants meet your restrictions', 'eq')
