# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/057 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: n = 5\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change these lines to\n#assign different ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/057', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nn = 5\nOutput:\n120
    check_stdout(run_program(candidate_path, assignments={'n': '5'}), '120', 'tail')


def test_t2(candidate_path):
    # release: Input:\nn = 1\nOutput:\n1
    check_stdout(run_program(candidate_path, assignments={'n': '1'}), '1', 'tail')


def test_t3(candidate_path):
    # release: Input:\nn = 0\nOutput:\n1
    check_stdout(run_program(candidate_path, assignments={'n': '0'}), '1', 'tail')


def test_t4(candidate_path):
    # release: Input:\nn = 7\nOutput:\n5040
    check_stdout(run_program(candidate_path, assignments={'n': '7'}), '5040', 'tail')


def test_t5(candidate_path):
    # release: Input:\nn = 10\nOutput:\n3628800
    check_stdout(run_program(candidate_path, assignments={'n': '10'}), '3628800', 'tail')
