# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/076 | mode: original | kind: function | entry: digit_count | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called digit_count. digit_count should\n#take as input a number, which could be either a float or an\n#integer. It should return ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/076', 'kind': 'function', 'entry': 'digit_count'}
ENV = None


def test_t1(m):
    # release: Input:\n11223\nOutput:\n{1: 2, 2: 2, 3: 1}
    check(call(m, TASK, (11223,), {}), {1: 2, 2: 2, 3: 1}, 'eq')


def test_t2(m):
    # release: Input:\n3.14159\nOutput:\n{3: 1, 1: 2, 4: 1, 5: 1, 9: 1}
    check(call(m, TASK, (3.14159,), {}), {3: 1, 1: 2, 4: 1, 5: 1, 9: 1}, 'eq')


def test_t3(m):
    # release: Input:\n444.888\nOutput:\n{4: 3, 8: 3}
    check(call(m, TASK, (444.888,), {}), {4: 3, 8: 3}, 'eq')


def test_t4(m):
    # release: Input:\n0.123456789\nOutput:\n{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
    check(call(m, TASK, (0.123456789,), {}), {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}, 'eq')


def test_t5(m):
    # release: Input:\n123456789123456789\nOutput:\n{1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2}
    check(call(m, TASK, (123456789123456789,), {}), {1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2}, 'eq')
