# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/019 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- external_service: needs a live web API (CoinDesk) whose price the tests freeze at an old value
# Prompt: implement a program that:\n\nPrompts the user to input the number of Bitcoins,\n, that they would like to buy. If that input cannot be converted ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/019', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 1\nExpected Output:\nThe current cost of 1 Bitcoin(s) is $29,385.3229
    check_stdout(run_program(candidate_path, stdin='1\n'), 'The current cost of 1 Bitcoin(s) is $29,385.3229', 'tail')


def test_t2(candidate_path):
    # release: Input: 2\nExpected Output:\nThe current cost of 2 Bitcoin(s) is $58,770.6458
    check_stdout(run_program(candidate_path, stdin='2\n'), 'The current cost of 2 Bitcoin(s) is $58,770.6458', 'tail')


def test_t3(candidate_path):
    # release: Input: 0.5\nExpected Output:\nThe current cost of 0.5 Bitcoin(s) is $14,692.6615
    check_stdout(run_program(candidate_path, stdin='0.5\n'), 'The current cost of 0.5 Bitcoin(s) is $14,692.6615', 'tail')


def test_t4(candidate_path):
    # release: Input: 10\nExpected Output:\nThe current cost of 10 Bitcoin(s) is $293,853.2290
    check_stdout(run_program(candidate_path, stdin='10\n'), 'The current cost of 10 Bitcoin(s) is $293,853.2290', 'tail')


def test_t5(candidate_path):
    # release: Input: abc (Invalid Input)\nExpected Output:\nError: The input cannot be converted to a float.
    check_stdout(run_program(candidate_path, stdin='abc\n'), 'Error: The input cannot be converted to a float.', 'tail')
