# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/005 | mode: original | kind: program | entry: None | comparison: contains_ci
# Well-posed: yes
# Note: The prompt names the phrases ('breakfast time', ...) but no surrounding text.
# Prompt: Suppose that you’re in a country where it’s customary to eat breakfast between 7:00 and 8:00, lunch between 12:00 and 13:00, and dinner between ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/005', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 7:30\nOutput: It's breakfast time!
    check_stdout(run_program(candidate_path, stdin='7:30\n'), "It's breakfast time!", 'contains_ci')


def test_t2(candidate_path):
    # release: Input: 12:15\nOutput: It's lunch time!
    check_stdout(run_program(candidate_path, stdin='12:15\n'), "It's lunch time!", 'contains_ci')


def test_t3(candidate_path):
    # release: Input: 19:00\nOutput: It's dinner time!
    check_stdout(run_program(candidate_path, stdin='19:00\n'), "It's dinner time!", 'contains_ci')


def test_t4(candidate_path):
    # release: Input: 6:45\nOutput: (No output)
    check_stdout(run_program(candidate_path, stdin='6:45\n'), '', 'empty')


def test_t5(candidate_path):
    # release: Input: 13:15\nOutput: (No output)
    check_stdout(run_program(candidate_path, stdin='13:15\n'), '', 'empty')
