# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/015 | mode: original | kind: program | entry: None | comparison: suffix
# Well-posed: yes
# Note: Needs the third-party 'emoji' package (as the CS50 task does).
# Prompt: Because emoji aren’t quite as easy to type as text, at least on laptops and desktops, some programs support “codes,” whereby you can type, for ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/015', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "I am happy today :thumbs_up:"\nOutput: "I am happy today 👍"
    check_stdout(run_program(candidate_path, stdin='I am happy today :thumbs_up:\n'), 'I am happy today 👍', 'suffix')


def test_t2(candidate_path):
    # release: Input: "It's raining :umbrella:"\nOutput: "It's raining ☔"
    check_stdout(run_program(candidate_path, stdin="It's raining :umbrella:\n"), "It's raining ☔", 'suffix')


def test_t3(candidate_path):
    # release: Input: "Having pizza for dinner :pizza:"\nOutput: "Having pizza for dinner 🍕"
    check_stdout(run_program(candidate_path, stdin='Having pizza for dinner :pizza:\n'), 'Having pizza for dinner 🍕', 'suffix')


def test_t4(candidate_path):
    # release: Input: "Going for a run :runner:"\nOutput: "Going for a run 🏃"
    check_stdout(run_program(candidate_path, stdin='Going for a run :runner:\n'), 'Going for a run 🏃', 'suffix')


def test_t5(candidate_path):
    # release: Input: "I love my cat :cat:"\nOutput: "I love my cat 🐱"
    check_stdout(run_program(candidate_path, stdin='I love my cat :cat:\n'), 'I love my cat 🐱', 'suffix')
