# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/028 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- library_dependent: the accepted inputs depend on which third-party validator library is used
# Prompt: When creating a Google Form that prompts users for a short answer (or paragraph), it’s possible to enable response validation and require that the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/028', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: john.doe@example.com\nExpected Output: Valid
    check_stdout(run_program(candidate_path, stdin='john.doe@example.com\n'), 'Valid', 'tail')


def test_t2(candidate_path):
    # release: Input: john.doe@example\nExpected Output: Invalid
    check_stdout(run_program(candidate_path, stdin='john.doe@example\n'), 'Invalid', 'tail')


def test_t3(candidate_path):
    # release: Input: john.doe@.com\nExpected Output: Invalid
    check_stdout(run_program(candidate_path, stdin='john.doe@.com\n'), 'Invalid', 'tail')


def test_t4(candidate_path):
    # release: Input: john.doe@exa_mple.com\nExpected Output: Valid
    check_stdout(run_program(candidate_path, stdin='john.doe@exa_mple.com\n'), 'Valid', 'tail')


def test_t5(candidate_path):
    # release: Input: john.doe@exa mple.com\nExpected Output: Invalid
    check_stdout(run_program(candidate_path, stdin='john.doe@exa mple.com\n'), 'Invalid', 'tail')
