# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/085 | mode: original | kind: function | entry: check_pingpong_winner | comparison: eq
# Well-posed: yes
# Prompt: #In ping-pong (table tennis), the first person to score 21\n#points wins. However, they must win by 2. So, if the score\n#is 21-20, they keep ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/085', 'kind': 'function', 'entry': 'check_pingpong_winner'}
ENV = None


def test_t1(m):
    # release: Input: (19, 13)\nOutput: "Keep playing!"
    check(call(m, TASK, ((19, 13),), {}), 'Keep playing!', 'eq')


def test_t2(m):
    # release: Input: (21, 13)\nOutput: "Player 1 wins!"
    check(call(m, TASK, ((21, 13),), {}), 'Player 1 wins!', 'eq')


def test_t3(m):
    # release: Input: (19, 21)\nOutput: "Player 2 wins!"
    check(call(m, TASK, ((19, 21),), {}), 'Player 2 wins!', 'eq')


def test_t4(m):
    # release: Input: (21, 20)\nOutput: "Keep playing!"
    check(call(m, TASK, ((21, 20),), {}), 'Keep playing!', 'eq')


def test_t5(m):
    # release: Input: (25, 25)\nOutput: "Keep playing!"
    check(call(m, TASK, ((25, 25),), {}), 'Keep playing!', 'eq')
