# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/022 | mode: original | kind: function | entry: is_valid | comparison: eq
# Well-posed: yes
# Prompt: implement Vanity Plates from Problem Set 2, restructuring your code per the below, wherein is_valid still expects a str as input and returns True ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/022', 'kind': 'function', 'entry': 'is_valid'}
ENV = None


def test_t1(m):
    # release: Input: "AB1234"\nExpected Output: "Valid"
    check(call(m, TASK, ('AB1234',), {}), 'Valid', 'eq')


def test_t2(m):
    # release: Input: "A1234"\nExpected Output: "Invalid" (The plate does not start with at least two letters)
    check(call(m, TASK, ('A1234',), {}), 'Invalid', 'eq')


def test_t3(m):
    # release: Input: "ABCD12"\nExpected Output: "Valid"
    check(call(m, TASK, ('ABCD12',), {}), 'Valid', 'eq')


def test_t4(m):
    # release: Input: "AB12CD"\nExpected Output: "Invalid" (Numbers are used in the middle of the plate)
    check(call(m, TASK, ('AB12CD',), {}), 'Invalid', 'eq')


def test_t5(m):
    # release: Input: "ABCD123"\nExpected Output: "Invalid" (The plate contains more than 6 characters)
    check(call(m, TASK, ('ABCD123',), {}), 'Invalid', 'eq')
