# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/032 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: yes
# Prompt: Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Use 35 hours and a rate of 2.75 per hour to test ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/032', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: Hours = 35, Rate = 2.75\nExpected Output: Gross Pay = 96.25
    check_stdout(run_program(candidate_path, stdin='35\n2.75\n'), '96.25', 'num')


def test_t2(candidate_path):
    # release: Input: Hours = 40, Rate = 10\nExpected Output: Gross Pay = 400
    check_stdout(run_program(candidate_path, stdin='40\n10\n'), '400', 'num')


def test_t3(candidate_path):
    # release: Input: Hours = 50, Rate = 20\nExpected Output: Gross Pay = 1000
    check_stdout(run_program(candidate_path, stdin='50\n20\n'), '1000', 'num')


def test_t4(candidate_path):
    # release: Input: Hours = 0, Rate = 100\nExpected Output: Gross Pay = 0
    check_stdout(run_program(candidate_path, stdin='0\n100\n'), '0', 'num')


def test_t5(candidate_path):
    # release: Input: Hours = 100, Rate = 0\nExpected Output: Gross Pay = 0
    check_stdout(run_program(candidate_path, stdin='100\n0\n'), '0', 'num')
