# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/060 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: list_sum = 7\nlist_count = 0\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change these ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/060', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nlist_sum = 15\nlist_count = 3\nOutput:\n5.0
    check_stdout(run_program(candidate_path, assignments={'list_sum': '15', 'list_count': '3'}), '5.0', 'tail')


def test_t2(candidate_path):
    # release: Input:\nlist_sum = 0\nlist_count = 0\nOutput:\n"Can't divide by zero!"
    check_stdout(run_program(candidate_path, assignments={'list_sum': '0', 'list_count': '0'}), "Can't divide by zero!", 'tail')


def test_t3(candidate_path):
    # release: Input:\nlist_sum = 100\nlist_count = 25\nOutput:\n4.0
    check_stdout(run_program(candidate_path, assignments={'list_sum': '100', 'list_count': '25'}), '4.0', 'tail')


def test_t4(candidate_path):
    # release: Input:\nlist_sum = -50\nlist_count = 5\nOutput:\n-10.0
    check_stdout(run_program(candidate_path, assignments={'list_sum': '-50', 'list_count': '5'}), '-10.0', 'tail')


def test_t5(candidate_path):
    # release: Input:\nlist_sum = 123456\nlist_count = 1\nOutput:\n123456.0
    check_stdout(run_program(candidate_path, assignments={'list_sum': '123456', 'list_count': '1'}), '123456.0', 'tail')
