# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/101 | mode: original | kind: function | entry: add_to_dictionary | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called add_to_dictionary. add_to_dictionary\n#should have three parameters: a dictionary, a potential new\n#key, and a potential ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/101', 'kind': 'function', 'entry': 'add_to_dictionary'}
ENV = None


def test_t1(m):
    # release: Input: {}, 5, "five"\nOutput: {5: "five"}
    check(call_or_arg(m, TASK, ({}, 5, 'five'), {}), {5: 'five'}, 'eq')


def test_t2(m):
    # release: Input: {1: "one", 2: "two"}, "three", 3\nOutput: {1: "one", 2: "two", "three": 3}
    check(call_or_arg(m, TASK, ({1: 'one', 2: 'two'}, 'three', 3), {}), {1: 'one', 2: 'two', 'three': 3}, 'eq')


def test_t3(m):
    # release: Input: {"a": 1, "b": 2}, ["c"], 3\nOutput: "Error!"
    check(call_or_arg(m, TASK, ({'a': 1, 'b': 2}, ['c'], 3), {}), 'Error!', 'eq')


def test_t4(m):
    # release: Input: {1: "one", 2: "two"}, 3, "three"\nOutput: {1: "one", 2: "two"}
    check(call_or_arg(m, TASK, ({1: 'one', 2: 'two'}, 3, 'three'), {}), {1: 'one', 2: 'two'}, 'eq')


def test_t5(m):
    # release: Input: {1: "one", "two": 2}, ("three",), 3\nOutput: {1: "one", "two": 2, ("three",): 3}
    check(call_or_arg(m, TASK, ({1: 'one', 'two': 2}, ('three',), 3), {}), {1: 'one', 'two': 2, ('three',): 3}, 'eq')
