# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/089 | mode: original | kind: function | entry: not_list | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called not_list. not_list should have two\n#parameters: a list of booleans and a list of integers.\n#\n#The list of integers ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/089', 'kind': 'function', 'entry': 'not_list'}
ENV = None


def test_t1(m):
    # release: Input:\nbool_list = [True, False, False]\nindex_list = [0, 2]\nOutput:\n[False, False, True]
    check(call_or_arg(m, TASK, ([True, False, False], [0, 2]), {}), [False, False, True], 'eq')


def test_t2(m):
    # release: Input:\nbool_list = [True, True, True, True]\nindex_list = [0, 2, 3]\nOutput:\n[False, True, False, ...
    check(call_or_arg(m, TASK, ([True, True, True, True], [0, 2, 3]), {}), [False, True, False, False], 'eq')


def test_t3(m):
    # release: Input:\nbool_list = [False, False, False, False]\nindex_list = [1, 2, 3]\nOutput:\n[False, True, ...
    check(call_or_arg(m, TASK, ([False, False, False, False], [1, 2, 3]), {}), [False, True, True, True], 'eq')


def test_t4(m):
    # release: Input:\nbool_list = [True, True, True]\nindex_list = [1, 1, 1]\nOutput:\n[True, False, True]
    check(call_or_arg(m, TASK, ([True, True, True], [1, 1, 1]), {}), [True, False, True], 'eq')


def test_t5(m):
    # release: Input:\nbool_list = [True, True, True, True, True]\nindex_list = [0, 1, 2, 3, 4]\nOutput:\n[False, ...
    check(call_or_arg(m, TASK, ([True, True, True, True, True], [0, 1, 2, 3, 4]), {}), [False, False, False, False, False], 'eq')
