# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/087 | mode: original | kind: function | entry: check_value | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called check_value. check_value should\n#take as input two parameters: a dictionary and a string.\n#Both the keys and the values ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/087', 'kind': 'function', 'entry': 'check_value'}
ENV = None


def test_t1(m):
    # release: Input:\nd = {"k1": "1.1", "k2": "1", "k3": "1.4.6", "k4": "a"}\nkey = "k1"\nOutput:\n"Float!"
    check(call(m, TASK, ({'k1': '1.1', 'k2': '1', 'k3': '1.4.6', 'k4': 'a'}, 'k1'), {}), 'Float!', 'eq')


def test_t2(m):
    # release: Input:\nd = {"k1": "1.1", "k2": "1", "k3": "1.4.6", "k4": "a"}\nkey = "k2"\nOutput:\n"Integer!"
    check(call(m, TASK, ({'k1': '1.1', 'k2': '1', 'k3': '1.4.6', 'k4': 'a'}, 'k2'), {}), 'Integer!', 'eq')


def test_t3(m):
    # release: Input:\nd = {"k1": "1.1", "k2": "1", "k3": "1.4.6", "k4": "a"}\nkey = "k3"\nOutput:\n"String!"
    check(call(m, TASK, ({'k1': '1.1', 'k2': '1', 'k3': '1.4.6', 'k4': 'a'}, 'k3'), {}), 'String!', 'eq')


def test_t4(m):
    # release: Input:\nd = {"k1": "1.1", "k2": "1", "k3": "1.4.6", "k4": "a"}\nkey = "k4"\nOutput:\n"String!"
    check(call(m, TASK, ({'k1': '1.1', 'k2': '1', 'k3': '1.4.6', 'k4': 'a'}, 'k4'), {}), 'String!', 'eq')


def test_t5(m):
    # release: Input:\nd = {"k1": "1.1", "k2": "1", "k3": "1.4.6", "k4": "a"}\nkey = "k5"\nOutput:\n"Not found!"
    check(call(m, TASK, ({'k1': '1.1', 'k2': '1', 'k3': '1.4.6', 'k4': 'a'}, 'k5'), {}), 'Not found!', 'eq')
