# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/024 | mode: original | kind: function | entry: validate | comparison: eq
# Well-posed: yes
# Prompt: In Season 5, Episode 23 of NUMB3RS, a supposed IP address appears on screen, 275.3.6.28, which isn’t actually a valid IPv4 (or IPv6) ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/024', 'kind': 'function', 'entry': 'validate'}
ENV = None


def test_t1(m):
    # release: Input: "192.168.1.1"\nExpected Output: True
    check(call(m, TASK, ('192.168.1.1',), {}), True, 'eq')


def test_t2(m):
    # release: Input: "255.255.255.255"\nExpected Output: True
    check(call(m, TASK, ('255.255.255.255',), {}), True, 'eq')


def test_t3(m):
    # release: Input: "275.3.6.28"\nExpected Output: False (275 is not in the range 0-255)
    check(call(m, TASK, ('275.3.6.28',), {}), False, 'eq')


def test_t4(m):
    # release: Input: "192.168.1.256"\nExpected Output: False (256 is not in the range 0-255)
    check(call(m, TASK, ('192.168.1.256',), {}), False, 'eq')


def test_t5(m):
    # release: Input: "192.168.1"\nExpected Output: False (There are not 4 octets)
    check(call(m, TASK, ('192.168.1',), {}), False, 'eq')
