# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/094 | mode: original | kind: function | entry: check_volleyball_winner | comparison: eq
# Well-posed: yes
# Prompt: #In volleyball, the first team to score 25 points wins.\n#However, they must win by 2. So, if the score is 25-24,\n#they keep playing until ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/094', 'kind': 'function', 'entry': 'check_volleyball_winner'}
ENV = None


def test_t1(m):
    # release: Input: check_volleyball_winner((23, 17))\nOutput: "Keep playing!"
    check(call(m, TASK, ((23, 17),), {}), 'Keep playing!', 'eq')


def test_t2(m):
    # release: Input: check_volleyball_winner((25, 17))\nOutput: "Team 1 wins!"
    check(call(m, TASK, ((25, 17),), {}), 'Team 1 wins!', 'eq')


def test_t3(m):
    # release: Input: check_volleyball_winner((23, 25))\nOutput: "Team 2 wins!"
    check(call(m, TASK, ((23, 25),), {}), 'Team 2 wins!', 'eq')


def test_t4(m):
    # release: Input: check_volleyball_winner((25, 24))\nOutput: "Keep playing!"
    check(call(m, TASK, ((25, 24),), {}), 'Keep playing!', 'eq')


def test_t5(m):
    # release: Input: check_volleyball_winner((29, 29))\nOutput: "Keep playing!"
    check(call(m, TASK, ((29, 29),), {}), 'Keep playing!', 'eq')
