# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/099 | mode: original | kind: function | entry: find_gcf | comparison: eq
# Well-posed: yes
# Prompt: #The Greatest Common Factor (GCF) of two numbers is the\n#largest number that divides evenly into those two\n#numbers. For example, the Greatest ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/099', 'kind': 'function', 'entry': 'find_gcf'}
ENV = None


def test_t1(m):
    # release: Input: (48, 18)\nOutput: 6
    check(call(m, TASK, (48, 18), {}), 6, 'eq')


def test_t2(m):
    # release: Input: (21, 7)\nOutput: 7
    check(call(m, TASK, (21, 7), {}), 7, 'eq')


def test_t3(m):
    # release: Input: (47, 17)\nOutput: 1
    check(call(m, TASK, (47, 17), {}), 1, 'eq')


def test_t4(m):
    # release: Input: (60, 45)\nOutput: 15
    check(call(m, TASK, (60, 45), {}), 15, 'eq')


def test_t5(m):
    # release: Input: (100, 25)\nOutput: 25
    check(call(m, TASK, (100, 25), {}), 25, 'eq')
