# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/018 | mode: original | kind: program | entry: None | comparison: contains
# Well-posed: NO -- nondeterministic: the output depends on random numbers the tests cannot know; release tests 4-5 ignore the prompt's three-tries rule
# Note: Random numbers fixed to the problems listed in each release test.
# Prompt: One of David’s first toys as a child, funny enough, was Little Professor, a “calculator” that would generate ten different math problems for David ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/018', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: est Case 1:\nInput:\nLevel: 1\nProblems: 1 + 1, 2 + 2, 3 + 3, 4 + 4, 5 + 5, 6 + 6, 7 + 7, 8 + 8, 9 + ...
    check_stdout(run_program(candidate_path, stdin='1\n2\n4\n6\n8\n10\n12\n14\n16\n18\n0\n', env={'CSE_RANDOM_SEQ': '[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 0, 0]'}), 'Score: 10/10', 'contains')


def test_t2(candidate_path):
    # release: Input:\nLevel: 2\nProblems: 11 + 11, 22 + 22, 33 + 33, 44 + 44, 55 + 55, 66 + 66, 77 + 77, 88 + 88, ...
    check_stdout(run_program(candidate_path, stdin='2\n22\n44\n66\n88\n110\n132\n154\n176\n198\n0\n', env={'CSE_RANDOM_SEQ': '[11, 11, 22, 22, 33, 33, 44, 44, 55, 55, 66, 66, 77, 77, 88, 88, 99, 99, 0, 0]'}), 'Score: 10/10', 'contains')


def test_t3(candidate_path):
    # release: Input:\nLevel: 3\nProblems: 111 + 111, 222 + 222, 333 + 333, 444 + 444, 555 + 555, 666 + 666, 777 + ...
    check_stdout(run_program(candidate_path, stdin='3\n222\n444\n666\n888\n1110\n1332\n1554\n1776\n1998\n0\n', env={'CSE_RANDOM_SEQ': '[111, 111, 222, 222, 333, 333, 444, 444, 555, 555, 666, 666, 777, 777, 888, 888, 999, 999, 0, 0]'}), 'Score: 10/10', 'contains')


def test_t4(candidate_path):
    # release: Input:\nLevel: 1\nProblems: 1 + 1, 2 + 2, 3 + 3, 4 + 4, 5 + 5, 6 + 6, 7 + 7, 8 + 8, 9 + 9, 0 + ...
    check_stdout(run_program(candidate_path, stdin='1\n2\n5\n6\n8\n10\n12\n14\n16\n18\n0\n', env={'CSE_RANDOM_SEQ': '[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 0, 0]'}), 'Score: 9/10', 'contains')


def test_t5(candidate_path):
    # release: Input:\nLevel: 2\nProblems: 11 + 11, 22 + 22, 33 + 33, 44 + 44, 55 + 55, 66 + 66, 77 + 77, 88 + 88, ...
    check_stdout(run_program(candidate_path, stdin='2\n22\n45\n66\n88\n110\n132\n154\n176\n198\n0\n', env={'CSE_RANDOM_SEQ': '[11, 11, 22, 22, 33, 33, 44, 44, 55, 55, 66, 66, 77, 77, 88, 88, 99, 99, 0, 0]'}), 'Score: 9/10', 'contains')
