# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/069 | mode: original | kind: function | entry: pivot_library | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called pivot_library. pivot_library takes\n#as input one parameter, a list of 3-tuples. Each tuple in\n#the list has three ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/069', 'kind': 'function', 'entry': 'pivot_library'}
ENV = None


def test_t1(m):
    # release: Input: [("To Kill a Mockingbird", "Harper Lee", "978-0-06-093546-7"), ("1984", "George Orwell", ...
    check(call(m, TASK, ([('To Kill a Mockingbird', 'Harper Lee', '978-0-06-093546-7'), ('1984', 'George Orwell', '978-0-452-28423-4')],), {}), {'978-0-06-093546-7': ('To Kill a Mockingbird', 'Harper Lee'), '978-0-452-28423-4': ('1984', 'George Orwell')}, 'eq')


def test_t2(m):
    # release: Input: []\nOutput: {}\n\nExplanation: An empty list as input should return an empty dictionary as no ...
    check(call(m, TASK, ([],), {}), {}, 'eq')


def test_t3(m):
    # release: Input: [("The Great Gatsby", "F. Scott Fitzgerald", "978-0-7432-7356-5")]\nOutput: ...
    check(call(m, TASK, ([('The Great Gatsby', 'F. Scott Fitzgerald', '978-0-7432-7356-5')],), {}), {'978-0-7432-7356-5': ('The Great Gatsby', 'F. Scott Fitzgerald')}, 'eq')


def test_t4(m):
    # release: Input: [("Moby Dick", "Herman Melville", "978-0-14-243724-7"), ("Moby Dick", "Herman Melville", ...
    check(call(m, TASK, ([('Moby Dick', 'Herman Melville', '978-0-14-243724-7'), ('Moby Dick', 'Herman Melville', '978-0-14-243724-7')],), {}), {'978-0-14-243724-7': ('Moby Dick', 'Herman Melville')}, 'eq')


def test_t5(m):
    # release: Input: [("Brave New World", "Aldous Huxley", "978-0-06-085052-4"), ("Slaughterhouse-Five", "Kurt ...
    check(call(m, TASK, ([('Brave New World', 'Aldous Huxley', '978-0-06-085052-4'), ('Slaughterhouse-Five', 'Kurt Vonnegut', '978-0-385-33384-9'), ('The Catcher in the Rye', 'J.D. Salinger', '978-0-316-76948-1')],), {}), {'978-0-06-085052-4': ('Brave New World', 'Aldous Huxley'), '978-0-385-33384-9': ('Slaughterhouse-Five', 'Kurt Vonnegut'), '978-0-316-76948-1': ('The Catcher in the Rye', 'J.D. Salinger')}, 'eq')
