# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/064 | mode: original | kind: function | entry: sum_evens | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called sum_evens. sum_evens should take\n#two parameters: a minimum and a maximum. It should add up\n#all the even numbers ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/064', 'kind': 'function', 'entry': 'sum_evens'}
ENV = None


def test_t1(m):
    # release: Input:\n2, 6\nOutput:\n12
    check(call(m, TASK, (2, 6), {}), 12, 'eq')


def test_t2(m):
    # release: Input:\n1, 10\nOutput:\n30
    check(call(m, TASK, (1, 10), {}), 30, 'eq')


def test_t3(m):
    # release: Input:\n7, 9\nOutput:\n8
    check(call(m, TASK, (7, 9), {}), 8, 'eq')


def test_t4(m):
    # release: Input:\n0, 0\nOutput:\n0
    check(call(m, TASK, (0, 0), {}), 0, 'eq')


def test_t5(m):
    # release: Input:\n20, 30\nOutput:\n150
    check(call(m, TASK, (20, 30), {}), 150, 'eq')
