# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/096 | mode: original | kind: function | entry: create_palindrome | comparison: eq
# Well-posed: yes
# Prompt: #A palindrome is a sequence of letters that is the same\n#forward and backward. For example, "racecar" is a\n#palindrome.\n#\n#Write a function ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/096', 'kind': 'function', 'entry': 'create_palindrome'}
ENV = None


def test_t1(m):
    # release: Input: "abc"\nOutput: "abccba"
    check(call(m, TASK, ('abc',), {}), 'abccba', 'eq')


def test_t2(m):
    # release: Input: "racecar"\nOutput: "racecar"
    check(call(m, TASK, ('racecar',), {}), 'racecar', 'eq')


def test_t3(m):
    # release: Input: "Madam in Eden, I'm Adam"\nOutput: "Madam in Eden, I'm Adam"
    check(call(m, TASK, ("Madam in Eden, I'm Adam",), {}), "Madam in Eden, I'm Adam", 'eq')


def test_t4(m):
    # release: Input: "Hello there!"\nOutput: "Hello there!!ereht olleH"
    check(call(m, TASK, ('Hello there!',), {}), 'Hello there!!ereht olleH', 'eq')


def test_t5(m):
    # release: Input: "Was it a car or a cat I saw?"\nOutput: "Was it a car or a cat I saw?was I tac a ro rac a ti saW"
    check(call(m, TASK, ('Was it a car or a cat I saw?',), {}), 'Was it a car or a cat I saw?was I tac a ro rac a ti saW', 'eq')
