# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/041 | mode: original | kind: vars | entry: None | comparison: num
# Well-posed: yes
# Prompt: goal = 50000\nrate = 0.05\nyears = 5\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/041', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\ngoal = 50000\nrate = 0.05\nyears = 5\nOutput:\nPrincipal needed: 39283.56
    check_stdout(run_program(candidate_path, assignments={'goal': '50000', 'rate': '0.05', 'years': '5'}), '39283.56', 'num')


def test_t2(candidate_path):
    # release: Input:\ngoal = 100000\nrate = 0.07\nyears = 10\nOutput:\nPrincipal needed: 50834.86
    check_stdout(run_program(candidate_path, assignments={'goal': '100000', 'rate': '0.07', 'years': '10'}), '50834.86', 'num')


def test_t3(candidate_path):
    # release: Input:\ngoal = 5000\nrate = 0.03\nyears = 3\nOutput:\nPrincipal needed: 4596.05
    check_stdout(run_program(candidate_path, assignments={'goal': '5000', 'rate': '0.03', 'years': '3'}), '4596.05', 'num')


def test_t4(candidate_path):
    # release: Input:\ngoal = 150000\nrate = 0.06\nyears = 7\nOutput:\nPrincipal needed: 104499.31
    check_stdout(run_program(candidate_path, assignments={'goal': '150000', 'rate': '0.06', 'years': '7'}), '104499.31', 'num')


def test_t5(candidate_path):
    # release: Input:\ngoal = 20000\nrate = 0.02\nyears = 2\nOutput:\nPrincipal needed: 19269.25
    check_stdout(run_program(candidate_path, assignments={'goal': '20000', 'rate': '0.02', 'years': '2'}), '19269.25', 'num')
