# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/081 | mode: original | kind: function | entry: restaurant_rating | comparison: eq
# Well-posed: yes
# Prompt: #Imagine you are trying to choose what restaurant to visit.\n#You have a list of restaurants, each with a collection of\n#star ratings. You also ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/081', 'kind': 'function', 'entry': 'restaurant_rating'}
ENV = None


def test_t1(m):
    # release: Input:\nrest_and_rating = {'burger king': [4, 5, 3, 4, 3], 'moes': [4, 5, 5, 5, 5], 'taco bell': [1, ...
    check(call(m, TASK, ({'burger king': [4, 5, 3, 4, 3], 'moes': [4, 5, 5, 5, 5], 'taco bell': [1, 2, 3, 4, 5]}, 4.5), {}), ['moes'], 'eq')


def test_t2(m):
    # release: Input:\nrest_and_rating = {'pizza hut': [3, 4, 3, 4, 3], 'papa johns': [4, 4, 5, 5, 4], 'dominos': ...
    check(call(m, TASK, ({'pizza hut': [3, 4, 3, 4, 3], 'papa johns': [4, 4, 5, 5, 4], 'dominos': [2, 3, 2, 2, 3]}, 4.0), {}), ['papa johns'], 'eq')


def test_t3(m):
    # release: Input:\nrest_and_rating = {'subway': [3, 4, 3, 2, 3], 'quiznos': [2, 2, 2, 2, 2], 'jimmy johns': [4, ...
    check(call(m, TASK, ({'subway': [3, 4, 3, 2, 3], 'quiznos': [2, 2, 2, 2, 2], 'jimmy johns': [4, 5, 5, 5, 4]}, 2.5), {}), ['subway', 'jimmy johns'], 'eq')


def test_t4(m):
    # release: Input:\nrest_and_rating = {'kfc': [4, 3, 4, 4, 3], 'popeyes': [5, 4, 4, 5, 5], 'chick-fil-a': [5, 5, ...
    check(call(m, TASK, ({'kfc': [4, 3, 4, 4, 3], 'popeyes': [5, 4, 4, 5, 5], 'chick-fil-a': [5, 5, 5, 5, 5]}, 4.2), {}), ['kfc', 'popeyes', 'chick-fil-a'], 'eq')


def test_t5(m):
    # release: Input:\nrest_and_rating = {'mcdonalds': [2, 2, 3, 3, 2], 'wendys': [3, 3, 3, 4, 3], 'sonic': [4, 4, ...
    check(call(m, TASK, ({'mcdonalds': [2, 2, 3, 3, 2], 'wendys': [3, 3, 3, 4, 3], 'sonic': [4, 4, 5, 4, 4]}, 3.3), {}), ['wendys', 'sonic'], 'eq')
