# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/092 | mode: original | kind: function | entry: inverted_sort | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called inverted_sort. inverted_ should\n#take as input a list of integers, and return as output a\n#list with the integers ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/092', 'kind': 'function', 'entry': 'inverted_sort'}
ENV = None


def test_t1(m):
    # release: Input: [5, 2, 8, 1, 7]\nOutput: [8, 7, 5, 2, 1]
    check(call(m, TASK, ([5, 2, 8, 1, 7],), {}), [8, 7, 5, 2, 1], 'eq')


def test_t2(m):
    # release: Input: [10, 5, 20, 15, 25]\nOutput: [25, 20, 15, 10, 5]
    check(call(m, TASK, ([10, 5, 20, 15, 25],), {}), [25, 20, 15, 10, 5], 'eq')


def test_t3(m):
    # release: Input: [3, 1, 4, 1, 5, 9, 2]\nOutput: [9, 5, 4, 3, 2, 1, 1]
    check(call(m, TASK, ([3, 1, 4, 1, 5, 9, 2],), {}), [9, 5, 4, 3, 2, 1, 1], 'eq')


def test_t4(m):
    # release: Input: [100, 90, 80, 70, 60]\nOutput: [100, 90, 80, 70, 60]
    check(call(m, TASK, ([100, 90, 80, 70, 60],), {}), [100, 90, 80, 70, 60], 'eq')


def test_t5(m):
    # release: Input: [2, 1, 3, 5, 4]\nOutput: [5, 4, 3, 2, 1]
    check(call(m, TASK, ([2, 1, 3, 5, 4],), {}), [5, 4, 3, 2, 1], 'eq')
