# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/009 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: In Massachusetts, home to Harvard University, it’s possible to request a vanity license plate for your car, with your choice of letters and ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/009', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "AB1234"\nExpected Output: "Valid"
    check_stdout(run_program(candidate_path, stdin='AB1234\n'), 'Valid', 'tail')


def test_t2(candidate_path):
    # release: Input: "1AB234"\nExpected Output: "Invalid"
    check_stdout(run_program(candidate_path, stdin='1AB234\n'), 'Invalid', 'tail')


def test_t3(candidate_path):
    # release: Input: "AA"\nExpected Output: "Valid"
    check_stdout(run_program(candidate_path, stdin='AA\n'), 'Valid', 'tail')


def test_t4(candidate_path):
    # release: Input: "A1B234"\nExpected Output: "Invalid"
    check_stdout(run_program(candidate_path, stdin='A1B234\n'), 'Invalid', 'tail')


def test_t5(candidate_path):
    # release: Input: "ABCDEFG"\nExpected Output: "Invalid"
    check_stdout(run_program(candidate_path, stdin='ABCDEFG\n'), 'Invalid', 'tail')
