# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/049 | mode: original | kind: function | entry: numCombinations | comparison: eq
# Well-posed: yes
# Prompt: #A common formula in probability and statistics is the\n#formula for the number of possible combinations of r\n#objects from a set of n objects. ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/049', 'kind': 'function', 'entry': 'numCombinations'}
ENV = None


def test_t1(m):
    # release: Input:\nn = 5\nr = 2\nOutput:\n10
    check(call(m, TASK, (5, 2), {}), 10, 'eq')


def test_t2(m):
    # release: Input:\nn = 52\nr = 2\nOutput:\n1326
    check(call(m, TASK, (52, 2), {}), 1326, 'eq')


def test_t3(m):
    # release: Input:\nn = 10\nr = 5\nOutput:\n252
    check(call(m, TASK, (10, 5), {}), 252, 'eq')


def test_t4(m):
    # release: Input:\nn = 6\nr = 6\nOutput:\n1
    check(call(m, TASK, (6, 6), {}), 1, 'eq')


def test_t5(m):
    # release: Input:\nn = 10\nr = 0\nOutput:\n1
    check(call(m, TASK, (10, 0), {}), 1, 'eq')
