# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/084 | mode: original | kind: function | entry: food_at_home | comparison: eq
# Well-posed: yes
# Prompt: #You are going through your refrigerator at home and trying to determine whether you have the proper ingredients to cook a meal.\n#\n#Write a ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/084', 'kind': 'function', 'entry': 'food_at_home'}
ENV = None


def test_t1(m):
    # release: Input:\nfood_list = ["chicken", "mixed veggies", "greens", "beans", "corn", "cooking ...
    check(call(m, TASK, (['chicken', 'mixed veggies', 'greens', 'beans', 'corn', 'cooking oil'],), {}), 'You do have food, your options are chicken or mixed veggies or greens or beans or corn', 'eq')


def test_t2(m):
    # release: Input:\nfood_list = ["pasta", "tomato sauce", "cheese"]\nOutput:\n"I guess it's pizza tonight"
    check(call(m, TASK, (['pasta', 'tomato sauce', 'cheese'],), {}), "I guess it's pizza tonight", 'eq')


def test_t3(m):
    # release: Input:\nfood_list = ["eggs", "milk", "bread", "butter", "cooking oil"]\nOutput:\n"You do have food, ...
    check(call(m, TASK, (['eggs', 'milk', 'bread', 'butter', 'cooking oil'],), {}), 'You do have food, your options are eggs or milk or bread or butter', 'eq')


def test_t4(m):
    # release: Input:\nfood_list = ["salmon", "asparagus", "lemon", "olive oil", "salt", "pepper"]\nOutput:\n"You ...
    check(call(m, TASK, (['salmon', 'asparagus', 'lemon', 'olive oil', 'salt', 'pepper'],), {}), 'You do have food, your options are salmon or asparagus or lemon or salt or pepper', 'eq')


def test_t5(m):
    # release: Input:\nfood_list = ["rice", "soy sauce"]\nOutput:\n"I guess it's pizza tonight"
    check(call(m, TASK, (['rice', 'soy sauce'],), {}), "I guess it's pizza tonight", 'eq')
