# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/021 | mode: original | kind: function | entry: value | comparison: eq
# Well-posed: yes
# Prompt: implement Home Federal Savings Bank from Problem Set 1, restructuring your code per the below, wherein value expects a str as input and returns 0 ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/021', 'kind': 'function', 'entry': 'value'}
ENV = None


def test_t1(m):
    # release: Input: "Hello, World!"\nExpected Output: $0
    check(call(m, TASK, ('Hello, World!',), {}), '$0', 'eq')


def test_t2(m):
    # release: Input: "hi there"\nExpected Output: $20
    check(call(m, TASK, ('hi there',), {}), '$20', 'eq')


def test_t3(m):
    # release: Input: "Hey, how are you?"\nExpected Output: $20
    check(call(m, TASK, ('Hey, how are you?',), {}), '$20', 'eq')


def test_t4(m):
    # release: Input: "Good morning"\nExpected Output: $100
    check(call(m, TASK, ('Good morning',), {}), '$100', 'eq')


def test_t5(m):
    # release: Input: "HELLO"\nExpected Output: $0
    check(call(m, TASK, ('HELLO',), {}), '$0', 'eq')
