# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/077 | mode: original | kind: function | entry: complete_profile | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called complete_profile. complete_profile\n#will take as input a dictionary. This dictionary will have\n#four keys: first, ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/077', 'kind': 'function', 'entry': 'complete_profile'}
ENV = None


def test_t1(m):
    # release: Input:\n{"first": "David", "middle": "Andrew", "last": "Joyner", "title": "Dr."}\nOutput:\n{"first": ...
    check(call_or_arg(m, TASK, ({'first': 'David', 'middle': 'Andrew', 'last': 'Joyner', 'title': 'Dr.'},), {}), {'first': 'David', 'middle': 'Andrew', 'last': 'Joyner', 'title': 'Dr.', 'name': 'David Joyner', 'full_name': 'Dr. David Andrew Joyner', 'short_name': 'D Joyner'}, 'eq')


def test_t2(m):
    # release: Input:\n{"first": "John", "middle": "Jacob", "last": "Jingleheimer", "title": ...
    check(call_or_arg(m, TASK, ({'first': 'John', 'middle': 'Jacob', 'last': 'Jingleheimer', 'title': 'Mr.'},), {}), {'first': 'John', 'middle': 'Jacob', 'last': 'Jingleheimer', 'title': 'Mr.', 'name': 'John Jingleheimer', 'full_name': 'Mr. John Jacob Jingleheimer', 'short_name': 'J Jingleheimer'}, 'eq')


def test_t3(m):
    # release: Input:\n{"first": "Jane", "middle": "Quincy", "last": "Doe", "title": "Ms."}\nOutput:\n{"first": ...
    check(call_or_arg(m, TASK, ({'first': 'Jane', 'middle': 'Quincy', 'last': 'Doe', 'title': 'Ms.'},), {}), {'first': 'Jane', 'middle': 'Quincy', 'last': 'Doe', 'title': 'Ms.', 'name': 'Jane Doe', 'full_name': 'Ms. Jane Quincy Doe', 'short_name': 'J Doe'}, 'eq')


def test_t4(m):
    # release: Input:\n{"first": "Albert", "middle": "Einstein", "last": "", "title": "Prof."}\nOutput:\n{"first": ...
    check(call_or_arg(m, TASK, ({'first': 'Albert', 'middle': 'Einstein', 'last': '', 'title': 'Prof.'},), {}), {'first': 'Albert', 'middle': 'Einstein', 'last': '', 'title': 'Prof.', 'name': 'Albert ', 'full_name': 'Prof. Albert Einstein ', 'short_name': 'A '}, 'eq')


def test_t5(m):
    # release: Input:\n{"first": "Sigmund", "middle": "", "last": "Freud", "title": "Dr."}\nOutput:\n{"first": ...
    check(call_or_arg(m, TASK, ({'first': 'Sigmund', 'middle': '', 'last': 'Freud', 'title': 'Dr.'},), {}), {'first': 'Sigmund', 'middle': '', 'last': 'Freud', 'title': 'Dr.', 'name': 'Sigmund Freud', 'full_name': 'Dr. Sigmund Freud', 'short_name': 'S Freud'}, 'eq')
