# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/038 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: balance = 500\nincome = 200\nprice = 1000\nmonths = 6\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/038', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nprice = 1000\nmonths = 6\nbalance = 1200\nincome = 100\nOutput:\nTrue
    check_stdout(run_program(candidate_path, assignments={'price': '1000', 'months': '6', 'balance': '1200', 'income': '100'}), 'True', 'tail')


def test_t2(candidate_path):
    # release: Input:\nprice = 2000\nmonths = 10\nbalance = 1500\nincome = 200\nOutput:\nTrue
    check_stdout(run_program(candidate_path, assignments={'price': '2000', 'months': '10', 'balance': '1500', 'income': '200'}), 'True', 'tail')


def test_t3(candidate_path):
    # release: Input:\nprice = 5000\nmonths = 10\nbalance = 4000\nincome = 400\nOutput:\nFalse
    check_stdout(run_program(candidate_path, assignments={'price': '5000', 'months': '10', 'balance': '4000', 'income': '400'}), 'False', 'tail')


def test_t4(candidate_path):
    # release: Input:\nprice = 800\nmonths = 4\nbalance = 500\nincome = 250\nOutput:\nTrue
    check_stdout(run_program(candidate_path, assignments={'price': '800', 'months': '4', 'balance': '500', 'income': '250'}), 'True', 'tail')


def test_t5(candidate_path):
    # release: Input:\nprice = 1200\nmonths = 12\nbalance = 1000\nincome = 80\nOutput:\nFalse
    check_stdout(run_program(candidate_path, assignments={'price': '1200', 'months': '12', 'balance': '1000', 'income': '80'}), 'False', 'tail')
