# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/012 | mode: original | kind: program | entry: None | comparison: nums
# Well-posed: yes
# Prompt: One of the most popular places to eat in Harvard Square is Felipe’s Taqueria, which offers a menu of entrees, per the dict below, wherein the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/012', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "Baja Taco", "Burrito", Control-D\nExpected Output: "$4.00", "$11.50"
    check_stdout(run_program(candidate_path, stdin='Baja Taco\nBurrito\n'), '"$4.00", "$11.50"', 'nums')


def test_t2(candidate_path):
    # release: Input: "Super Burrito", "Taco", "Bowl", Control-D\nExpected Output: "$8.50", "$11.50", "$20.00"
    check_stdout(run_program(candidate_path, stdin='Super Burrito\nTaco\nBowl\n'), '"$8.50", "$11.50", "$20.00"', 'nums')


def test_t3(candidate_path):
    # release: Input: "Nachos", "Quesadilla", "Tortilla Salad", Control-D\nExpected Output: "$11.00", "$19.50", ...
    check_stdout(run_program(candidate_path, stdin='Nachos\nQuesadilla\nTortilla Salad\n'), '"$11.00", "$19.50", "$27.50"', 'nums')


def test_t4(candidate_path):
    # release: Input: "Pasta", Control-D\nExpected Output: "Ignored - not a menu item."
    check_stdout(run_program(candidate_path, stdin='Pasta\n'), 'Ignored - not a menu item.', 'tail')


def test_t5(candidate_path):
    # release: Input: "Taco", "taco", "TACO", Control-D\nExpected Output: "$3.00", "$6.00", "$9.00"
    check_stdout(run_program(candidate_path, stdin='Taco\ntaco\nTACO\n'), '"$3.00", "$6.00", "$9.00"', 'nums')
