# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/080 | mode: original | kind: function | entry: find_winner | comparison: eq
# Well-posed: yes
# Prompt: #In the game Rock-Paper-Scissors, two opponents\n#simultaneously choose to throw either "Rock", "Paper",\n#or "Scissors". Rock beats Scissors, ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/080', 'kind': 'function', 'entry': 'find_winner'}
ENV = None


def test_t1(m):
    # release: Input:\n[("Rock", "Rock"), ("Rock", "Scissors"), ("Paper", "Rock"), ("Scissors", ...
    check(call(m, TASK, ([('Rock', 'Rock'), ('Rock', 'Scissors'), ('Paper', 'Rock'), ('Scissors', 'Rock')],), {}), 'Player 1 wins!', 'eq')


def test_t2(m):
    # release: Input:\n[("Paper", "Scissors"), ("Scissors", "Rock"), ("Rock", "Scissors"), ("Paper", ...
    check(call(m, TASK, ([('Paper', 'Scissors'), ('Scissors', 'Rock'), ('Rock', 'Scissors'), ('Paper', 'Rock')],), {}), 'Player 2 wins!', 'eq')


def test_t3(m):
    # release: Input:\n[("Rock", "Rock"), ("Scissors", "Scissors"), ("Paper", "Paper")]\nOutput:\n"It's a tie!"
    check(call(m, TASK, ([('Rock', 'Rock'), ('Scissors', 'Scissors'), ('Paper', 'Paper')],), {}), "It's a tie!", 'eq')


def test_t4(m):
    # release: Input:\n[("Rock", "Scissors"), ("Scissors", "Paper"), ("Paper", "Rock")]\nOutput:\n"Player 1 wins!"
    check(call(m, TASK, ([('Rock', 'Scissors'), ('Scissors', 'Paper'), ('Paper', 'Rock')],), {}), 'Player 1 wins!', 'eq')


def test_t5(m):
    # release: Input:\n[("Rock", "Scissors"), ("Scissors", "Rock"), ("Rock", "Rock")]\nOutput:\n"It's a tie!"
    check(call(m, TASK, ([('Rock', 'Scissors'), ('Scissors', 'Rock'), ('Rock', 'Rock')],), {}), "It's a tie!", 'eq')
