# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/043 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: spouse_1 = "Caitlin"\nspouse_2 = "David"\nmonth = "November"\nday = 3\nyear = 2012\ntime = "5:00PM"\n\n#You may modify the lines of code above, ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/043', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nspouse_1 = "Caitlin"\nspouse_2 = "David"\nmonth = "November"\nday = 3\nyear = 2012\ntime = ...
    check_stdout(run_program(candidate_path, assignments={'spouse_1': '"Caitlin"', 'spouse_2': '"David"', 'month': '"November"', 'day': '3', 'year': '2012', 'time': '"5:00PM"'}), 'You are cordially invited to attend the wedding of Caitlin and David, to take place on November 3, 2012 at 5:00PM.', 'tail')


def test_t2(candidate_path):
    # release: Input:\nspouse_1 = "John"\nspouse_2 = "Emily"\nmonth = "June"\nday = 10\nyear = 2022\ntime = ...
    check_stdout(run_program(candidate_path, assignments={'spouse_1': '"John"', 'spouse_2': '"Emily"', 'month': '"June"', 'day': '10', 'year': '2022', 'time': '"3:00PM"'}), 'You are cordially invited to attend the wedding of John and Emily, to take place on June 10, 2022 at 3:00PM.', 'tail')


def test_t3(candidate_path):
    # release: Input:\nspouse_1 = "Alice"\nspouse_2 = "Bob"\nmonth = "December"\nday = 31\nyear = 2023\ntime = ...
    check_stdout(run_program(candidate_path, assignments={'spouse_1': '"Alice"', 'spouse_2': '"Bob"', 'month': '"December"', 'day': '31', 'year': '2023', 'time': '"11:00AM"'}), 'You are cordially invited to attend the wedding of Alice and Bob, to take place on December 31, 2023 at 11:00AM.', 'tail')


def test_t4(candidate_path):
    # release: Input:\nspouse_1 = "Emma"\nspouse_2 = "Jake"\nmonth = "March"\nday = 5\nyear = 2024\ntime = ...
    check_stdout(run_program(candidate_path, assignments={'spouse_1': '"Emma"', 'spouse_2': '"Jake"', 'month': '"March"', 'day': '5', 'year': '2024', 'time': '"2:30PM"'}), 'You are cordially invited to attend the wedding of Emma and Jake, to take place on March 5, 2024 at 2:30PM.', 'tail')


def test_t5(candidate_path):
    # release: Input:\nspouse_1 = "Sophia"\nspouse_2 = "Liam"\nmonth = "August"\nday = 15\nyear = 2025\ntime = ...
    check_stdout(run_program(candidate_path, assignments={'spouse_1': '"Sophia"', 'spouse_2': '"Liam"', 'month': '"August"', 'day': '15', 'year': '2025', 'time': '"4:00PM"'}), 'You are cordially invited to attend the wedding of Sophia and Liam, to take place on August 15, 2025 at 4:00PM.', 'tail')
