# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/026 | mode: original | kind: function | entry: convert | comparison: eq
# Well-posed: yes
# Prompt: Whereas most countries use a 24-hour clock, the United States tends to use a 12-hour clock. Accordingly, instead of “09:00 to 17:00”, many ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/026', 'kind': 'function', 'entry': 'convert'}
ENV = None


def test_t1(m):
    # release: Input: "9:00 AM to 5:00 PM"\nExpected Output: "09:00 to 17:00"
    check(call(m, TASK, ('9:00 AM to 5:00 PM',), {}), '09:00 to 17:00', 'eq')


def test_t2(m):
    # release: Input: "1:00 PM to 11:00 PM"\nExpected Output: "13:00 to 23:00"
    check(call(m, TASK, ('1:00 PM to 11:00 PM',), {}), '13:00 to 23:00', 'eq')


def test_t3(m):
    # release: Input: "12:00 AM to 12:00 PM"\nExpected Output: "00:00 to 12:00"
    check(call(m, TASK, ('12:00 AM to 12:00 PM',), {}), '00:00 to 12:00', 'eq')


def test_t4(m):
    # release: Input: "5:00 PM to 9:00 AM"\nExpected Output: "17:00 to 09:00"
    check(call(m, TASK, ('5:00 PM to 9:00 AM',), {}), '17:00 to 09:00', 'eq')


def test_t5(m):
    # release: Input: "13:00 PM to 5:00 PM" (Invalid Input)\nExpected Output: Error: The input is not in the ...
    check(call(m, TASK, ('13:00 PM to 5:00 PM',), {}), 'Error: The input is not in the correct format or the time is invalid.', 'eq')
