# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/061 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: input_string = "1234"\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change these lines ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/061', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\ninput_string = "1234"\nOutput:\n"PIN"
    check_stdout(run_program(candidate_path, assignments={'input_string': '"1234"'}), 'PIN', 'tail')


def test_t2(candidate_path):
    # release: Input:\ninput_string = "12.34"\nOutput:\n"amount"
    check_stdout(run_program(candidate_path, assignments={'input_string': '"12.34"'}), 'amount', 'tail')


def test_t3(candidate_path):
    # release: Input:\ninput_string = "password123"\nOutput:\n"password"
    check_stdout(run_program(candidate_path, assignments={'input_string': '"password123"'}), 'password', 'tail')


def test_t4(candidate_path):
    # release: Input:\ninput_string = "7890"\nOutput:\n"PIN"
    check_stdout(run_program(candidate_path, assignments={'input_string': '"7890"'}), 'PIN', 'tail')


def test_t5(candidate_path):
    # release: Input:\ninput_string = "word123.45"\nOutput:\n"password"
    check_stdout(run_program(candidate_path, assignments={'input_string': '"word123.45"'}), 'password', 'tail')
