# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/002 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: implement a program that prompts the user for a greeting. If the greeting starts with “hello”, output $0. If the greeting starts with an “h” (but ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/002', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: hello world\nOutput: $0
    check_stdout(run_program(candidate_path, stdin='hello world\n'), '$0', 'tail')


def test_t2(candidate_path):
    # release: Input: Hola!\nOutput: $20
    check_stdout(run_program(candidate_path, stdin='Hola!\n'), '$20', 'tail')


def test_t3(candidate_path):
    # release: Input: hi there\nOutput: $20
    check_stdout(run_program(candidate_path, stdin='hi there\n'), '$20', 'tail')


def test_t4(candidate_path):
    # release: Input: Hello Universe\nOutput: $0
    check_stdout(run_program(candidate_path, stdin='Hello Universe\n'), '$0', 'tail')


def test_t5(candidate_path):
    # release: Input: Greetings\nOutput: $100
    check_stdout(run_program(candidate_path, stdin='Greetings\n'), '$100', 'tail')
