# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/079 | mode: original | kind: function | entry: fancy_me | comparison: eq
# Well-posed: yes
# Prompt: #It's a well-known and indisputable fact that if you want\n#to make your name sound fancy, you should list it as only\n#your first two initials ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/079', 'kind': 'function', 'entry': 'fancy_me'}
ENV = None


def test_t1(m):
    # release: Input:\n["First Middle Last", "David Andrew Joyner", "George P Burdell"]\nOutput:\n"F. M. Last, D. ...
    check(call(m, TASK, (['First Middle Last', 'David Andrew Joyner', 'George P Burdell'],), {}), 'F. M. Last, D. A. Joyner, G. P. Burdell', 'eq')


def test_t2(m):
    # release: Input:\n["John Jacob Jingleheimer", "James Richard Doe", "Jane Quincy Public"]\nOutput:\n"J. J. ...
    check(call(m, TASK, (['John Jacob Jingleheimer', 'James Richard Doe', 'Jane Quincy Public'],), {}), 'J. J. Jingleheimer, J. R. Doe, J. Q. Public', 'eq')


def test_t3(m):
    # release: Input:\n["Albert Einstein", "Isaac Newton", "Charles Darwin"]\nOutput:\n"A. Einstein, I. Newton, C. ...
    check(call(m, TASK, (['Albert Einstein', 'Isaac Newton', 'Charles Darwin'],), {}), 'A. Einstein, I. Newton, C. Darwin', 'eq')


def test_t4(m):
    # release: Input:\n["Emily Dickinson", "Robert Frost", "Walt Whitman"]\nOutput:\n"E. Dickinson, R. Frost, W. ...
    check(call(m, TASK, (['Emily Dickinson', 'Robert Frost', 'Walt Whitman'],), {}), 'E. Dickinson, R. Frost, W. Whitman', 'eq')


def test_t5(m):
    # release: Input:\n["Thomas Alva Edison", "Nikola Tesla", "Alexander Graham Bell"]\nOutput:\n"T. A. Edison, N. ...
    check(call(m, TASK, (['Thomas Alva Edison', 'Nikola Tesla', 'Alexander Graham Bell'],), {}), 'T. A. Edison, N. Tesla, A. G. Bell', 'eq')
