# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/100 | mode: original | kind: function | entry: to_pig_latin | comparison: eq
# Well-posed: yes
# Prompt: #Pig Latin is a fictitious language. To translate a word into\n#Pig Latin, you would take the consonants up until the first\n#vowel, move them to ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/100', 'kind': 'function', 'entry': 'to_pig_latin'}
ENV = None


def test_t1(m):
    # release: Input: "pig"\nOutput: "igpay"
    check(call(m, TASK, ('pig',), {}), 'igpay', 'eq')


def test_t2(m):
    # release: Input: "david"\nOutput: "avidday"
    check(call(m, TASK, ('david',), {}), 'avidday', 'eq')


def test_t3(m):
    # release: Input: "trash"\nOutput: "ashtray"
    check(call(m, TASK, ('trash',), {}), 'ashtray', 'eq')


def test_t4(m):
    # release: Input: "scram"\nOutput: "amscray"
    check(call(m, TASK, ('scram',), {}), 'amscray', 'eq')


def test_t5(m):
    # release: Input: "translate"\nOutput: "anslatetray"
    check(call(m, TASK, ('translate',), {}), 'anslatetray', 'eq')
