# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/007 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: yes
# Note: Checks the last number printed (the change owed); the prompt gives no output wording.
# Prompt: Suppose that a machine sells bottles of Coca-Cola (Coke) for 50 cents and only accepts coins in these denominations: 25 cents, 10 cents, and 5 ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/007', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 25, 25\nExpected Output: "0 cents owed."
    check_stdout(run_program(candidate_path, stdin='25\n25\n'), '0', 'num')


def test_t2(candidate_path):
    # release: Input: 10, 10, 10, 10, 10, 10\nExpected Output: "10 cents owed."
    check_stdout(run_program(candidate_path, stdin='10\n10\n10\n10\n10\n10\n'), '10', 'num')


def test_t3(candidate_path):
    # release: Input: 25, 25, 10\nExpected Output: "10 cents owed."
    check_stdout(run_program(candidate_path, stdin='25\n25\n10\n'), '10', 'num')


def test_t4(candidate_path):
    # release: Input: 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5\nExpected Output: "5 cents owed."
    check_stdout(run_program(candidate_path, stdin='5\n5\n5\n5\n5\n5\n5\n5\n5\n5\n5\n'), '5', 'num')


def test_t5(candidate_path):
    # release: Input: 50\nExpected Output: "0 cents owed."
    check_stdout(run_program(candidate_path, stdin='50\n'), '0', 'num')
