# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/073 | mode: original | kind: function | entry: check_winner | comparison: eq
# Well-posed: yes
# Prompt: #Last problem, you implemented a function that could find if\n#someone had won a particular game of tic-tac-toe based on a\n#2D tuple representing ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/073', 'kind': 'function', 'entry': 'check_winner'}
ENV = None


def test_t1(m):
    # release: Input:\n(("O", "O", "X", "X", "O", "O", "O"),\n("O", "X", "O", "X", "O", "X", "X"),\n("X", "X", "O", ...
    check(call(m, TASK, ((('O', 'O', 'X', 'X', 'O', 'O', 'O'), ('O', 'X', 'O', 'X', 'O', 'X', 'X'), ('X', 'X', 'O', 'O', 'X', 'O', 'O'), ('O', 'O', 'X', 'X', 'O', 'O', 'X'), ('O', 'X', 'O', 'X', 'O', 'X', 'O'), ('X', 'X', 'O', 'O', 'X', 'O', 'X')),), {}), None, 'eq')


def test_t2(m):
    # release: Input:\n(("O", "O", "X", "X", "O", "O", "O"),\n("O", "X", "O", "X", "O", "X", "X"),\n("X", "X", "O", ...
    check(call(m, TASK, ((('O', 'O', 'X', 'X', 'O', 'O', 'O'), ('O', 'X', 'O', 'X', 'O', 'X', 'X'), ('X', 'X', 'O', 'O', 'X', 'O', 'O'), ('O', 'O', 'X', 'X', 'O', 'O', 'X'), ('O', 'X', 'O', 'X', 'X', 'X', 'X'), ('X', 'X', 'O', 'O', 'X', 'O', 'X')),), {}), 'X', 'eq')


def test_t3(m):
    # release: Input:\n(("O", "O", "X", "X", "O", "O", "O"),\n("O", "X", "O", "X", "O", "X", "O"),\n("X", "X", "O", ...
    check(call(m, TASK, ((('O', 'O', 'X', 'X', 'O', 'O', 'O'), ('O', 'X', 'O', 'X', 'O', 'X', 'O'), ('X', 'X', 'O', 'O', 'X', 'O', 'O'), ('O', 'O', 'X', 'X', 'O', 'O', 'X'), ('O', 'X', 'O', 'X', 'O', 'X', 'O'), ('X', 'X', 'O', 'O', 'O', 'O', 'O')),), {}), 'O', 'eq')


def test_t4(m):
    # release: Input:\n(("None", "None", "None", "None", "None", "None", "None"),\n("None", "None", "None", "None", ...
    check(call(m, TASK, ((('None', 'None', 'None', 'None', 'None', 'None', 'None'), ('None', 'None', 'None', 'None', 'None', 'None', 'None'), ('None', 'None', 'None', 'None', 'None', 'None', 'None'), ('None', 'None', 'None', 'None', 'None', 'None', 'None'), ('None', 'None', 'None', 'None', 'None', 'None', 'None'), ('X', 'X', 'X', 'X', 'None', 'None', 'None')),), {}), 'X', 'eq')


def test_t5(m):
    # release: Input:\n(("O", "O", "O", "X", "O", "O", "O"),\n("O", "X", "O", "X", "O", "X", "X"),\n("X", "X", "O", ...
    check(call(m, TASK, ((('O', 'O', 'O', 'X', 'O', 'O', 'O'), ('O', 'X', 'O', 'X', 'O', 'X', 'X'), ('X', 'X', 'O', 'O', 'X', 'O', 'O'), ('O', 'O', 'X', 'X', 'O', 'O', 'X'), ('O', 'X', 'O', 'X', 'O', 'X', 'O'), ('X', 'X', 'O', 'O', 'X', 'O', 'X')),), {}), 'X', 'eq')
