# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/074 | mode: original | kind: function | entry: average_rainfall | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called average_rainfall. average_rainfall\n#should have one parameter, a list of integers. The list\n#represents daily rainfall ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/074', 'kind': 'function', 'entry': 'average_rainfall'}
ENV = None


def test_t1(m):
    # release: Input:\n[5, 10, 15, -1, 20, 25]\nOutput:\n10.0
    check(call(m, TASK, ([5, 10, 15, -1, 20, 25],), {}), 10.0, 'eq')


def test_t2(m):
    # release: Input:\n[1, 2, 3, 4, 5, -1, 6, 7]\nOutput:\n3.0
    check(call(m, TASK, ([1, 2, 3, 4, 5, -1, 6, 7],), {}), 3.0, 'eq')


def test_t3(m):
    # release: Input:\n[100, 200, 300, 400, -1, 500, 600]\nOutput:\n250.0
    check(call(m, TASK, ([100, 200, 300, 400, -1, 500, 600],), {}), 250.0, 'eq')


def test_t4(m):
    # release: Input:\n[8, 7, 6, 5, 4, 3, 2, 1, -1, 0]\nOutput:\n4.5
    check(call(m, TASK, ([8, 7, 6, 5, 4, 3, 2, 1, -1, 0],), {}), 4.5, 'eq')


def test_t5(m):
    # release: Input:\n[50, 100, -1, 150, 200]\nOutput:\n75.0
    check(call(m, TASK, ([50, 100, -1, 150, 200],), {}), 75.0, 'eq')
