# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/030 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: Write a program that uses a print function to say 'hello world' as shown in 'Desired Output'.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/030', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: None\nExpected Output: hello world
    check_stdout(run_program(candidate_path, stdin=''), 'hello world', 'tail')


def test_t2(candidate_path):
    # release: Input: None\nExpected Output: hello world
    check_stdout(run_program(candidate_path, stdin=''), 'hello world', 'tail')


def test_t3(candidate_path):
    # release: Input: None\nExpected Output: hello world
    check_stdout(run_program(candidate_path, stdin=''), 'hello world', 'tail')


def test_t4(candidate_path):
    # release: Input: None\nExpected Output: hello world
    check_stdout(run_program(candidate_path, stdin=''), 'hello world', 'tail')


def test_t5(candidate_path):
    # release: Input: None\nExpected Output: hello world
    check_stdout(run_program(candidate_path, stdin=''), 'hello world', 'tail')
