# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/065 | mode: original | kind: function | entry: collatz | comparison: eq
# Well-posed: yes
# Prompt: #The Collatz Conjecture is a famous sequence in mathematics\n#proposed by Lothar Collatz. It proceeds as follows:\n#\n#Start with any number. If ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/065', 'kind': 'function', 'entry': 'collatz'}
ENV = None


def test_t1(m):
    # release: Input: 5\nOutput: 5
    check(call(m, TASK, (5,), {}), 5, 'eq')


def test_t2(m):
    # release: Input: 10\nOutput: 6
    check(call(m, TASK, (10,), {}), 6, 'eq')


def test_t3(m):
    # release: Input: 1\nOutput: 0
    check(call(m, TASK, (1,), {}), 0, 'eq')


def test_t4(m):
    # release: Input: 6\nOutput: 8
    check(call(m, TASK, (6,), {}), 8, 'eq')


def test_t5(m):
    # release: Input: 11\nOutput: 14
    check(call(m, TASK, (11,), {}), 14, 'eq')
