# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/029 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- time_dependent: the output depends on today's date; release wording uses 'and' although the prompt says 'without any and'
# Note: Today's date fixed to 2023-07-31, the date implied by release test 3.
# Prompt: Assuming there are 365 days in a year, there are 525600 minutes in that same year (because there are 24 hours in a day and 60 minutes in an hour). ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/029', 'kind': 'program', 'entry': None}
ENV = {'CSE_TODAY': '2023-07-31'}


def test_t1(candidate_path):
    # release: Input: 2000-01-01\nExpected Output: Twenty three million, seven hundred and forty five thousand, six ...
    check_stdout(run_program(candidate_path, stdin='2000-01-01\n', env={'CSE_TODAY': '2023-07-31'}), 'Twenty three million, seven hundred and forty five thousand, six hundred and forty minutes', 'tail')


def test_t2(candidate_path):
    # release: Input: 1990-07-15\nExpected Output: Seventeen million, two hundred and twenty eight thousand, eight ...
    check_stdout(run_program(candidate_path, stdin='1990-07-15\n', env={'CSE_TODAY': '2023-07-31'}), 'Seventeen million, two hundred and twenty eight thousand, eight hundred and eighty minutes', 'tail')


def test_t3(candidate_path):
    # release: Input: 2023-07-31\nExpected Output: Zero minutes
    check_stdout(run_program(candidate_path, stdin='2023-07-31\n', env={'CSE_TODAY': '2023-07-31'}), 'Zero minutes', 'tail')


def test_t4(candidate_path):
    # release: Input: 1985-12-25\nExpected Output: Nineteen million, seven hundred and seventy eight thousand, four ...
    check_stdout(run_program(candidate_path, stdin='1985-12-25\n', env={'CSE_TODAY': '2023-07-31'}), 'Nineteen million, seven hundred and seventy eight thousand, four hundred and forty minutes', 'tail')


def test_t5(candidate_path):
    # release: Input: 1970-01-01\nExpected Output: Twenty eight million, one hundred and five thousand, six hundred ...
    check_stdout(run_program(candidate_path, stdin='1970-01-01\n', env={'CSE_TODAY': '2023-07-31'}), 'Twenty eight million, one hundred and five thousand, six hundred and forty minutes', 'tail')
