# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/034 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/034', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 0.85\nOutput: B
    check_stdout(run_program(candidate_path, stdin='0.85\n'), 'B', 'tail')


def test_t2(candidate_path):
    # release: Input: 0.95\nOutput: A
    check_stdout(run_program(candidate_path, stdin='0.95\n'), 'A', 'tail')


def test_t3(candidate_path):
    # release: Input: 0.75\nOutput: C
    check_stdout(run_program(candidate_path, stdin='0.75\n'), 'C', 'tail')


def test_t4(candidate_path):
    # release: Input: 1.2\nOutput: Error: Score out of range. Please enter a value between 0.0 and 1.0
    check_stdout(run_program(candidate_path, stdin='1.2\n'), 'Error: Score out of range. Please enter a value between 0.0 and 1.0', 'tail')


def test_t5(candidate_path):
    # release: Input: -0.5\nOutput: Error: Score out of range. Please enter a value between 0.0 and 1.0
    check_stdout(run_program(candidate_path, stdin='-0.5\n'), 'Error: Score out of range. Please enter a value between 0.0 and 1.0', 'tail')
