# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/070 | mode: original | kind: function | entry: names_to_apa | comparison: eq
# Well-posed: yes
# Prompt: #APA citation style cites author names like this:\n#\n# Last, F., Joyner, D., Burdell, G.\n#\n#Note the following:\n#\n# - Each individual name is ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/070', 'kind': 'function', 'entry': 'names_to_apa'}
ENV = None


def test_t1(m):
    # release: Input:\n"John Doe, Jane Smith, and Sarah Brown"\nOutput:\n"Doe, J., Smith, J., Brown, S."
    check(call(m, TASK, ('John Doe, Jane Smith, and Sarah Brown',), {}), 'Doe, J., Smith, J., Brown, S.', 'eq')


def test_t2(m):
    # release: Input:\n"Tom Hanks, Jerry Seinfeld, and Julia Louis"\nOutput:\n"Hanks, T., Seinfeld, J., Louis, J."
    check(call(m, TASK, ('Tom Hanks, Jerry Seinfeld, and Julia Louis',), {}), 'Hanks, T., Seinfeld, J., Louis, J.', 'eq')


def test_t3(m):
    # release: Input:\n"Barack Obama, George Bush, and Bill Clinton"\nOutput:\n"Obama, B., Bush, G., Clinton, B."
    check(call(m, TASK, ('Barack Obama, George Bush, and Bill Clinton',), {}), 'Obama, B., Bush, G., Clinton, B.', 'eq')


def test_t4(m):
    # release: Input:\n"Elon Musk, Jeff Bezos, and Mark Zuckerberg"\nOutput:\n"Musk, E., Bezos, J., Zuckerberg, M."
    check(call(m, TASK, ('Elon Musk, Jeff Bezos, and Mark Zuckerberg',), {}), 'Musk, E., Bezos, J., Zuckerberg, M.', 'eq')


def test_t5(m):
    # release: Input:\n"Albert Einstein, Isaac Newton, and Galileo Galilei"\nOutput:\n"Einstein, A., Newton, I., ...
    check(call(m, TASK, ('Albert Einstein, Isaac Newton, and Galileo Galilei',), {}), 'Einstein, A., Newton, I., Galilei, G.', 'eq')
