# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/036 | mode: original | kind: program | entry: None | comparison: nums
# Well-posed: yes
# Prompt: Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/036', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 5, 8, 3, 1, 6, done\nOutput: Largest number: 8, Smallest number: 1
    check_stdout(run_program(candidate_path, stdin='5\n8\n3\n1\n6\ndone\n'), 'Largest number: 8, Smallest number: 1', 'nums')


def test_t2(candidate_path):
    # release: Input: 10, 12, 15, done\nOutput: Largest number: 15, Smallest number: 10
    check_stdout(run_program(candidate_path, stdin='10\n12\n15\ndone\n'), 'Largest number: 15, Smallest number: 10', 'nums')


def test_t3(candidate_path):
    # release: Input: 20, 30, 40, 50, 60, done\nOutput: Largest number: 60, Smallest number: 20
    check_stdout(run_program(candidate_path, stdin='20\n30\n40\n50\n60\ndone\n'), 'Largest number: 60, Smallest number: 20', 'nums')


def test_t4(candidate_path):
    # release: Input: 100, 200, 300, 400, 500, done\nOutput: Largest number: 500, Smallest number: 100
    check_stdout(run_program(candidate_path, stdin='100\n200\n300\n400\n500\ndone\n'), 'Largest number: 500, Smallest number: 100', 'nums')


def test_t5(candidate_path):
    # release: Input: done\nOutput: No numbers entered.
    check_stdout(run_program(candidate_path, stdin='done\n'), 'No numbers entered.', 'tail')
