# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/044 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: amount = 17\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change these lines to\n#assign ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/044', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: amount = 88\nOutput:\nFifties: 1\nTwenties: 1\nTens: 1\nFives: 1\nOnes: 3
    check_stdout(run_program(candidate_path, assignments={'amount': '88'}), 'Fifties: 1\nTwenties: 1\nTens: 1\nFives: 1\nOnes: 3', 'tail')


def test_t2(candidate_path):
    # release: Input: amount = 121\nOutput:\nFifties: 2\nTwenties: 1\nTens: 0\nFives: 0\nOnes: 1
    check_stdout(run_program(candidate_path, assignments={'amount': '121'}), 'Fifties: 2\nTwenties: 1\nTens: 0\nFives: 0\nOnes: 1', 'tail')


def test_t3(candidate_path):
    # release: Input: amount = 53\nOutput:\nFifties: 1\nTwenties: 0\nTens: 0\nFives: 0\nOnes: 3
    check_stdout(run_program(candidate_path, assignments={'amount': '53'}), 'Fifties: 1\nTwenties: 0\nTens: 0\nFives: 0\nOnes: 3', 'tail')


def test_t4(candidate_path):
    # release: Input: amount = 3\nOutput:\nFifties: 0\nTwenties: 0\nTens: 0\nFives: 0\nOnes: 3
    check_stdout(run_program(candidate_path, assignments={'amount': '3'}), 'Fifties: 0\nTwenties: 0\nTens: 0\nFives: 0\nOnes: 3', 'tail')


def test_t5(candidate_path):
    # release: Input: amount = 0\nOutput:\nFifties: 0\nTwenties: 0\nTens: 0\nFives: 0\nOnes: 0
    check_stdout(run_program(candidate_path, assignments={'amount': '0'}), 'Fifties: 0\nTwenties: 0\nTens: 0\nFives: 0\nOnes: 0', 'tail')
