# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/001 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: implement a program that prompts the user for the answer to the Great Question of Life, the Universe and Everything, outputting Yes if the user ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/001', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 42\nOutput: Yes
    check_stdout(run_program(candidate_path, stdin='42\n'), 'Yes', 'tail')


def test_t2(candidate_path):
    # release: Input: Forty-Two\nOutput: Yes
    check_stdout(run_program(candidate_path, stdin='Forty-Two\n'), 'Yes', 'tail')


def test_t3(candidate_path):
    # release: Input: forty two\nOutput: Yes
    check_stdout(run_program(candidate_path, stdin='forty two\n'), 'Yes', 'tail')


def test_t4(candidate_path):
    # release: Input: 50\nOutput: No
    check_stdout(run_program(candidate_path, stdin='50\n'), 'No', 'tail')


def test_t5(candidate_path):
    # release: Input: FourTY TwO\nOutput: Yes
    check_stdout(run_program(candidate_path, stdin='FourTY TwO\n'), 'Yes', 'tail')
