# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/010 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: NO -- missing_context: the prompt refers to data or a desired output that it does not include (the FDA poster's calorie values)
# Prompt: The U.S. Food & Drug Adminstration (FDA) offers downloadable/printable posters that “show nutrition information for the 20 most frequently ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/010', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "Apple"\nExpected Output: "130 calories"
    check_stdout(run_program(candidate_path, stdin='Apple\n'), '130', 'num')


def test_t2(candidate_path):
    # release: Input: "Banana"\nExpected Output: "110 calories"
    check_stdout(run_program(candidate_path, stdin='Banana\n'), '110', 'num')


def test_t3(candidate_path):
    # release: Input: "Strawberries"\nExpected Output: "50 calories"
    check_stdout(run_program(candidate_path, stdin='Strawberries\n'), '50', 'num')


def test_t4(candidate_path):
    # release: Input: "Pineapple"\nExpected Output: "50 calories"
    check_stdout(run_program(candidate_path, stdin='Pineapple\n'), '50', 'num')


def test_t5(candidate_path):
    # release: Input: "Grapes"\nExpected Output: "90 calories"
    check_stdout(run_program(candidate_path, stdin='Grapes\n'), '90', 'num')
