# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/078 | mode: original | kind: function | entry: pivot_library | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called pivot_library. pivot_library takes\n#as input one parameter, a list of 3-tuples. Each tuple in\n#the list has three ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/078', 'kind': 'function', 'entry': 'pivot_library'}
ENV = None


def test_t1(m):
    # release: Input:\n[("Of Mice and Men", "John Steinbeck", "978-0-140-17739-8")]\nOutput:\n{"978-0-140-17739-8": ...
    check(call(m, TASK, ([('Of Mice and Men', 'John Steinbeck', '978-0-140-17739-8')],), {}), {'978-0-140-17739-8': {'title': 'Of Mice and Men', 'author': 'John Steinbeck'}}, 'eq')


def test_t2(m):
    # release: Input:\n[("Introduction to Computing", "David Joyner", ...
    check(call(m, TASK, ([('Introduction to Computing', 'David Joyner', '978-1-260-08227-2')],), {}), {'978-1-260-08227-2': {'title': 'Introduction to Computing', 'author': 'David Joyner'}}, 'eq')


def test_t3(m):
    # release: Input:\n[("Harry Potter and the Philosopher's Stone", "J.K. Rowling", "978-0-7475-3269-6"),\n("The ...
    check(call(m, TASK, ([("Harry Potter and the Philosopher's Stone", 'J.K. Rowling', '978-0-7475-3269-6'), ('The Great Gatsby', 'F. Scott Fitzgerald', '978-0-7432-7356-5')],), {}), {'978-0-7475-3269-6': {'title': "Harry Potter and the Philosopher's Stone", 'author': 'J.K. Rowling'}, '978-0-7432-7356-5': {'title': 'The Great Gatsby', 'author': 'F. Scott Fitzgerald'}}, 'eq')


def test_t4(m):
    # release: Input:\n[("To Kill a Mockingbird", "Harper Lee", "978-0-06-112008-4"),\n("1984", "George Orwell", ...
    check(call(m, TASK, ([('To Kill a Mockingbird', 'Harper Lee', '978-0-06-112008-4'), ('1984', 'George Orwell', '978-0-452-28423-4')],), {}), {'978-0-006-112008-4': {'title': 'To Kill a Mockingbird', 'author': 'Harper Lee'}, '978-0-452-28423-4': {'title': '1984', 'author': 'George Orwell'}}, 'eq')


def test_t5(m):
    # release: Input:\n[("The Lord of the Rings", "J.R.R. Tolkien", "978-0-618-57472-6"),\n("Pride and Prejudice", ...
    check(call(m, TASK, ([('The Lord of the Rings', 'J.R.R. Tolkien', '978-0-618-57472-6'), ('Pride and Prejudice', 'Jane Austen', '978-0-14-143951-8')],), {}), {'978-0-618-57472-6': {'title': 'The Lord of the Rings', 'author': 'J.R.R. Tolkien'}, '978-0-014-143951-8': {'title': 'Pride and Prejudice', 'author': 'Jane Austen'}}, 'eq')
