# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/072 | mode: original | kind: function | entry: check_winner | comparison: eq
# Well-posed: yes
# Prompt: #In the game tic-tac-toe, two players take turns drawing\n#Xs and Os on a 3x3 grid. If one player can place three of\n#their symbols side-by-side ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/072', 'kind': 'function', 'entry': 'check_winner'}
ENV = None


def test_t1(m):
    # release: Input:\n(("X", "O", "X"),\n("O", "O", "X"),\n("O", "X", "X"))\nOutput:\n"X"
    check(call(m, TASK, ((('X', 'O', 'X'), ('O', 'O', 'X'), ('O', 'X', 'X')),), {}), 'X', 'eq')


def test_t2(m):
    # release: Input:\n(("O", "X", "X"),\n("X", "O", "None"),\n("None", "None", "O"))\nOutput:\n"X"
    check(call(m, TASK, ((('O', 'X', 'X'), ('X', 'O', 'None'), ('None', 'None', 'O')),), {}), 'X', 'eq')


def test_t3(m):
    # release: Input:\n(("O", "O", "None"),\n("X", "X", "X"),\n("None", "None", "None"))\nOutput:\n"X"
    check(call(m, TASK, ((('O', 'O', 'None'), ('X', 'X', 'X'), ('None', 'None', 'None')),), {}), 'X', 'eq')


def test_t4(m):
    # release: Input:\n(("X", "O", "O"),\n("O", "X", "X"),\n("X", "X", "O"))\nOutput:\nNone
    check(call(m, TASK, ((('X', 'O', 'O'), ('O', 'X', 'X'), ('X', 'X', 'O')),), {}), None, 'eq')


def test_t5(m):
    # release: Input:\n(("X", "X", "X"),\n("O", "O", "None"),\n("None", "None", "None"))\nOutput:\n"X"
    check(call(m, TASK, ((('X', 'X', 'X'), ('O', 'O', 'None'), ('None', 'None', 'None')),), {}), 'X', 'eq')
