# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/017 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- nondeterministic: the output depends on random numbers the tests cannot know
# Note: Random target fixed to the guess that the release marks 'Just right!'.
# Prompt: I’m thinking of a number between 1 and 100…\n\nWhat is it?\nIn a file called game.py, implement a program that:\n\nPrompts the user for a level, ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/017', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nLevel: 10\nGuesses: 5, 7, 10\nExpected Output:\n"Too small!", "Too small!", "Just right!"
    check_stdout(run_program(candidate_path, stdin='10\n5\n7\n10\n', env={'CSE_RANDOM_SEQ': '[10]'}), 'Too small!\nToo small!\nJust right!', 'tail')


def test_t2(candidate_path):
    # release: Input:\nLevel: 20\nGuesses: 25, 15, 20\nExpected Output:\n"Invalid guess!", "Too small!", "Just right!"
    check_stdout(run_program(candidate_path, stdin='20\n25\n15\n20\n', env={'CSE_RANDOM_SEQ': '[20]'}), 'Invalid guess!\nToo small!\nJust right!', 'tail')


def test_t3(candidate_path):
    # release: Input:\nLevel: 50\nGuesses: 60, 45, 50\nExpected Output:\n"Too large!", "Too small!", "Just right!"
    check_stdout(run_program(candidate_path, stdin='50\n60\n45\n50\n', env={'CSE_RANDOM_SEQ': '[50]'}), 'Too large!\nToo small!\nJust right!', 'tail')


def test_t4(candidate_path):
    # release: Input:\nLevel: 100\nGuesses: 150, 90, 100\nExpected Output:\n"Invalid guess!", "Too small!", "Just ...
    check_stdout(run_program(candidate_path, stdin='100\n150\n90\n100\n', env={'CSE_RANDOM_SEQ': '[100]'}), 'Invalid guess!\nToo small!\nJust right!', 'tail')


def test_t5(candidate_path):
    # release: Input:\nLevel: 30\nGuesses: 35, 25, 30\nExpected Output:\n"Invalid guess!", "Too small!", "Just right!"
    check_stdout(run_program(candidate_path, stdin='30\n35\n25\n30\n', env={'CSE_RANDOM_SEQ': '[30]'}), 'Invalid guess!\nToo small!\nJust right!', 'tail')
