# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/083 | mode: original | kind: function | entry: playlist | comparison: eq
# Well-posed: yes
# Prompt: #Your goal in this question is to create a playlist (that is, a list of songs) by your friend's favorite artists.\n#\n#Write a function called ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/083', 'kind': 'function', 'entry': 'playlist'}
ENV = None


def test_t1(m):
    # release: Input:\nartists_and_songs = {\n"Beyonce": ["Halo", "Run the World", "Irreplaceable"],\n"Maroon 5": ...
    check(call(m, TASK, ({'Beyonce': ['Halo', 'Run the World', 'Irreplaceable'], 'Maroon 5': ['Sugar', 'Payphone', 'Memories'], 'Harry Styles': ['Sign of the Times', 'Adore You', 'Falling'], 'AC/DC': ['TNT', "It's a long way to the top", 'Thunderstruck']}, ['Maroon 5', 'AC/DC', 'Tame Impala']), {}), ["It's a long way to the top", 'Memories', 'Payphone', 'Sugar', 'TNT', 'Thunderstruck'], 'eq')


def test_t2(m):
    # release: Input:\nartists_and_songs = {\n"Taylor Swift": ["Love Story", "Blank Space", "Shake It Off"],\n"Ed ...
    check(call(m, TASK, ({'Taylor Swift': ['Love Story', 'Blank Space', 'Shake It Off'], 'Ed Sheeran': ['Shape of You', 'Thinking Out Loud', 'Photograph'], 'Adele': ['Hello', 'Rolling in the Deep', 'Someone Like You'], 'Imagine Dragons': ['Believer', 'Radioactive', 'Demons']}, ['Ed Sheeran', 'Adele', 'Justin Bieber']), {}), "I guess I don't mind ads on the radio that much", 'eq')


def test_t3(m):
    # release: Input:\nartists_and_songs = {\n"Coldplay": ["Yellow", "Clocks", "Viva la Vida"],\n"U2": ["With or ...
    check(call(m, TASK, ({'Coldplay': ['Yellow', 'Clocks', 'Viva la Vida'], 'U2': ['With or Without You', 'Beautiful Day', 'One'], 'Queen': ['Bohemian Rhapsody', 'Another One Bites the Dust', 'We Will Rock You'], 'The Beatles': ['Hey Jude', 'Let It Be', 'Yesterday']}, ['Coldplay', 'U2', 'The Beatles']), {}), ['Clocks', 'Viva la Vida', 'Yellow', 'Hey Jude', 'Let It Be', 'Yesterday'], 'eq')


def test_t4(m):
    # release: Input:\nartists_and_songs = {\n"Drake": ["Hotline Bling", "God's Plan", "In My ...
    check(call(m, TASK, ({'Drake': ['Hotline Bling', "God's Plan", 'In My Feelings'], 'Kendrick Lamar': ['HUMBLE.', 'DNA.', 'Alright'], 'Post Malone': ['Circles', 'Congratulations', 'Rockstar']}, ['Drake', 'Kendrick Lamar', 'Post Malone']), {}), ['Alright', 'Circles', 'Congratulations', 'DNA.', "God's Plan", 'Hotline Bling', 'HUMBLE.', 'In My Feelings', 'Rockstar'], 'eq')


def test_t5(m):
    # release: Input:\nartists_and_songs = {\n"Michael Jackson": ["Thriller", "Billie Jean", "Beat It"],\n"Prince": ...
    check(call(m, TASK, ({'Michael Jackson': ['Thriller', 'Billie Jean', 'Beat It'], 'Prince': ['Purple Rain', 'When Doves Cry', 'Kiss'], 'Madonna': ['Like a Virgin', 'Material Girl', 'Vogue']}, ['Madonna', 'Britney Spears', 'Justin Timberlake']), {}), "I guess I don't mind ads on the radio that much", 'eq')
