# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/051 | mode: original | kind: function | entry: interpretCashier | comparison: eq
# Well-posed: yes
# Prompt: #Imagine you're writing a cash register application. To make\n#interaction easier on the user, it doesn't have separate\n#areas for passwords, PIN ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/051', 'kind': 'function', 'entry': 'interpretCashier'}
ENV = None


def test_t1(m):
    # release: Input:\n"1234"\nOutput:\n"PIN"
    check(call(m, TASK, ('1234',), {}), 'PIN', 'eq')


def test_t2(m):
    # release: Input:\n"123.45"\nOutput:\n"Transaction"
    check(call(m, TASK, ('123.45',), {}), 'Transaction', 'eq')


def test_t3(m):
    # release: Input:\n"hello123"\nOutput:\n"Password"
    check(call(m, TASK, ('hello123',), {}), 'Password', 'eq')


def test_t4(m):
    # release: Input:\n"23.45.67"\nOutput:\n"Password"
    check(call(m, TASK, ('23.45.67',), {}), 'Password', 'eq')


def test_t5(m):
    # release: Input:\n"0.0"\nOutput:\n"Transaction"
    check(call(m, TASK, ('0.0',), {}), 'Transaction', 'eq')
