# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/095 | mode: original | kind: function | entry: count_squares | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called count_squares. This function\n#should take as input a list of integers, and return as\n#output a single integer. The ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/095', 'kind': 'function', 'entry': 'count_squares'}
ENV = None


def test_t1(m):
    # release: Input: 1, 2, 3, 4, 5, 6, 7, 8, 9\nOutput: 3
    check(call(m, TASK, ([1, 2, 3, 4, 5, 6, 7, 8, 9],), {}), 3, 'eq')


def test_t2(m):
    # release: Input: 1, 4, 9, 16, 25, 36, 49, 64\nOutput: 8
    check(call(m, TASK, ([1, 4, 9, 16, 25, 36, 49, 64],), {}), 8, 'eq')


def test_t3(m):
    # release: Input: 2, 3, 5, 6, 7, 8, 10, 11\nOutput: 0
    check(call(m, TASK, ([2, 3, 5, 6, 7, 8, 10, 11],), {}), 0, 'eq')


def test_t4(m):
    # release: Input: 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100\nOutput: 11
    check(call(m, TASK, ([0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100],), {}), 11, 'eq')


def test_t5(m):
    # release: Input: 1000000000\nOutput: 1
    check(call(m, TASK, ([1000000000],), {}), 1, 'eq')
