# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/056 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: minimum = 5\nmaximum = 10\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change these lines ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/056', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nminimum = 1\nmaximum = 5\nOutput:\n1\n2\n3\n4\n5
    check_stdout(run_program(candidate_path, assignments={'minimum': '1', 'maximum': '5'}), '1\n2\n3\n4\n5', 'tail')


def test_t2(candidate_path):
    # release: Input:\nminimum = 7\nmaximum = 7\nOutput:\n7
    check_stdout(run_program(candidate_path, assignments={'minimum': '7', 'maximum': '7'}), '7', 'tail')


def test_t3(candidate_path):
    # release: Input:\nminimum = -5\nmaximum = 0\nOutput:\n-5\n-4\n-3\n-2\n-1\n0
    check_stdout(run_program(candidate_path, assignments={'minimum': '-5', 'maximum': '0'}), '-5\n-4\n-3\n-2\n-1\n0', 'tail')


def test_t4(candidate_path):
    # release: Input:\nminimum = 0\nmaximum = 3\nOutput:\n0\n1\n2\n3
    check_stdout(run_program(candidate_path, assignments={'minimum': '0', 'maximum': '3'}), '0\n1\n2\n3', 'tail')


def test_t5(candidate_path):
    # release: Input:\nminimum = 10\nmaximum = 12\nOutput:\n10\n11\n12
    check_stdout(run_program(candidate_path, assignments={'minimum': '10', 'maximum': '12'}), '10\n11\n12', 'tail')
