# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/046 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: num = 3\n\n#-----------------------------------------------------------\n#You may modify the lines of code above, but don't move them!\n#When you ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/046', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nnum = 2\nOutput:\n"8888"
    check_stdout(run_program(candidate_path, assignments={'num': '2'}), '8888', 'tail')


def test_t2(candidate_path):
    # release: Input:\nnum = 4\nOutput:\n"6464646464646464646464646464"
    check_stdout(run_program(candidate_path, assignments={'num': '4'}), '6464646464646464646464646464', 'tail')


def test_t3(candidate_path):
    # release: Input:\nnum = 1\nOutput:\n"1"
    check_stdout(run_program(candidate_path, assignments={'num': '1'}), '1', 'tail')


def test_t4(candidate_path):
    # release: Input:\nnum = 5\nOutput:\n"125125125125125125125125125125125125125125125125125"
    check_stdout(run_program(candidate_path, assignments={'num': '5'}), '125125125125125125125125125125125125125125125125125', 'tail')


def test_t5(candidate_path):
    # release: Input:\nnum = ...
    check_stdout(run_program(candidate_path, assignments={'num': '6'}), '216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216216', 'tail')
