# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/023 | mode: original | kind: function | entry: gauge | comparison: eq
# Well-posed: yes
# Note: Each test checks gauge(convert(fraction)).
# Prompt: implement Fuel Gauge from Problem Set 3, restructuring your code per the below, wherein:\n\nconvert expects a str in X/Y format as input, wherein ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/023', 'kind': 'function', 'entry': 'gauge'}
ENV = None


def test_t1(m):
    # release: Input: "1/4"\nExpected Output: "25%"
    check(call(m, TASK, (call(m, TASK, ('1/4',), entry='convert'),)), '25%')


def test_t2(m):
    # release: Input: "1/2"\nExpected Output: "50%"
    check(call(m, TASK, (call(m, TASK, ('1/2',), entry='convert'),)), '50%')


def test_t3(m):
    # release: Input: "3/4"\nExpected Output: "75%"
    check(call(m, TASK, (call(m, TASK, ('3/4',), entry='convert'),)), '75%')


def test_t4(m):
    # release: Input: "1/100"\nExpected Output: "E"
    check(call(m, TASK, (call(m, TASK, ('1/100',), entry='convert'),)), 'E')


def test_t5(m):
    # release: Input: "99/100"\nExpected Output: "F"
    check(call(m, TASK, (call(m, TASK, ('99/100',), entry='convert'),)), 'F')
