# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/048 | mode: original | kind: function | entry: pullString | comparison: eq
# Well-posed: yes
# Prompt: #Imagine you're writing the software that controls the speed\n#of a ceiling fan. The user changes the fan's speed by\n#pulling a string. Pulling ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/048', 'kind': 'function', 'entry': 'pullString'}
ENV = None


def test_t1(m):
    # release: Input:\ncurrentSpeed = 0\nmaxSpeed = 3\nOutput:\n1
    check(call(m, TASK, (0, 3), {}), 1, 'eq')


def test_t2(m):
    # release: Input:\ncurrentSpeed = 3\nmaxSpeed = 3\nOutput:\n0
    check(call(m, TASK, (3, 3), {}), 0, 'eq')


def test_t3(m):
    # release: Input:\ncurrentSpeed = 2\nmaxSpeed = 3\nOutput:\n3
    check(call(m, TASK, (2, 3), {}), 3, 'eq')


def test_t4(m):
    # release: Input:\ncurrentSpeed = 0\nmaxSpeed = 0\nOutput:\n0
    check(call(m, TASK, (0, 0), {}), 0, 'eq')


def test_t5(m):
    # release: Input:\ncurrentSpeed = 5\nmaxSpeed = 10\nOutput:\n6
    check(call(m, TASK, (5, 10), {}), 6, 'eq')
