# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/093 | mode: original | kind: custom | entry: Rectangle | comparison: eq
# Well-posed: yes
# Prompt: #Create a class called Rectangle. Rectangle should\n#have two attributes (instance variables): length and\n#width. Make sure the variable names ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/093', 'kind': 'custom', 'entry': 'Rectangle'}
ENV = None


def test_t1(m):
    # release: Input: Rectangle(5.0, 3.0)\nOutput: 16.0
    r = m.Rectangle(5.0, 3.0)
    check(r.find_perimeter(), 16.0)


def test_t2(m):
    # release: Input: Rectangle(10.5, 7.2)\nOutput: 35.4
    r = m.Rectangle(10.5, 7.2)
    check(r.find_perimeter(), 35.4)


def test_t3(m):
    # release: Input: Rectangle(2.5, 2.5)\nOutput: 10.0
    r = m.Rectangle(2.5, 2.5)
    check(r.find_perimeter(), 10.0)


def test_t4(m):
    # release: Input: Rectangle(8.0, 4.0)\nOutput: 24.0
    r = m.Rectangle(8.0, 4.0)
    check(r.find_perimeter(), 24.0)


def test_t5(m):
    # release: Input: Rectangle(12.3, 4.7)\nOutput: 34.0
    r = m.Rectangle(12.3, 4.7)
    check(r.find_perimeter(), 34.0)
