# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/086 | mode: original | kind: function | entry: count_positive_evens | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called count_positive_evens. This function\n#should take as input a list of integers, and return as\n#output a single integer. ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/086', 'kind': 'function', 'entry': 'count_positive_evens'}
ENV = None


def test_t1(m):
    # release: Input: [5, 7, 9, 8, -1, -2, -3]\nOutput: 1
    check(call(m, TASK, ([5, 7, 9, 8, -1, -2, -3],), {}), 1, 'eq')


def test_t2(m):
    # release: Input: [2, 4, 6, 8, 10, 12, 15]\nOutput: 6
    check(call(m, TASK, ([2, 4, 6, 8, 10, 12, 15],), {}), 6, 'eq')


def test_t3(m):
    # release: Input: [-2, -4, -6, -8, -10, 1]\nOutput: 0
    check(call(m, TASK, ([-2, -4, -6, -8, -10, 1],), {}), 0, 'eq')


def test_t4(m):
    # release: Input: [0, 2, 4, 6, 8, -10, 1, -12]\nOutput: 4
    check(call(m, TASK, ([0, 2, 4, 6, 8, -10, 1, -12],), {}), 4, 'eq')


def test_t5(m):
    # release: Input: [12, -10, 5, 7, 8, 9]\nOutput: 2
    check(call(m, TASK, ([12, -10, 5, 7, 8, 9],), {}), 2, 'eq')
