# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/042 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: principal = 40000\nrate = 0.05\nyears = 5\ngoal = 50000\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/042', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nprincipal = 40000\nrate = 0.05\nyears = 5\ngoal = 50000\nOutput:\nTrue
    check_stdout(run_program(candidate_path, assignments={'principal': '40000', 'rate': '0.05', 'years': '5', 'goal': '50000'}), 'True', 'tail')


def test_t2(candidate_path):
    # release: Input:\nprincipal = 40000\nrate = 0.03\nyears = 10\ngoal = 50000\nOutput:\nFalse
    check_stdout(run_program(candidate_path, assignments={'principal': '40000', 'rate': '0.03', 'years': '10', 'goal': '50000'}), 'False', 'tail')


def test_t3(candidate_path):
    # release: Input:\nprincipal = 10000\nrate = 0.07\nyears = 5\ngoal = 20000\nOutput:\nTrue
    check_stdout(run_program(candidate_path, assignments={'principal': '10000', 'rate': '0.07', 'years': '5', 'goal': '20000'}), 'True', 'tail')


def test_t4(candidate_path):
    # release: Input:\nprincipal = 50000\nrate = 0.05\nyears = 7\ngoal = 70000\nOutput:\nTrue
    check_stdout(run_program(candidate_path, assignments={'principal': '50000', 'rate': '0.05', 'years': '7', 'goal': '70000'}), 'True', 'tail')


def test_t5(candidate_path):
    # release: Input:\nprincipal = 30000\nrate = 0.04\nyears = 5\ngoal = 40000\nOutput:\nFalse
    check_stdout(run_program(candidate_path, assignments={'principal': '30000', 'rate': '0.04', 'years': '5', 'goal': '40000'}), 'False', 'tail')
