# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/013 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: Suppose that you’re in the habit of making a list of items you need from the grocery store.\n\nImplement a program that prompts the user for ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/013', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "Milk", "Eggs", "Bread", "Bread", Control-D\nExpected Output:\n"2 BREAD"\n"1 EGGS"\n"1 MILK"
    check_stdout(run_program(candidate_path, stdin='Milk\nEggs\nBread\nBread\n'), '2 BREAD\n1 EGGS\n1 MILK', 'tail')


def test_t2(candidate_path):
    # release: Input: "Apples", "Bananas", "Cereal", "Bananas", "cereal", Control-D\nExpected Output:\n"1 ...
    check_stdout(run_program(candidate_path, stdin='Apples\nBananas\nCereal\nBananas\ncereal\n'), '1 APPLES\n2 BANANAS\n2 CEREAL', 'tail')


def test_t3(candidate_path):
    # release: Input: "Coffee", "Tea", "Coffee", "coffee", "COFFEE", Control-D\nExpected Output:\n"4 COFFEE"\n"1 TEA"
    check_stdout(run_program(candidate_path, stdin='Coffee\nTea\nCoffee\ncoffee\nCOFFEE\n'), '4 COFFEE\n1 TEA', 'tail')


def test_t4(candidate_path):
    # release: Input: "Potatoes", "Tomatoes", "Potatoes", "potatoes", "POTATOES", "Potatoes", Control-D\nExpected ...
    check_stdout(run_program(candidate_path, stdin='Potatoes\nTomatoes\nPotatoes\npotatoes\nPOTATOES\nPotatoes\n'), '4 POTATOES\n1 TOMATOES', 'tail')


def test_t5(candidate_path):
    # release: Input: "Cheese", "Ham", "Cheese", "Ham", "Cheese", "Ham", "Cheese", "Ham", Control-D\nExpected ...
    check_stdout(run_program(candidate_path, stdin='Cheese\nHam\nCheese\nHam\nCheese\nHam\nCheese\nHam\n'), '4 CHEESE\n4 HAM', 'tail')
