# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/062 | mode: original | kind: function | entry: check_date | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called check_date. check_date should\n#require two positional parameters: a string representing\n#the name of a month, and an ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/062', 'kind': 'function', 'entry': 'check_date'}
ENV = None


def test_t1(m):
    # release: Input:\nmonth = "February", day = 29, is_leap_year = True\nOutput:\nTrue
    check(call(m, TASK, ('February', 29), {'is_leap_year': True}), True, 'eq')


def test_t2(m):
    # release: Input:\nmonth = "February", day = 29, is_leap_year = False\nOutput:\nFalse
    check(call(m, TASK, ('February', 29), {'is_leap_year': False}), False, 'eq')


def test_t3(m):
    # release: Input:\nmonth = "April", day = 30, is_leap_year = False\nOutput:\nTrue
    check(call(m, TASK, ('April', 30), {'is_leap_year': False}), True, 'eq')


def test_t4(m):
    # release: Input:\nmonth = "April", day = 31, is_leap_year = False\nOutput:\nFalse
    check(call(m, TASK, ('April', 31), {'is_leap_year': False}), False, 'eq')


def test_t5(m):
    # release: Input:\nmonth = "September", day = 31, is_leap_year = False\nOutput:\nFalse
    check(call(m, TASK, ('September', 31), {'is_leap_year': False}), False, 'eq')
