# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/098 | mode: original | kind: function | entry: fib_skip | comparison: eq
# Well-posed: yes
# Prompt: #Remember that Fibonacci's sequence is a sequence of numbers\n#where every number is the sum of the previous two numbers.\n#\n#Let's write a ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/098', 'kind': 'function', 'entry': 'fib_skip'}
ENV = None


def test_t1(m):
    # release: Input: 1\nOutput: 1
    check(call(m, TASK, (1,), {}), 1, 'eq')


def test_t2(m):
    # release: Input: 2\nOutput: 1
    check(call(m, TASK, (2,), {}), 1, 'eq')


def test_t3(m):
    # release: Input: 3\nOutput: 1
    check(call(m, TASK, (3,), {}), 1, 'eq')


def test_t4(m):
    # release: Input: 4\nOutput: 3
    check(call(m, TASK, (4,), {}), 3, 'eq')


def test_t5(m):
    # release: Input: 9\nOutput: 13
    check(call(m, TASK, (9,), {}), 13, 'eq')
