# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/008 | mode: original | kind: program | entry: None | comparison: suffix
# Well-posed: yes
# Prompt: When texting or tweeting, it’s not uncommon to shorten words to save time or space, as by omitting vowels, much like Twitter was originally called ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/008', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "Hello, world!"\nExpected Output: "Hll, wrld!"
    check_stdout(run_program(candidate_path, stdin='Hello, world!\n'), 'Hll, wrld!', 'suffix')


def test_t2(candidate_path):
    # release: Input: "OpenAI is the best!"\nExpected Output: "OpnAI s th bst!"
    check_stdout(run_program(candidate_path, stdin='OpenAI is the best!\n'), 'OpnAI s th bst!', 'suffix')


def test_t3(candidate_path):
    # release: Input: "I love to code in Python."\nExpected Output: " lv t cd n Pythn."
    check_stdout(run_program(candidate_path, stdin='I love to code in Python.\n'), ' lv t cd n Pythn.', 'suffix')


def test_t4(candidate_path):
    # release: Input: "A quick brown fox jumps over the lazy dog."\nExpected Output: " qck brwn fx jmps vr th lzy dg."
    check_stdout(run_program(candidate_path, stdin='A quick brown fox jumps over the lazy dog.\n'), ' qck brwn fx jmps vr th lzy dg.', 'suffix')


def test_t5(candidate_path):
    # release: Input: "AEIOU are vowels. aeiou are also vowels."\nExpected Output: "R vwls. r ls vwls."
    check_stdout(run_program(candidate_path, stdin='AEIOU are vowels. aeiou are also vowels.\n'), 'R vwls. r ls vwls.', 'suffix')
