# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/025 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- incomplete_task: the task statement stops before saying what to implement
# Prompt: It turns out that (most) YouTube videos can be embedded in other websites, just like the above. For instance, if you visit ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/025', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: "<iframe src="https://www.youtube.com/embed/xvFZjo5PgG0\"></iframe>"\nExpected Output: ...
    check(call(m, TASK, ('<iframe src="https://www.youtube.com/embed/xvFZjo5PgG0"></iframe>',), {}), 'https://youtu.be/xvFZjo5PgG0', 'eq')


def test_t2(m):
    # release: Input: "<iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ\"></iframe>"\nExpected Output: ...
    check(call(m, TASK, ('<iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ"></iframe>',), {}), 'https://youtu.be/dQw4w9WgXcQ', 'eq')


def test_t3(m):
    # release: Input: "<iframe src="https://www.youtube.com/embed/3tmd-ClpJxA\"></iframe>"\nExpected Output: ...
    check(call(m, TASK, ('<iframe src="https://www.youtube.com/embed/3tmd-ClpJxA"></iframe>',), {}), 'https://youtu.be/3tmd-ClpJxA', 'eq')


def test_t4(m):
    # release: Input: "<iframe src="https://www.youtube.com/embed/ktvTqknDobU\"></iframe>"\nExpected Output: ...
    check(call(m, TASK, ('<iframe src="https://www.youtube.com/embed/ktvTqknDobU"></iframe>',), {}), 'https://youtu.be/ktvTqknDobU', 'eq')


def test_t5(m):
    # release: Input: "<iframe src="https://www.youtube.com/embed/YQHsXMglC9A\"></iframe>"\nExpected Output: ...
    check(call(m, TASK, ('<iframe src="https://www.youtube.com/embed/YQHsXMglC9A"></iframe>',), {}), 'https://youtu.be/YQHsXMglC9A', 'eq')
