# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/037 | mode: original | kind: vars | entry: None | comparison: num
# Well-posed: yes
# Prompt: old_balance = "500.45"\ndeposit = "10"\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/037', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nold_balance = "100.00"\ndeposit = "50"\nOutput:\n"The new balance is: 150.00"
    check_stdout(run_program(candidate_path, assignments={'old_balance': '"100.00"', 'deposit': '"50"'}), '150.00', 'num')


def test_t2(candidate_path):
    # release: Input:\nold_balance = "500.45"\ndeposit = "10"\nOutput:\n"The new balance is: 510.45"
    check_stdout(run_program(candidate_path, assignments={'old_balance': '"500.45"', 'deposit': '"10"'}), '510.45', 'num')


def test_t3(candidate_path):
    # release: Input:\nold_balance = "0.00"\ndeposit = "100"\nOutput:\n"The new balance is: 100.00"
    check_stdout(run_program(candidate_path, assignments={'old_balance': '"0.00"', 'deposit': '"100"'}), '100.00', 'num')


def test_t4(candidate_path):
    # release: Input:\nold_balance = "1234.56"\ndeposit = "200"\nOutput:\n"The new balance is: 1434.56"
    check_stdout(run_program(candidate_path, assignments={'old_balance': '"1234.56"', 'deposit': '"200"'}), '1434.56', 'num')


def test_t5(candidate_path):
    # release: Input:\nold_balance = "1000.99"\ndeposit = "0"\nOutput:\n"The new balance is: 1000.99"
    check_stdout(run_program(candidate_path, assignments={'old_balance': '"1000.99"', 'deposit': '"0"'}), '1000.99', 'num')
