# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/055 | mode: original | kind: vars | entry: None | comparison: num
# Well-posed: yes
# Prompt: driver_speed = 57\nspeed_limit = 55\nschool_zone = True\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/055', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\ndriver_speed = 57\nspeed_limit = 55\nschool_zone = True\nOutput:\n240
    check_stdout(run_program(candidate_path, assignments={'driver_speed': '57', 'speed_limit': '55', 'school_zone': 'True'}), '240', 'num')


def test_t2(candidate_path):
    # release: Input:\ndriver_speed = 57\nspeed_limit = 55\nschool_zone = False\nOutput:\n120
    check_stdout(run_program(candidate_path, assignments={'driver_speed': '57', 'speed_limit': '55', 'school_zone': 'False'}), '120', 'num')


def test_t3(candidate_path):
    # release: Input:\ndriver_speed = 55\nspeed_limit = 55\nschool_zone = True\nOutput:\n0
    check_stdout(run_program(candidate_path, assignments={'driver_speed': '55', 'speed_limit': '55', 'school_zone': 'True'}), '0', 'num')


def test_t4(candidate_path):
    # release: Input:\ndriver_speed = 70\nspeed_limit = 55\nschool_zone = True\nOutput:\n450
    check_stdout(run_program(candidate_path, assignments={'driver_speed': '70', 'speed_limit': '55', 'school_zone': 'True'}), '450', 'num')


def test_t5(candidate_path):
    # release: Input:\ndriver_speed = 70\nspeed_limit = 55\nschool_zone = False\nOutput:\n250
    check_stdout(run_program(candidate_path, assignments={'driver_speed': '70', 'speed_limit': '55', 'school_zone': 'False'}), '250', 'num')
