# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/016 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: In The Sound of Music, there’s a song sung largely in English, So Long, Farewell, with these lyrics, wherein “adieu” means “goodbye” in ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/016', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: John\nOutput: Adieu, adieu, to John
    check_stdout(run_program(candidate_path, stdin='John\n'), 'Adieu, adieu, to John', 'tail')


def test_t2(candidate_path):
    # release: Input: John, Doe\nOutput: Adieu, adieu, to John and Doe
    check_stdout(run_program(candidate_path, stdin='John\nDoe\n'), 'Adieu, adieu, to John and Doe', 'tail')


def test_t3(candidate_path):
    # release: Input: John, Doe, Jane\nOutput: Adieu, adieu, to John, Doe, and Jane
    check_stdout(run_program(candidate_path, stdin='John\nDoe\nJane\n'), 'Adieu, adieu, to John, Doe, and Jane', 'tail')


def test_t4(candidate_path):
    # release: Input: John, Doe, Jane, Smith\nOutput: Adieu, adieu, to John, Doe, Jane, and Smith
    check_stdout(run_program(candidate_path, stdin='John\nDoe\nJane\nSmith\n'), 'Adieu, adieu, to John, Doe, Jane, and Smith', 'tail')


def test_t5(candidate_path):
    # release: Input: John, Doe, Jane, Smith, Alice\nOutput: Adieu, adieu, to John, Doe, Jane, Smith, and Alice
    check_stdout(run_program(candidate_path, stdin='John\nDoe\nJane\nSmith\nAlice\n'), 'Adieu, adieu, to John, Doe, Jane, Smith, and Alice', 'tail')
