# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/045 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: message = "lol"\npunct = "!"\nnum = 3\n\n#You may modify the lines of code above, but don't move them!\n#When you Submit your code, we'll change ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/045', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nmessage = "hi"\npunct = "*"\nnum = 2\nOutput:\n"hihihihi**"
    check_stdout(run_program(candidate_path, assignments={'message': '"hi"', 'punct': '"*"', 'num': '2'}), 'hihihihi**', 'tail')


def test_t2(candidate_path):
    # release: Input:\nmessage = "bye"\npunct = "#"\nnum = 3\nOutput:\n"###byebyebye###byebyebye###byebyebye###"
    check_stdout(run_program(candidate_path, assignments={'message': '"bye"', 'punct': '"#"', 'num': '3'}), '###byebyebye###byebyebye###byebyebye###', 'tail')


def test_t3(candidate_path):
    # release: Input:\nmessage = "run"\npunct = "."\nnum = 1\nOutput:\n".run."
    check_stdout(run_program(candidate_path, assignments={'message': '"run"', 'punct': '"."', 'num': '1'}), '.run.', 'tail')


def test_t4(candidate_path):
    # release: Input:\nmessage = "jump"\npunct = "&"\nnum = ...
    check_stdout(run_program(candidate_path, assignments={'message': '"jump"', 'punct': '"&"', 'num': '4'}), '&&&&jumpjumpjumpjump&&&&jumpjumpjumpjump&&&&jumpjumpjumpjump&&&&jumpjumpjumpjump&&&&', 'tail')


def test_t5(candidate_path):
    # release: Input:\nmessage = "play"\npunct = "%"\nnum = ...
    check_stdout(run_program(candidate_path, assignments={'message': '"play"', 'punct': '"%"', 'num': '5'}), '%%%%%playplayplayplayplay%%%%%playplayplayplayplay%%%%%playplayplayplayplay%%%%%playplayplayplayplay%%%%%playplayplayplayplay%%%%%', 'tail')
