# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/050 | mode: original | kind: function | entry: calculateWeight | comparison: eq
# Well-posed: yes
# Prompt: #An object's weight is defined as its mass times the gravity\n#on the planet where it sits. We tend to assume that the\n#planet is earth and its ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/050', 'kind': 'function', 'entry': 'calculateWeight'}
ENV = None


def test_t1(m):
    # release: Input:\nmass = 10.0\nOutput:\n"A 10.0 kg object weighs 98.07 Newtons on Earth."
    check(call(m, TASK, (10.0,), {}), 'A 10.0 kg object weighs 98.07 Newtons on Earth.', 'eq')


def test_t2(m):
    # release: Input:\nmass = 5.0, planet="Jupiter", gravity=24.79\nOutput:\n"A 5.0 kg object weighs 123.95 Newtons ...
    check(call(m, TASK, (5.0,), {'planet': 'Jupiter', 'gravity': 24.79}), 'A 5.0 kg object weighs 123.95 Newtons on Jupiter.', 'eq')


def test_t3(m):
    # release: Input:\nmass = 50.0, planet="Mars", gravity=3.721\nOutput:\n"A 50.0 kg object weighs 186.05 Newtons ...
    check(call(m, TASK, (50.0,), {'planet': 'Mars', 'gravity': 3.721}), 'A 50.0 kg object weighs 186.05 Newtons on Mars.', 'eq')


def test_t4(m):
    # release: Input:\nmass = 100.0, planet="Venus", gravity=8.87\nOutput:\n"A 100.0 kg object weighs 887.0 Newtons ...
    check(call(m, TASK, (100.0,), {'planet': 'Venus', 'gravity': 8.87}), 'A 100.0 kg object weighs 887.0 Newtons on Venus.', 'eq')


def test_t5(m):
    # release: Input:\nmass = 7.5, planet="Moon", gravity=1.622\nOutput:\n"A 7.5 kg object weighs 12.17 Newtons on ...
    check(call(m, TASK, (7.5,), {'planet': 'Moon', 'gravity': 1.622}), 'A 7.5 kg object weighs 12.17 Newtons on Moon.', 'eq')
