# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/027 | mode: original | kind: function | entry: count | comparison: eq
# Well-posed: yes
# Prompt: It’s not uncommon, in English, at least, to say “um” when trying to, um, think of a word. The more you do it, though, the more noticeable it tends ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/027', 'kind': 'function', 'entry': 'count'}
ENV = None


def test_t1(m):
    # release: Input: "hello, um, world"\nExpected Output: 1
    check(call(m, TASK, ('hello, um, world',), {}), 1, 'eq')


def test_t2(m):
    # release: Input: "yummy"\nExpected Output: 0
    check(call(m, TASK, ('yummy',), {}), 0, 'eq')


def test_t3(m):
    # release: Input: "Um, I think, um, I need to, um, think about it."\nExpected Output: 3
    check(call(m, TASK, ('Um, I think, um, I need to, um, think about it.',), {}), 3, 'eq')


def test_t4(m):
    # release: Input: "UM is the abbreviation for University of Michigan."\nExpected Output: 1
    check(call(m, TASK, ('UM is the abbreviation for University of Michigan.',), {}), 1, 'eq')


def test_t5(m):
    # release: Input: "I am unsure about the outcome."\nExpected Output: 0
    check(call(m, TASK, ('I am unsure about the outcome.',), {}), 0, 'eq')
