# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/063 | mode: original | kind: function | entry: get_capitals | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called get_capitals. get_capitals should\n#accept one parameter, a string. It should return a string\n#containing only the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/063', 'kind': 'function', 'entry': 'get_capitals'}
ENV = None


def test_t1(m):
    # release: Input:\n"HelloWorld"\nOutput:\n"HW"
    check(call(m, TASK, ('HelloWorld',), {}), 'HW', 'eq')


def test_t2(m):
    # release: Input:\n"Python"\nOutput:\n"P"
    check(call(m, TASK, ('Python',), {}), 'P', 'eq')


def test_t3(m):
    # release: Input:\n"JAVA"\nOutput:\n"JAVA"
    check(call(m, TASK, ('JAVA',), {}), 'JAVA', 'eq')


def test_t4(m):
    # release: Input:\n"languagemodel"\nOutput:\n""
    check(call(m, TASK, ('languagemodel',), {}), '', 'eq')


def test_t5(m):
    # release: Input:\n"OpenAI"\nOutput:\n"OAI"
    check(call(m, TASK, ('OpenAI',), {}), 'OAI', 'eq')
