# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/097 | mode: original | kind: function | entry: check_uno_winner | comparison: eq
# Well-posed: yes
# Prompt: #The game Uno is a card game where each player's goal is\n#to get rid of all their cards. A round ends when one player\n#has gotten rid of all ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/097', 'kind': 'function', 'entry': 'check_uno_winner'}
ENV = None


def test_t1(m):
    # release: Input: (0, 0)\nOutput: "Keep playing!"
    check(call(m, TASK, ((0, 0),), {}), 'Keep playing!', 'eq')


def test_t2(m):
    # release: Input: (505, 250)\nOutput: "Player 1 wins!"
    check(call(m, TASK, ((505, 250),), {}), 'Player 1 wins!', 'eq')


def test_t3(m):
    # release: Input: (250, 505)\nOutput: "Player 2 wins!"
    check(call(m, TASK, ((250, 505),), {}), 'Player 2 wins!', 'eq')


def test_t4(m):
    # release: Input: (25, 101, 362, 415)\nOutput: "Keep playing!"
    check(call(m, TASK, ((25, 101, 362, 415),), {}), 'Keep playing!', 'eq')


def test_t5(m):
    # release: Input: (25, 101, 426, 515)\nOutput: "Player 4 wins!"
    check(call(m, TASK, ((25, 101, 426, 515),), {}), 'Player 4 wins!', 'eq')
