# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/059 | mode: original | kind: function | entry: find_weight | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called find_weight. find_weight should\n#take one positional parameter, a float that represents\n#the mass of an object in ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/059', 'kind': 'function', 'entry': 'find_weight'}
ENV = None


def test_t1(m):
    # release: Input:\nfind_weight(10.0)\nOutput:\n98.1
    check(call(m, TASK, (10.0,), {}), 98.1, 'eq')


def test_t2(m):
    # release: Input:\nfind_weight(0.0)\nOutput:\n0.0
    check(call(m, TASK, (0.0,), {}), 0.0, 'eq')


def test_t3(m):
    # release: Input:\nfind_weight(5.5, gravity=24.79) # Jupiter's gravity\nOutput:\n136.345
    check(call(m, TASK, (5.5,), {'gravity': 24.79}), 136.345, 'eq')


def test_t4(m):
    # release: Input:\nfind_weight(100.0, gravity=3.7) # Mars's gravity\nOutput:\n370.0
    check(call(m, TASK, (100.0,), {'gravity': 3.7}), 370.0, 'eq')


def test_t5(m):
    # release: Input:\nfind_weight(76.2, gravity=1.622) # Moon's gravity\nOutput:\n123.6924
    check(call(m, TASK, (76.2,), {'gravity': 1.622}), 123.6924, 'eq')
