# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/035 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: yes
# Prompt: Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/035', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: Hours = 45, Rate per Hour = 10.50\nOutput: Gross Pay = 498.75
    check_stdout(run_program(candidate_path, stdin='45\n10.50\n'), '498.75', 'num')


def test_t2(candidate_path):
    # release: Input: Hours = 40, Rate per Hour = 8.75\nOutput: Gross Pay = 350.0
    check_stdout(run_program(candidate_path, stdin='40\n8.75\n'), '350.0', 'num')


def test_t3(candidate_path):
    # release: Input: Hours = 50, Rate per Hour = 12.0\nOutput: Gross Pay = 630.0
    check_stdout(run_program(candidate_path, stdin='50\n12.0\n'), '630.0', 'num')


def test_t4(candidate_path):
    # release: Input: Hours = 38, Rate per Hour = 9.25\nOutput: Gross Pay = 350.5
    check_stdout(run_program(candidate_path, stdin='38\n9.25\n'), '350.5', 'num')


def test_t5(candidate_path):
    # release: Input: Hours = 55, Rate per Hour = 11.50\nOutput: Gross Pay = 632.5
    check_stdout(run_program(candidate_path, stdin='55\n11.50\n'), '632.5', 'num')
