# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/071 | mode: original | kind: function | entry: check_formula | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called check_formula. The check_formula\n#function should take as input one parameter, a string. It\n#should return True if the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/071', 'kind': 'function', 'entry': 'check_formula'}
ENV = None


def test_t1(m):
    # release: Input:\n"5*3=5+2"\nOutput:\nTrue
    check(call(m, TASK, ('5*3=5+2',), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n"5*3+5+2"\nOutput:\nFalse
    check(call(m, TASK, ('5*3+5+2',), {}), False, 'eq')


def test_t3(m):
    # release: Input:\n"5=7"\nOutput:\nTrue
    check(call(m, TASK, ('5=7',), {}), True, 'eq')


def test_t4(m):
    # release: Input:\n"5="\nOutput:\nFalse
    check(call(m, TASK, ('5=',), {}), False, 'eq')


def test_t5(m):
    # release: Input:\n"5=2-5"\nOutput:\nTrue
    check(call(m, TASK, ('5=2-5',), {}), True, 'eq')
