# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/088 | mode: original | kind: function | entry: is_palindrome | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called is_palindrome. The function should\n#have one parameter, a string. The function should return\n#True if the string is a ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/088', 'kind': 'function', 'entry': 'is_palindrome'}
ENV = None


def test_t1(m):
    # release: Input:\n"racecar"\nOutput:\nTrue
    check(call(m, TASK, ('racecar',), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n"Madam in Eden, I'm Adam"\nOutput:\nTrue
    check(call(m, TASK, ("Madam in Eden, I'm Adam",), {}), True, 'eq')


def test_t3(m):
    # release: Input:\n"Able was I ere I saw Elba"\nOutput:\nTrue
    check(call(m, TASK, ('Able was I ere I saw Elba',), {}), True, 'eq')


def test_t4(m):
    # release: Input:\n"hello"\nOutput:\nFalse
    check(call(m, TASK, ('hello',), {}), False, 'eq')


def test_t5(m):
    # release: Input:\n"Was it a car or a cat I saw?"\nOutput:\nTrue
    check(call(m, TASK, ('Was it a car or a cat I saw?',), {}), True, 'eq')
