# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/058 | mode: original | kind: function | entry: find_weight | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called find_weight. find_weight should\n#take one parameter, a float that represents the mass of\n#an object in kilograms. It ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/058', 'kind': 'function', 'entry': 'find_weight'}
ENV = None


def test_t1(m):
    # release: Input:\nfind_weight(10.0)\nOutput:\n98.1
    check(call(m, TASK, (10.0,), {}), 98.1, 'eq')


def test_t2(m):
    # release: Input:\nfind_weight(0.0)\nOutput:\n0.0
    check(call(m, TASK, (0.0,), {}), 0.0, 'eq')


def test_t3(m):
    # release: Input:\nfind_weight(5.5)\nOutput:\n53.955
    check(call(m, TASK, (5.5,), {}), 53.955, 'eq')


def test_t4(m):
    # release: Input:\nfind_weight(100.0)\nOutput:\n981.0
    check(call(m, TASK, (100.0,), {}), 981.0, 'eq')


def test_t5(m):
    # release: Input:\nfind_weight(76.2)\nOutput:\n747.662
    check(call(m, TASK, (76.2,), {}), 747.662, 'eq')
