# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/031 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- missing_context: the prompt refers to data or a desired output that it does not include (the 'desired output' is not shown)
# Prompt: Write a program that uses input to prompt a user for their name and then welcomes them. Note that input will pop up a dialog box. Enter Sarah in ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/031', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "John"\nExpected Output: "Hello, John"
    check_stdout(run_program(candidate_path, stdin='John\n'), 'Hello, John', 'tail')


def test_t2(candidate_path):
    # release: Input: "Alice"\nExpected Output: "Hello, Alice"
    check_stdout(run_program(candidate_path, stdin='Alice\n'), 'Hello, Alice', 'tail')


def test_t3(candidate_path):
    # release: Input: "Bob"\nExpected Output: "Hello, Bob"
    check_stdout(run_program(candidate_path, stdin='Bob\n'), 'Hello, Bob', 'tail')


def test_t4(candidate_path):
    # release: Input: "Charlie"\nExpected Output: "Hello, Charlie"
    check_stdout(run_program(candidate_path, stdin='Charlie\n'), 'Hello, Charlie', 'tail')


def test_t5(candidate_path):
    # release: Input: "David"\nExpected Output: "Hello, David"
    check_stdout(run_program(candidate_path, stdin='David\n'), 'Hello, David', 'tail')
