# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/053 | mode: original | kind: function | entry: sortString | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called sortString. sortString should take\n#one parameter as input, a string. If the input is not a\n#string, sortString should ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/053', 'kind': 'function', 'entry': 'sortString'}
ENV = None


def test_t1(m):
    # release: Input:\n"Hello, world!!1"\nOutput:\n"H\nelloworld\n,!!1\n1"
    check(call(m, TASK, ('Hello, world!!1',), {}), 'H\nelloworld\n,!!1\n1', 'eq')


def test_t2(m):
    # release: Input:\n"Good Morning, John!"\nOutput:\n"GMJ\noodorningohn\n,!\n2"
    check(call(m, TASK, ('Good Morning, John!',), {}), 'GMJ\noodorningohn\n,!\n2', 'eq')


def test_t3(m):
    # release: Input:\n"Bye Bye, Baby!"\nOutput:\n"BBB\nyebyeaby\n,!\n3"
    check(call(m, TASK, ('Bye Bye, Baby!',), {}), 'BBB\nyebyeaby\n,!\n3', 'eq')


def test_t4(m):
    # release: Input:\n"I Love Python Programming!"\nOutput:\n"ILPP\noveythonrogramming\n!\n4"
    check(call(m, TASK, ('I Love Python Programming!',), {}), 'ILPP\noveythonrogramming\n!\n4', 'eq')


def test_t5(m):
    # release: Input:\n12345\nOutput:\n"Not a string!"
    check(call(m, TASK, (12345,), {}), 'Not a string!', 'eq')
