# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/011 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: Fuel gauges indicate, often with fractions, just how much fuel is in a tank. For instance 1/4 indicates that a tank is 25% full, 1/2 indicates ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/011', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: "1/4"\nExpected Output: "25%"
    check_stdout(run_program(candidate_path, stdin='1/4\n'), '25%', 'tail')


def test_t2(candidate_path):
    # release: Input: "1/2"\nExpected Output: "50%"
    check_stdout(run_program(candidate_path, stdin='1/2\n'), '50%', 'tail')


def test_t3(candidate_path):
    # release: Input: "3/4"\nExpected Output: "75%"
    check_stdout(run_program(candidate_path, stdin='3/4\n'), '75%', 'tail')


def test_t4(candidate_path):
    # release: Input: "1/100"\nExpected Output: "E"
    check_stdout(run_program(candidate_path, stdin='1/100\n'), 'E', 'tail')


def test_t5(candidate_path):
    # release: Input: "99/100"\nExpected Output: "F"
    check_stdout(run_program(candidate_path, stdin='99/100\n'), 'F', 'tail')
