# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/006 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: In some languages, it’s common to use camel case (otherwise known as “mixed case”) for variables’ names when those names comprise multiple words, ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/006', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: name\nExpected Output: name
    check_stdout(run_program(candidate_path, stdin='name\n'), 'name', 'tail')


def test_t2(candidate_path):
    # release: Input: firstName\nExpected Output: first_name
    check_stdout(run_program(candidate_path, stdin='firstName\n'), 'first_name', 'tail')


def test_t3(candidate_path):
    # release: Input: preferredFirstName\nExpected Output: preferred_first_name
    check_stdout(run_program(candidate_path, stdin='preferredFirstName\n'), 'preferred_first_name', 'tail')


def test_t4(candidate_path):
    # release: Input: someVariableName\nExpected Output: some_variable_name
    check_stdout(run_program(candidate_path, stdin='someVariableName\n'), 'some_variable_name', 'tail')


def test_t5(candidate_path):
    # release: Input: myCamelCaseString\nExpected Output: my_camel_case_string
    check_stdout(run_program(candidate_path, stdin='myCamelCaseString\n'), 'my_camel_case_string', 'tail')
