# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/040 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: yes
# Prompt: import datetime\nstart_date = datetime.date(2017, 2, 16)\nend_date = datetime.date(2017, 2, 16)\nstart_time = datetime.time(4, 30, 0)\nend_time = ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/040', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nstart_date = datetime.date(2017, 2, 16)\nend_date = datetime.date(2017, 2, 16)\nstart_time = ...
    check_stdout(run_program(candidate_path, assignments={'start_date': 'datetime.date(2017, 2, 16)', 'end_date': 'datetime.date(2017, 2, 16)', 'start_time': 'datetime.time(4, 30, 0)', 'end_time': 'datetime.time(4, 30, 17)'}), 'True', 'tail')


def test_t2(candidate_path):
    # release: Input:\nstart_date = datetime.date(2023, 1, 1)\nend_date = datetime.date(2023, 1, 2)\nstart_time = ...
    check_stdout(run_program(candidate_path, assignments={'start_date': 'datetime.date(2023, 1, 1)', 'end_date': 'datetime.date(2023, 1, 2)', 'start_time': 'datetime.time(22, 30, 0)', 'end_time': 'datetime.time(1, 30, 0)'}), 'True', 'tail')


def test_t3(candidate_path):
    # release: Input:\nstart_date = datetime.date(2023, 1, 2)\nend_date = datetime.date(2023, 1, 1)\nstart_time = ...
    check_stdout(run_program(candidate_path, assignments={'start_date': 'datetime.date(2023, 1, 2)', 'end_date': 'datetime.date(2023, 1, 1)', 'start_time': 'datetime.time(1, 30, 0)', 'end_time': 'datetime.time(22, 30, 0)'}), 'False', 'tail')


def test_t4(candidate_path):
    # release: Input:\nstart_date = datetime.date(2023, 1, 2)\nend_date = datetime.date(2023, 1, 2)\nstart_time = ...
    check_stdout(run_program(candidate_path, assignments={'start_date': 'datetime.date(2023, 1, 2)', 'end_date': 'datetime.date(2023, 1, 2)', 'start_time': 'datetime.time(12, 0, 0)', 'end_time': 'datetime.time(12, 0, 0)'}), 'False', 'tail')


def test_t5(candidate_path):
    # release: Input:\nstart_date = datetime.date(2023, 1, 2)\nend_date = datetime.date(2023, 1, 2)\nstart_time = ...
    check_stdout(run_program(candidate_path, assignments={'start_date': 'datetime.date(2023, 1, 2)', 'end_date': 'datetime.date(2023, 1, 2)', 'start_time': 'datetime.time(1, 30, 0)', 'end_time': 'datetime.time(22, 30, 0)'}), 'True', 'tail')
