# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/067 | mode: original | kind: function | entry: password_check | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called password_check. password_check should\n#take as input a single string. It should return a boolean:\n#True if the password ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/067', 'kind': 'function', 'entry': 'password_check'}
ENV = None


def test_t1(m):
    # release: Input: "Password1!"\nOutput: True
    check(call(m, TASK, ('Password1!',), {}), True, 'eq')


def test_t2(m):
    # release: Input: "password1"\nOutput: False
    check(call(m, TASK, ('password1',), {}), False, 'eq')


def test_t3(m):
    # release: Input: "PASSWORD1!"\nOutput: False
    check(call(m, TASK, ('PASSWORD1!',), {}), False, 'eq')


def test_t4(m):
    # release: Input: "Password!"\nOutput: False
    check(call(m, TASK, ('Password!',), {}), False, 'eq')


def test_t5(m):
    # release: Input: "Pass1!"\nOutput: False
    check(call(m, TASK, ('Pass1!',), {}), False, 'eq')
