# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/075 | mode: original | kind: function | entry: volume_and_area | comparison: eq
# Well-posed: yes
# Prompt: #Write a function called volume_and_area. volume_and_area\n#will take in a dictionary. This dictionary is guaranteed to\n#have three keys: ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/075', 'kind': 'function', 'entry': 'volume_and_area'}
ENV = None


def test_t1(m):
    # release: Input:\n{"length": 2, "width": 3, "height": 4}\nOutput:\n{"length": 2, "width": 3, "height": 4, ...
    check(call_or_arg(m, TASK, ({'length': 2, 'width': 3, 'height': 4},), {}), {'length': 2, 'width': 3, 'height': 4, 'volume': 24, 'area': 52}, 'eq')


def test_t2(m):
    # release: Input:\n{"length": 5, "width": 5, "height": 5}\nOutput:\n{"length": 5, "width": 5, "height": 5, ...
    check(call_or_arg(m, TASK, ({'length': 5, 'width': 5, 'height': 5},), {}), {'length': 5, 'width': 5, 'height': 5, 'volume': 125, 'area': 150}, 'eq')


def test_t3(m):
    # release: Input:\n{"length": 7, "width": 6, "height": 5}\nOutput:\n{"length": 7, "width": 6, "height": 5, ...
    check(call_or_arg(m, TASK, ({'length': 7, 'width': 6, 'height': 5},), {}), {'length': 7, 'width': 6, 'height': 5, 'volume': 210, 'area': 214}, 'eq')


def test_t4(m):
    # release: Input:\n{"length": 10, "width": 8, "height": 2}\nOutput:\n{"length": 10, "width": 8, "height": 2, ...
    check(call_or_arg(m, TASK, ({'length': 10, 'width': 8, 'height': 2},), {}), {'length': 10, 'width': 8, 'height': 2, 'volume': 160, 'area': 216}, 'eq')


def test_t5(m):
    # release: Input:\n{"length": 3, "width": 4, "height": 2}\nOutput:\n{"length": 3, "width": 4, "height": 2, ...
    check(call_or_arg(m, TASK, ({'length': 3, 'width': 4, 'height': 2},), {}), {'length': 3, 'width': 4, 'height': 2, 'volume': 24, 'area': 52}, 'eq')
