# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/020 | mode: original | kind: function | entry: shorten | comparison: eq
# Well-posed: yes
# Prompt: implement Setting up my twttr from Problem Set 2, restructuring your code per the below, wherein shorten expects a str as input and returns that ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/020', 'kind': 'function', 'entry': 'shorten'}
ENV = None


def test_t1(m):
    # release: Input: "Hello, World!"\nExpected Output: "Hll, Wrld!"
    check(call(m, TASK, ('Hello, World!',), {}), 'Hll, Wrld!', 'eq')


def test_t2(m):
    # release: Input: "Setting up my twttr"\nExpected Output: "Sttng p my twttr"
    check(call(m, TASK, ('Setting up my twttr',), {}), 'Sttng p my twttr', 'eq')


def test_t3(m):
    # release: Input: "I love programming"\nExpected Output: " lv prgrmmng"
    check(call(m, TASK, ('I love programming',), {}), ' lv prgrmmng', 'eq')


def test_t4(m):
    # release: Input: "OpenAI is awesome"\nExpected Output: "OpnAI s wsm"
    check(call(m, TASK, ('OpenAI is awesome',), {}), 'OpnAI s wsm', 'eq')


def test_t5(m):
    # release: Input: "Artificial Intelligence"\nExpected Output: "rtfcl ntpllgnc"
    check(call(m, TASK, ('Artificial Intelligence',), {}), 'rtfcl ntpllgnc', 'eq')
