# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/004 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: implement a program that prompts the user for an arithmetic expression and then calculates and outputs the result as a floating-point value ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/004', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 2 + 3\nOutput: 5.0
    check_stdout(run_program(candidate_path, stdin='2 + 3\n'), '5.0', 'tail')


def test_t2(candidate_path):
    # release: Input: 10 - 5\nOutput: 5.0
    check_stdout(run_program(candidate_path, stdin='10 - 5\n'), '5.0', 'tail')


def test_t3(candidate_path):
    # release: Input: 5 * 3\nOutput: 15.0
    check_stdout(run_program(candidate_path, stdin='5 * 3\n'), '15.0', 'tail')


def test_t4(candidate_path):
    # release: Input: 10 / 2\nOutput: 5.0
    check_stdout(run_program(candidate_path, stdin='10 / 2\n'), '5.0', 'tail')


def test_t5(candidate_path):
    # release: Input: -2 + 8\nOutput: 6.0
    check_stdout(run_program(candidate_path, stdin='-2 + 8\n'), '6.0', 'tail')
