# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/academic.py (and data/reference/academic/) instead, then rebuild.
# Task academic/003 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: implement a program that prompts the user for the name of a file and then outputs that file’s media type if the file’s name ends, case- ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'academic/003', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: image.gif\nOutput: image/gif
    check_stdout(run_program(candidate_path, stdin='image.gif\n'), 'image/gif', 'tail')


def test_t2(candidate_path):
    # release: Input: picture.JPG\nOutput: image/jpeg
    check_stdout(run_program(candidate_path, stdin='picture.JPG\n'), 'image/jpeg', 'tail')


def test_t3(candidate_path):
    # release: Input: data.txt\nOutput: text/plain
    check_stdout(run_program(candidate_path, stdin='data.txt\n'), 'text/plain', 'tail')


def test_t4(candidate_path):
    # release: Input: document.PDF\nOutput: application/pdf
    check_stdout(run_program(candidate_path, stdin='document.PDF\n'), 'application/pdf', 'tail')


def test_t5(candidate_path):
    # release: Input: report.zip\nOutput: application/zip
    check_stdout(run_program(candidate_path, stdin='report.zip\n'), 'application/zip', 'tail')


def test_t6(candidate_path):
    # release: Input: presentation.docx\nOutput: application/octet-stream
    check_stdout(run_program(candidate_path, stdin='presentation.docx\n'), 'application/octet-stream', 'tail')
