# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/090 | mode: original | kind: function | entry: double_letters | comparison: eq
# Well-posed: yes
# Prompt: Write a function named double_letters that takes a string as its parameter. The function should return True if there are two identical letters in ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/090', 'kind': 'function', 'entry': 'double_letters'}
ENV = None


def test_t1(m):
    # release: Input:\n"hello"\nOutput:\nTrue
    check(call(m, TASK, ('hello',), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n"nono"\nOutput:\nFalse
    check(call(m, TASK, ('nono',), {}), False, 'eq')


def test_t3(m):
    # release: Input:\n"aabbcc"\nOutput:\nTrue
    check(call(m, TASK, ('aabbcc',), {}), True, 'eq')


def test_t4(m):
    # release: Input:\n"rainbow"\nOutput:\nFalse
    check(call(m, TASK, ('rainbow',), {}), False, 'eq')


def test_t5(m):
    # release: Input:\n"look"\nOutput:\nTrue
    check(call(m, TASK, ('look',), {}), True, 'eq')
