# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/057 | mode: original | kind: function | entry: all_equal | comparison: eq
# Well-posed: yes
# Prompt: Define a function named all_equal that takes a list and checks whether all elements in the list are the same.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/057', 'kind': 'function', 'entry': 'all_equal'}
ENV = None


def test_t1(m):
    # release: Input:\n[1, 1, 1, 1]\nOutput:\nTrue
    check(call(m, TASK, ([1, 1, 1, 1],), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n["hello", "hello", "hello"]\nOutput:\nTrue
    check(call(m, TASK, (['hello', 'hello', 'hello'],), {}), True, 'eq')


def test_t3(m):
    # release: Input:\n[10, 10, 15, 10]\nOutput:\nFalse
    check(call(m, TASK, ([10, 10, 15, 10],), {}), False, 'eq')


def test_t4(m):
    # release: Input:\n[]\nOutput:\nTrue
    check(call(m, TASK, ([],), {}), True, 'eq')


def test_t5(m):
    # release: Input:\n[7]\nOutput:\nTrue
    check(call(m, TASK, ([7],), {}), True, 'eq')
