# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/077 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the required return/print format is not stated (the release tests assume one)
# Prompt: Write a function that takes two arguments, a and b, and returns their sum, product, and difference.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/077', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n3, 4\nOutput:\nSum: 7, Product: 12, Difference: -1
    check(call(m, TASK, (3, 4), {}), 'Sum: 7, Product: 12, Difference: -1', 'eq')


def test_t2(m):
    # release: Input:\n5, 5\nOutput:\nSum: 10, Product: 25, Difference: 0
    check(call(m, TASK, (5, 5), {}), 'Sum: 10, Product: 25, Difference: 0', 'eq')


def test_t3(m):
    # release: Input:\n10, 2\nOutput:\nSum: 12, Product: 20, Difference: 8
    check(call(m, TASK, (10, 2), {}), 'Sum: 12, Product: 20, Difference: 8', 'eq')


def test_t4(m):
    # release: Input:\n-5, -7\nOutput:\nSum: -12, Product: 35, Difference: 2
    check(call(m, TASK, (-5, -7), {}), 'Sum: -12, Product: 35, Difference: 2', 'eq')


def test_t5(m):
    # release: Input:\n0, 10\nOutput:\nSum: 10, Product: 0, Difference: -10
    check(call(m, TASK, (0, 10), {}), 'Sum: 10, Product: 0, Difference: -10', 'eq')
