# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/049 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: NO -- io_unspecified: the input format (how the values are read) is not stated; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: You are given a 2-D array with dimensions N x M. Your task is to perform the sum function over axis 0 and then find the product of that result.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/049', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\n2 3\n1 2 3\n4 5 6\nOutput:\n5 7 9\n315
    check_stdout(run_program(candidate_path, stdin='2 3\n1 2 3\n4 5 6\n'), '315', 'num')


def test_t2(candidate_path):
    # release: Input:\n3 2\n1 2\n3 4\n5 6\nOutput:\n9 12\n108
    check_stdout(run_program(candidate_path, stdin='3 2\n1 2\n3 4\n5 6\n'), '108', 'num')


def test_t3(candidate_path):
    # release: Input:\n1 1\n7\nOutput:\n7\n7
    check_stdout(run_program(candidate_path, stdin='1 1\n7\n'), '7', 'num')


def test_t4(candidate_path):
    # release: Input:\n3 3\n1 2 3\n4 5 6\n7 8 9\nOutput:\n12 15 18\n3240
    check_stdout(run_program(candidate_path, stdin='3 3\n1 2 3\n4 5 6\n7 8 9\n'), '3240', 'num')


def test_t5(candidate_path):
    # release: Input:\n2 4\n-1 2 -3 4\n1 -2 3 -4\nOutput:\n0 0 0 0\n0
    check_stdout(run_program(candidate_path, stdin='2 4\n-1 2 -3 4\n1 -2 3 -4\n'), '0', 'num')
