# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/033 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given an int n, return True if it is within 10 of 100 or 200. Note: abs(num) computes the absolute value of a number.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/033', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 92\nOutput: True (Because it's within 10 of 100)
    check(call(m, TASK, (92,), {}), True, 'eq')


def test_t2(m):
    # release: Input: 112\nOutput: True (Because it's within 10 of 100)
    check(call(m, TASK, (112,), {}), True, 'eq')


def test_t3(m):
    # release: Input: 205\nOutput: True (Because it's within 10 of 200)
    check(call(m, TASK, (205,), {}), True, 'eq')


def test_t4(m):
    # release: Input: 50\nOutput: False (It's not within 10 of either 100 or 200)
    check(call(m, TASK, (50,), {}), False, 'eq')


def test_t5(m):
    # release: Input: 190\nOutput: True (Because it's within 10 of 200)
    check(call(m, TASK, (190,), {}), True, 'eq')
