# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/109 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a string, return the string made of its first two chars, so the String "Hello" yields "He". If the string is shorter than length 2, return ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/109', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"Hello"\nOutput:\n"He"
    check(call(m, TASK, ('Hello',), {}), 'He', 'eq')


def test_t2(m):
    # release: Input:\n"python"\nOutput:\n"py"
    check(call(m, TASK, ('python',), {}), 'py', 'eq')


def test_t3(m):
    # release: Input:\n"programming"\nOutput:\n"pr"
    check(call(m, TASK, ('programming',), {}), 'pr', 'eq')


def test_t4(m):
    # release: Input:\n"openai"\nOutput:\n"op"
    check(call(m, TASK, ('openai',), {}), 'op', 'eq')


def test_t5(m):
    # release: Input:\n"X"\nOutput:\n"X"
    check(call(m, TASK, ('X',), {}), 'X', 'eq')
