# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/007 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: The goal of this challenge is to analyze a binary string consisting of only zeros and ones. Your code should find the biggest number of ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/007', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: "10000101111000"\nOutput: 4
    check(call(m, TASK, ('10000101111000',), {}), 4, 'eq')


def test_t2(m):
    # release: Input: "11001110001111"\nOutput: 3
    check(call(m, TASK, ('11001110001111',), {}), 3, 'eq')


def test_t3(m):
    # release: Input: "1111111"\nOutput: 0
    check(call(m, TASK, ('1111111',), {}), 0, 'eq')


def test_t4(m):
    # release: Input: "10000001"\nOutput: 6
    check(call(m, TASK, ('10000001',), {}), 6, 'eq')


def test_t5(m):
    # release: Input: "00110001001100010000"\nOutput: 5
    check(call(m, TASK, ('00110001001100010000',), {}), 5, 'eq')
