# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/102 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes an array of arrays with numbers. Return a new (single) array with the largest numbers of each.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/102', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n[[1, 2, 3], [4, 5, 6], [7, 8, 9]]\nOutput:\n[3, 6, 9]
    check(call(m, TASK, ([[1, 2, 3], [4, 5, 6], [7, 8, 9]],), {}), [3, 6, 9], 'eq')


def test_t2(m):
    # release: Input:\n[[10, 20, 30], [40, 50, 60], [70, 80, 90]]\nOutput:\n[30, 60, 90]
    check(call(m, TASK, ([[10, 20, 30], [40, 50, 60], [70, 80, 90]],), {}), [30, 60, 90], 'eq')


def test_t3(m):
    # release: Input:\n[[5, 10, 15], [20, 25, 30], [35, 40, 45]]\nOutput:\n[15, 30, 45]
    check(call(m, TASK, ([[5, 10, 15], [20, 25, 30], [35, 40, 45]],), {}), [15, 30, 45], 'eq')


def test_t4(m):
    # release: Input:\n[[-1, -2, -3], [-4, -5, -6], [-7, -8, -9]]\nOutput:\n[-1, -4, -7]
    check(call(m, TASK, ([[-1, -2, -3], [-4, -5, -6], [-7, -8, -9]],), {}), [-1, -4, -7], 'eq')


def test_t5(m):
    # release: Input:\n[[0, 1, 2], [3, 4, 5], [6, 7, 8]]\nOutput:\n[2, 5, 8]
    check(call(m, TASK, ([[0, 1, 2], [3, 4, 5], [6, 7, 8]],), {}), [2, 5, 8], 'eq')
