# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/042 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; release_expected_values_incoherent
# Note: HackerRank 'Maximize It!' stdin format assumed: 'K M', then 'N x1 .. xN' per list.
# Prompt: You are given a function f(X) = X^2. You are also given K lists. The ith list consists of Ni elements. You have to pick one element from each list ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/042', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nK = 2, M = 1000\nLists:\n[2, 5, 4]\n[8, 3]\nOutput:\n897\n\nExplanation:\nThe optimal ...
    check_stdout(run_program(candidate_path, stdin='2 1000\n3 2 5 4\n2 8 3\n'), '897', 'num')


def test_t2(candidate_path):
    # release: Input:\nK = 2, M = 100\nLists:\n[1, 7]\n[6, 9]\nOutput:\n130\n\nExplanation:\nThe optimal solution ...
    check_stdout(run_program(candidate_path, stdin='2 100\n2 1 7\n2 6 9\n'), '130', 'num')


def test_t3(candidate_path):
    # release: Input:\nK = 3, M = 1000\nLists:\n[1, 2]\n[3, 4]\n[5, 6]\nOutput:\n161\n\nExplanation:\nThe optimal ...
    check_stdout(run_program(candidate_path, stdin='3 1000\n2 1 2\n2 3 4\n2 5 6\n'), '161', 'num')


def test_t4(candidate_path):
    # release: Input:\nK = 1, M = 10\nLists:\n[3, 4, 5]\nOutput:\n25\n\nExplanation:\nThe optimal solution is 5 ...
    check_stdout(run_program(candidate_path, stdin='1 10\n3 3 4 5\n'), '25', 'num')


def test_t5(candidate_path):
    # release: Input:\nK = 3, M = 100\nLists:\n[10]\n[10]\n[10]\nOutput:\n300\n\nExplanation:\nThe optimal solution ...
    check_stdout(run_program(candidate_path, stdin='3 100\n1 10\n1 10\n1 10\n'), '300', 'num')
