# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/044 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: You are given a square matrix A with dimensions N x N. Your task is to find the determinant.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/044', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nMatrix A:\n[[1]]\nOutput:\n1
    check(call(m, TASK, ([[1]],), {}), 1, 'eq')


def test_t2(m):
    # release: Input:\nMatrix A:\n[[1, 2],\n[3, 4]]\nOutput:\n-2
    check(call(m, TASK, ([[1, 2], [3, 4]],), {}), -2, 'eq')


def test_t3(m):
    # release: Input:\nMatrix A:\n[[1, 2, 3],\n[0, 1, 4],\n[5, 6, 0]]\nOutput:\n5
    check(call(m, TASK, ([[1, 2, 3], [0, 1, 4], [5, 6, 0]],), {}), 5, 'eq')


def test_t4(m):
    # release: Input:\nMatrix A:\n[[2, 1, 1],\n[1, 3, 2],\n[1, 0, 0]]\nOutput:\n3
    check(call(m, TASK, ([[2, 1, 1], [1, 3, 2], [1, 0, 0]],), {}), 3, 'eq')


def test_t5(m):
    # release: Input:\nMatrix A:\n[[3, 2, 0, 1],\n[1, 1, 2, 1],\n[1, 3, 9, 7],\n[5, 2, 0, 9]]\nOutput:\n-376
    check(call(m, TASK, ([[3, 2, 0, 1], [1, 1, 2, 1], [1, 3, 9, 7], [5, 2, 0, 9]],), {}), -376, 'eq')
