# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/070 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Return the number of times that the string "hi" appears anywhere in the given string.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/070', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"hi there"\nOutput:\n1
    check(call(m, TASK, ('hi there',), {}), 1, 'eq')


def test_t2(m):
    # release: Input:\n"hihihihi"\nOutput:\n4
    check(call(m, TASK, ('hihihihi',), {}), 4, 'eq')


def test_t3(m):
    # release: Input:\n"hello, how high?"\nOutput:\n1
    check(call(m, TASK, ('hello, how high?',), {}), 1, 'eq')


def test_t4(m):
    # release: Input:\n"hip hip hooray!"\nOutput:\n2
    check(call(m, TASK, ('hip hip hooray!',), {}), 2, 'eq')


def test_t5(m):
    # release: Input:\n"This is his kite."\nOutput:\n1
    check(call(m, TASK, ('This is his kite.',), {}), 1, 'eq')
