# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/117 | mode: original | kind: vars | entry: None | comparison: nums_in
# Well-posed: NO -- missing_context: the prompt refers to starter code or data that it does not include; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt; ambiguous: the prompt admits several readings that give different expected values (print the values above 23 or their indices; tests assume indices)
# Prompt: Use subsetting to find out which observations in our BMI array are above 23

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/117', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nBMI_array = np.array([24.22, 22.04, 26.23, 20.81, 26.32])\nOutput:\nAbove_23_indices = [0 2 4]
    check_stdout(run_program(candidate_path, assignments={'BMI_array': 'np.array([24.22, 22.04, 26.23, 20.81, 26.32])'}), [0, 2, 4], 'nums_in')


def test_t2(candidate_path):
    # release: Input:\nBMI_array = np.array([24.44, 24.22, 26.12, 24.49, 26.34])\nOutput:\nAbove_23_indices = [0 1 ...
    check_stdout(run_program(candidate_path, assignments={'BMI_array': 'np.array([24.44, 24.22, 26.12, 24.49, 26.34])'}), [0, 1, 2, 3, 4], 'nums_in')


def test_t3(candidate_path):
    # release: Input:\nBMI_array = np.array([22.66, 24.92, 20.85, 26.23, 21.85])\nOutput:\nAbove_23_indices = [1 3]
    check_stdout(run_program(candidate_path, assignments={'BMI_array': 'np.array([22.66, 24.92, 20.85, 26.23, 21.85])'}), [1, 3], 'nums_in')


def test_t4(candidate_path):
    # release: Input:\nBMI_array = np.array([23.88, 22.2, 21.48, 21.93, 23.11])\nOutput:\nAbove_23_indices = [0 4]
    check_stdout(run_program(candidate_path, assignments={'BMI_array': 'np.array([23.88, 22.2, 21.48, 21.93, 23.11])'}), [0, 4], 'nums_in')


def test_t5(candidate_path):
    # release: Input:\nBMI_array = np.array([24.69, 25.46, 25.47, 26.25, 25.95])\nOutput:\nAbove_23_indices = [0 1 ...
    check_stdout(run_program(candidate_path, assignments={'BMI_array': 'np.array([24.69, 25.46, 25.47, 26.25, 25.95])'}), [0, 1, 2, 3, 4], 'nums_in')
