# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/029 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given two int values, return their sum. Unless the two values are the same, then return double their sum.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/029', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 5, 5\nOutput: 20 (Because 5 + 5 = 10 and 10*2 = 20)
    check(call(m, TASK, (5, 5), {}), 20, 'eq')


def test_t2(m):
    # release: Input: 3, 7\nOutput: 10 (Simply 3 + 7)
    check(call(m, TASK, (3, 7), {}), 10, 'eq')


def test_t3(m):
    # release: Input: 0, 0\nOutput: 0 (Because 0 + 0 = 0 and 0*2 = 0)
    check(call(m, TASK, (0, 0), {}), 0, 'eq')


def test_t4(m):
    # release: Input: -5, 5\nOutput: 0 (Simply -5 + 5)
    check(call(m, TASK, (-5, 5), {}), 0, 'eq')


def test_t5(m):
    # release: Input: 6, 6\nOutput: 24 (Because 6 + 6 = 12 and 12*2 = 24)
    check(call(m, TASK, (6, 6), {}), 24, 'eq')
