# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/079 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the required return/print format is not stated (the release tests assume one)
# Prompt: Write a function that takes two sets and returns their union, intersection, and difference.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/079', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n{1, 2, 3}, {3, 4, 5}\nOutput:\nUnion: {1, 2, 3, 4, 5}, Intersection: {3}, Difference: {1, 2}
    check(call(m, TASK, ({1, 2, 3}, {3, 4, 5}), {}), 'Union: {1, 2, 3, 4, 5}, Intersection: {3}, Difference: {1, 2}', 'eq')


def test_t2(m):
    # release: Input:\n{5, 6, 7}, {8, 9, 10}\nOutput:\nUnion: {5, 6, 7, 8, 9, 10}, Intersection: {}, Difference: ...
    check(call(m, TASK, ({5, 6, 7}, {8, 9, 10}), {}), 'Union: {5, 6, 7, 8, 9, 10}, Intersection: {}, Difference: {5, 6, 7}', 'eq')


def test_t3(m):
    # release: Input:\n{10, 20, 30}, {20, 30, 40}\nOutput:\nUnion: {10, 20, 30, 40}, Intersection: {20, 30}, ...
    check(call(m, TASK, ({10, 20, 30}, {40, 20, 30}), {}), 'Union: {10, 20, 30, 40}, Intersection: {20, 30}, Difference: {10}', 'eq')


def test_t4(m):
    # release: Input:\n{1, 3, 5}, {2, 4, 6}\nOutput:\nUnion: {1, 2, 3, 4, 5, 6}, Intersection: {}, Difference: {1, ...
    check(call(m, TASK, ({1, 3, 5}, {2, 4, 6}), {}), 'Union: {1, 2, 3, 4, 5, 6}, Intersection: {}, Difference: {1, 3, 5}', 'eq')


def test_t5(m):
    # release: Input:\n{100, 200, 300}, {300, 400, 500}\nOutput:\nUnion: {100, 200, 300, 400, 500}, Intersection: ...
    check(call(m, TASK, ({200, 100, 300}, {400, 300, 500}), {}), 'Union: {100, 200, 300, 400, 500}, Intersection: {300}, Difference: {100, 200}', 'eq')
