# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/003 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: The aim of this challenge is, given a dictionary of people's online status, to count the number of people who are online.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/003', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: {"Alice": "online", "Bob": "offline", "Charlie": "online", "David": "offline"}\nOutput: 2
    check(call(m, TASK, ({'Alice': 'online', 'Bob': 'offline', 'Charlie': 'online', 'David': 'offline'},), {}), 2, 'eq')


def test_t2(m):
    # release: Input: {"Eva": "online", "Frank": "online", "Grace": "online"}\nOutput: 3
    check(call(m, TASK, ({'Eva': 'online', 'Frank': 'online', 'Grace': 'online'},), {}), 3, 'eq')


def test_t3(m):
    # release: Input: {"Henry": "offline", "Isabelle": "offline", "Jack": "offline"}\nOutput: 0
    check(call(m, TASK, ({'Henry': 'offline', 'Isabelle': 'offline', 'Jack': 'offline'},), {}), 0, 'eq')


def test_t4(m):
    # release: Input: {}\nOutput: 0
    check(call(m, TASK, ({},), {}), 0, 'eq')


def test_t5(m):
    # release: Input: {"Katie": "online", "Liam": "offline", "Mia": "online", "Nina": "offline", "Oscar": "online", ...
    check(call(m, TASK, ({'Katie': 'online', 'Liam': 'offline', 'Mia': 'online', 'Nina': 'offline', 'Oscar': 'online', 'Paul': 'online'},), {}), 4, 'eq')
