# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/012 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- io_unspecified: the input format (how the values are read) is not stated (n could be read from stdin or passed to a function)
# Prompt: Given an integer, n, perform the following conditional actions: If n is odd, print Weird. If n is even and in the inclusive range of 2 to 5, print ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/012', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 3\nOutput: "Weird"
    check_stdout(run_program(candidate_path, stdin='3\n'), 'Weird', 'tail')


def test_t2(candidate_path):
    # release: Input: 4\nOutput: "Not Weird"
    check_stdout(run_program(candidate_path, stdin='4\n'), 'Not Weird', 'tail')


def test_t3(candidate_path):
    # release: Input: 8\nOutput: "Weird"
    check_stdout(run_program(candidate_path, stdin='8\n'), 'Weird', 'tail')


def test_t4(candidate_path):
    # release: Input: 22\nOutput: "Not Weird"
    check_stdout(run_program(candidate_path, stdin='22\n'), 'Not Weird', 'tail')


def test_t5(candidate_path):
    # release: Input: 18\nOutput: "Weird"
    check_stdout(run_program(candidate_path, stdin='18\n'), 'Weird', 'tail')
