# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/001 | mode: original | kind: function | entry: capital_indexes | comparison: eq
# Well-posed: yes
# Prompt: Write a function named capital_indexes. The function takes a single parameter, which is a string. Your function should return a list of all the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/001', 'kind': 'function', 'entry': 'capital_indexes'}
ENV = None


def test_t1(m):
    # release: Input: "Hello World"\nOutput: [0, 6]
    check(call(m, TASK, ('Hello World',), {}), [0, 6], 'eq')


def test_t2(m):
    # release: Input: "wElcOmE To ChatGPT"\nOutput: [1, 4, 7, 9, 14]
    check(call(m, TASK, ('wElcOmE To ChatGPT',), {}), [1, 4, 7, 9, 14], 'eq')


def test_t3(m):
    # release: Input: "allsmallletters"\nOutput: []
    check(call(m, TASK, ('allsmallletters',), {}), [], 'eq')


def test_t4(m):
    # release: Input: "CAPSLOCKON"\nOutput: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    check(call(m, TASK, ('CAPSLOCKON',), {}), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'eq')


def test_t5(m):
    # release: Input: "First, Second, Third."\nOutput: [0, 7, 15]
    check(call(m, TASK, ('First, Second, Third.',), {}), [0, 7, 15], 'eq')
