# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/100 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes an array of numbers and returns the mean value.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/100', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n[1, 2, 3, 4, 5]\nOutput:\n3.0
    check(call(m, TASK, ([1, 2, 3, 4, 5],), {}), 3.0, 'eq')


def test_t2(m):
    # release: Input:\n[10, 20, 30, 40, 50]\nOutput:\n30.0
    check(call(m, TASK, ([10, 20, 30, 40, 50],), {}), 30.0, 'eq')


def test_t3(m):
    # release: Input:\n[2.5, 3.5, 4.5, 5.5]\nOutput:\n4.0
    check(call(m, TASK, ([2.5, 3.5, 4.5, 5.5],), {}), 4.0, 'eq')


def test_t4(m):
    # release: Input:\n[-1, 0, 1]\nOutput:\n0.0
    check(call(m, TASK, ([-1, 0, 1],), {}), 0.0, 'eq')


def test_t5(m):
    # release: Input:\n[1000]\nOutput:\n1000.0
    check(call(m, TASK, ([1000],), {}), 1000.0, 'eq')
