# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/082 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: We add a Leap Day on February 29, almost every four years. The leap day is an extra, or intercalary day and we add it to the shortest month of the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/082', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n2000\nOutput:\nTrue
    check(call(m, TASK, (2000,), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n2100\nOutput:\nFalse
    check(call(m, TASK, (2100,), {}), False, 'eq')


def test_t3(m):
    # release: Input:\n2024\nOutput:\nTrue
    check(call(m, TASK, (2024,), {}), True, 'eq')


def test_t4(m):
    # release: Input:\n1900\nOutput:\nFalse
    check(call(m, TASK, (1900,), {}), False, 'eq')


def test_t5(m):
    # release: Input:\n2400\nOutput:\nTrue
    check(call(m, TASK, (2400,), {}), True, 'eq')
