# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/071 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Return True if the string "cat" and "dog" appear the same number of times in the given string.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/071', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"catdog"\nOutput:\nTrue
    check(call(m, TASK, ('catdog',), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n"catcat"\nOutput:\nFalse
    check(call(m, TASK, ('catcat',), {}), False, 'eq')


def test_t3(m):
    # release: Input:\n"dogdogcat"\nOutput:\nFalse
    check(call(m, TASK, ('dogdogcat',), {}), False, 'eq')


def test_t4(m):
    # release: Input:\n"catxdogxdogxcat"\nOutput:\nTrue
    check(call(m, TASK, ('catxdogxdogxcat',), {}), True, 'eq')


def test_t5(m):
    # release: Input:\n"dogdogdogcatcat"\nOutput:\nTrue
    check(call(m, TASK, ('dogdogdogcatcat',), {}), True, 'eq')
