# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/067 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Note: Argument order follows the prompt: N, then the coin values S.
# Prompt: Given a value N, if we want to make change for N cents, and we have infinite supply of each of S = { S1, S2, .. , Sm} valued coins, how many ways ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/067', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nN: 4\nS: [1, 2, 3]\nOutput:\n4\n(Explanation: {1,1,1,1}, {1,1,2}, {2,2}, {1,3})
    check(call(m, TASK, (4, [1, 2, 3]), {}), 4, 'eq')


def test_t2(m):
    # release: Input:\nN: 10\nS: [2, 5, 3, 6]\nOutput:\n5\n(Explanation: {2,2,2,2,2}, {2,2,3,3}, {2,2,6}, {2,3,5}, ...
    check(call(m, TASK, (10, [2, 5, 3, 6]), {}), 5, 'eq')


def test_t3(m):
    # release: Input:\nN: 5\nS: [1, 2, 5]\nOutput:\n4\n(Explanation: {1,1,1,1,1}, {1,1,1,2}, {1,2,2}, {5})
    check(call(m, TASK, (5, [1, 2, 5]), {}), 4, 'eq')


def test_t4(m):
    # release: Input:\nN: 3\nS: [2, 3]\nOutput:\n1\n(Explanation: {3})
    check(call(m, TASK, (3, [2, 3]), {}), 1, 'eq')


def test_t5(m):
    # release: Input:\nN: 7\nS: [3, 4]\nOutput:\n0\n(Explanation: No combination can sum up to 7 using coins of ...
    check(call(m, TASK, (7, [3, 4]), {}), 0, 'eq')
