# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/045 | mode: original | kind: function | entry: None | comparison: seq
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: You are given two arrays A and B. Both have dimensions of N x N. Your task is to compute their matrix product.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/045', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nMatrix A:\n[[1]]\nMatrix B:\n[[2]]\nOutput:\n[[2]]
    check(call(m, TASK, ([[1]], [[2]]), {}), [[2]], 'seq')


def test_t2(m):
    # release: Input:\nMatrix A:\n[[1, 2],\n[3, 4]]\nMatrix B:\n[[2, 0],\n[1, 3]]\nOutput:\n[[4, 6],\n[10, 12]]
    check(call(m, TASK, ([[1, 2], [3, 4]], [[2, 0], [1, 3]]), {}), [[4, 6], [10, 12]], 'seq')


def test_t3(m):
    # release: Input:\nMatrix A:\n[[1, 0, 2],\n[0, 1, 1],\n[1, 1, 0]]\nMatrix B:\n[[1, 2, 1],\n[0, 1, 0],\n[1, 3, ...
    check(call(m, TASK, ([[1, 0, 2], [0, 1, 1], [1, 1, 0]], [[1, 2, 1], [0, 1, 0], [1, 3, 2]]), {}), [[3, 8, 5], [1, 4, 2], [1, 3, 1]], 'seq')


def test_t4(m):
    # release: Input:\nMatrix A:\n[[1, 2, 1],\n[0, 1, 0],\n[2, 3, 4]]\nMatrix B:\n[[2, 5, 1],\n[6, 7, 1],\n[0, 8, ...
    check(call(m, TASK, ([[1, 2, 1], [0, 1, 0], [2, 3, 4]], [[2, 5, 1], [6, 7, 1], [0, 8, 1]]), {}), [[14, 21, 4], [6, 7, 1], [8, 63, 6]], 'seq')


def test_t5(m):
    # release: Input:\nMatrix A:\n[[3, 0, 2],\n[2, 0, -2],\n[0, 1, 1]]\nMatrix B:\n[[0, 0, 1],\n[3, -1, 0],\n[1, 2, ...
    check(call(m, TASK, ([[3, 0, 2], [2, 0, -2], [0, 1, 1]], [[0, 0, 1], [3, -1, 0], [1, 2, 1]]), {}), [[6, 4, 5], [-2, -4, 0], [4, 1, 1]], 'seq')
