# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/004 | mode: original | kind: function | entry: random_number | comparison: eq
# Well-posed: yes
# Note: Property test: the release gives only 'any number between 1 and 100'.
# Prompt: Define a function, random_number, that takes no parameters. The function must generate a random integer between 1 and 100.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/004', 'kind': 'function', 'entry': 'random_number'}
ENV = None


def test_t1(m):
    # release: Input:\nOutput: (Any number between 1 and 100, e.g., 57)
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r


def test_t2(m):
    # release: Input:\nOutput: (Any number between 1 and 100, e.g., 23)
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r


def test_t3(m):
    # release: Input:\nOutput: (Any number between 1 and 100, e.g., 89)
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r


def test_t4(m):
    # release: Input:\nOutput: (Any number between 1 and 100, e.g., 1)
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r


def test_t5(m):
    # release: Input:\nOutput: (Any number between 1 and 100, e.g., 100)
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r
