# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/017 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- io_unspecified: the input format (how the values are read) is not stated (where N comes from is not stated)
# Prompt: Without using any string methods, try to print the following: 123...N

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/017', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: 5\nOutput: 12345
    check_stdout(run_program(candidate_path, stdin='5\n'), '12345', 'tail')


def test_t2(candidate_path):
    # release: Input: 3\nOutput: 123
    check_stdout(run_program(candidate_path, stdin='3\n'), '123', 'tail')


def test_t3(candidate_path):
    # release: Input: 1\nOutput: 1
    check_stdout(run_program(candidate_path, stdin='1\n'), '1', 'tail')


def test_t4(candidate_path):
    # release: Input: 10\nOutput: 12345678910
    check_stdout(run_program(candidate_path, stdin='10\n'), '12345678910', 'tail')


def test_t5(candidate_path):
    # release: Input: 7\nOutput: 1234567
    check_stdout(run_program(candidate_path, stdin='7\n'), '1234567', 'tail')
