# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/087 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: NO -- no_task_statement: the prompt only describes numpy.linalg.det; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: The NumPy module also comes with a number of built-in routines for linear algebra calculations. These can be found in the sub-module linalg. ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/087', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\n[[1, 2], [3, 4]]\nOutput:\n-2.0\n\nExplanation:\nDeterminant of matrix\n| 1 2 |\n| 3 4 | is ...
    check_stdout(run_program(candidate_path, stdin='2\n1 2\n3 4\n'), '-2.0', 'num')


def test_t2(candidate_path):
    # release: Input:\n[[6]]\nOutput:\n6.0\n\nExplanation:\nDeterminant of a 1x1 matrix is simply the value in it.
    check_stdout(run_program(candidate_path, stdin='1\n6\n'), '6.0', 'num')


def test_t3(candidate_path):
    # release: Input:\n[[1, 0, 0], [0, 1, 0], [0, 0, 1]]\nOutput:\n1.0\n\nExplanation:\nDeterminant of the identity ...
    check_stdout(run_program(candidate_path, stdin='3\n1 0 0\n0 1 0\n0 0 1\n'), '1.0', 'num')


def test_t4(candidate_path):
    # release: Input:\n[[2, 3], [2, 3]]\nOutput:\n0.0\n\nExplanation:\nDeterminant of matrix with dependent rows is 0.
    check_stdout(run_program(candidate_path, stdin='2\n2 3\n2 3\n'), '0.0', 'num')


def test_t5(candidate_path):
    # release: Input:\n[[5, 4, 2], [1, 3, 1], [2, 1, 3]]\nOutput:\n49.0\n\nExplanation:\nUsing the Laplace ...
    check_stdout(run_program(candidate_path, stdin='3\n5 4 2\n1 3 1\n2 1 3\n'), '49.0', 'num')
