# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/078 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the required return/print format is not stated (the release tests assume one); release tests 3 and 4 disagree on whether 'Python' must be a whole word
# Prompt: Write a regular expression that matches a string containing the word 'Python'.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/078', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"I love Python programming."\nOutput:\nMatch
    check(call(m, TASK, ('I love Python programming.',), {}), 'Match', 'eq')


def test_t2(m):
    # release: Input:\n"Python is versatile."\nOutput:\nMatch
    check(call(m, TASK, ('Python is versatile.',), {}), 'Match', 'eq')


def test_t3(m):
    # release: Input:\n"I'm attending a Pythoneer meetup."\nOutput:\nNo Match
    check(call(m, TASK, ("I'm attending a Pythoneer meetup.",), {}), 'No Match', 'eq')


def test_t4(m):
    # release: Input:\n"Pythons are also a type of snake."\nOutput:\nMatch
    check(call(m, TASK, ('Pythons are also a type of snake.',), {}), 'Match', 'eq')


def test_t5(m):
    # release: Input:\n"python in lowercase shouldn't match."\nOutput:\nNo Match
    check(call(m, TASK, ("python in lowercase shouldn't match.",), {}), 'No Match', 'eq')
