# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/107 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given an "out" string length 4, such as "<<>>", and a word, return a new string where the word is in the middle of the out string, e.g. "<<word>>".

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/107', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"<<>>", "hello"\nOutput:\n"<<hello>>"
    check(call(m, TASK, ('<<>>', 'hello'), {}), '<<hello>>', 'eq')


def test_t2(m):
    # release: Input:\n"[[]]", "world"\nOutput:\n"[[world]]"
    check(call(m, TASK, ('[[]]', 'world'), {}), '[[world]]', 'eq')


def test_t3(m):
    # release: Input:\n"()", "python"\nOutput:\n"(python)"
    check(call(m, TASK, ('()', 'python'), {}), '(python)', 'eq')


def test_t4(m):
    # release: Input:\n"{{}}", "programming"\nOutput:\n"{{programming}}"
    check(call(m, TASK, ('{{}}', 'programming'), {}), '{{programming}}', 'eq')


def test_t5(m):
    # release: Input:\n"**", "openai"\nOutput:\n"openai"
    check(call(m, TASK, ('**', 'openai'), {}), 'openai', 'eq')
