# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/060 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- ambiguous: the prompt admits several readings that give different expected values (the counting step k is not given; tests assume k = 2)
# Prompt: The Josephus Problem is a theoretical problem related to a certain counting-out game. Create a function that takes a number n and returns the last ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/060', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n7\nOutput:\n7
    check(call(m, TASK, (7,), {}), 7, 'eq')


def test_t2(m):
    # release: Input:\n1\nOutput:\n1
    check(call(m, TASK, (1,), {}), 1, 'eq')


def test_t3(m):
    # release: Input:\n10\nOutput:\n5
    check(call(m, TASK, (10,), {}), 5, 'eq')


def test_t4(m):
    # release: Input:\n100\nOutput:\n73
    check(call(m, TASK, (100,), {}), 73, 'eq')


def test_t5(m):
    # release: Input:\n6\nOutput:\n5
    check(call(m, TASK, (6,), {}), 5, 'eq')
