# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/064 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: You are given two identical eggs and you have access to a building with n floors. What is the minimum number of trials you need to find the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/064', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n10 floors\nOutput:\n4\n(Explanation: Drop first egg from floors 4, 7, 9. If it breaks on 4, ...
    check(call(m, TASK, (10,), {}), 4, 'eq')


def test_t2(m):
    # release: Input:\n100 floors\nOutput:\n14\n(Explanation: This involves a bit more strategy. For simplicity, we ...
    check(call(m, TASK, (100,), {}), 14, 'eq')


def test_t3(m):
    # release: Input:\n2 floors\nOutput:\n2\n(Explanation: Drop the first egg from the 1st floor. If it breaks, we ...
    check(call(m, TASK, (2,), {}), 2, 'eq')


def test_t4(m):
    # release: Input:\n1 floor\nOutput:\n1\n(Explanation: Only one floor to test. So, one drop is enough.)
    check(call(m, TASK, (1,), {}), 1, 'eq')


def test_t5(m):
    # release: Input:\n20 floors\nOutput:\n6\n(Explanation: Drop first egg from floors 5, 10, 14, 17, 19. This ...
    check(call(m, TASK, (20,), {}), 6, 'eq')
