# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/091 | mode: original | kind: function | entry: add_dots | comparison: eq
# Well-posed: yes
# Prompt: Write a function named add_dots that takes a string and adds "." in between each letter. Write another function named remove_dots that removes all ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/091', 'kind': 'function', 'entry': 'add_dots'}
ENV = None


def test_t1(m):
    # release: Input:\n"hello"\nOutput:\n"h.e.l.l.o"
    check(call(m, TASK, ('hello',), {}), 'h.e.l.l.o', 'eq')


def test_t2(m):
    # release: Input:\n"abc"\nOutput:\n"a.b.c"
    check(call(m, TASK, ('abc',), {}), 'a.b.c', 'eq')


def test_t3(m):
    # release: Input:\n"dog"\nOutput:\n"d.o.g"
    check(call(m, TASK, ('dog',), {}), 'd.o.g', 'eq')


def test_t4(m):
    # release: Input:\n"j"\nOutput:\n"j"
    check(call(m, TASK, ('j',), {}), 'j', 'eq')


def test_t5(m):
    # release: Input:\n""\nOutput:\n""
    check(call(m, TASK, ('',), {}), '', 'eq')
