# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/072 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Return the number of times that the string "code" appears anywhere in the given string, except we'll accept any letter for the 'd', so "cope" and ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/072', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"codecorecopecoor"\nOutput:\n3
    check(call(m, TASK, ('codecorecopecoor',), {}), 3, 'eq')


def test_t2(m):
    # release: Input:\n"codecodercofe"\nOutput:\n2
    check(call(m, TASK, ('codecodercofe',), {}), 2, 'eq')


def test_t3(m):
    # release: Input:\n"coze"\nOutput:\n1
    check(call(m, TASK, ('coze',), {}), 1, 'eq')


def test_t4(m):
    # release: Input:\n"codelcooecode"\nOutput:\n2
    check(call(m, TASK, ('codelcooecode',), {}), 2, 'eq')


def test_t5(m):
    # release: Input:\n"cote"\nOutput:\n1
    check(call(m, TASK, ('cote',), {}), 1, 'eq')
