# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/027 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: The parameter weekday is True if it is a weekday, and the parameter vacation is True if we are on vacation. We sleep in if it is not a weekday or ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/027', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: weekday = True, vacation = False\nOutput: False (It's a weekday and we're not on vacation)
    check(call(m, TASK, (True, False), {}), False, 'eq')


def test_t2(m):
    # release: Input: weekday = False, vacation = False\nOutput: True (It's not a weekday and we're not on vacation)
    check(call(m, TASK, (False, False), {}), True, 'eq')


def test_t3(m):
    # release: Input: weekday = False, vacation = True\nOutput: True (It's not a weekday and we're on vacation)
    check(call(m, TASK, (False, True), {}), True, 'eq')


def test_t4(m):
    # release: Input: weekday = True, vacation = True\nOutput: True (It's a weekday but we're on vacation)
    check(call(m, TASK, (True, True), {}), True, 'eq')


def test_t5(m):
    # release: Input: weekday = False, vacation = False\nOutput: True (It's not a weekday and we're not on vacation)
    check(call(m, TASK, (False, False), {}), True, 'eq')
