# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/035 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a string, return a new string where "not " has been added to the front. However, if the string already begins with "not", return the string ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/035', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: "happy"\nOutput: "not happy"
    check(call(m, TASK, ('happy',), {}), 'not happy', 'eq')


def test_t2(m):
    # release: Input: "not bad"\nOutput: "not bad" (Because it already begins with "not")
    check(call(m, TASK, ('not bad',), {}), 'not bad', 'eq')


def test_t3(m):
    # release: Input: "sad"\nOutput: "not sad"
    check(call(m, TASK, ('sad',), {}), 'not sad', 'eq')


def test_t4(m):
    # release: Input: "not good"\nOutput: "not good" (Because it already begins with "not")
    check(call(m, TASK, ('not good',), {}), 'not good', 'eq')


def test_t5(m):
    # release: Input: "okay"\nOutput: "not okay"
    check(call(m, TASK, ('okay',), {}), 'not okay', 'eq')
