# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/069 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a string, return a string where for every char in the original, there are two chars.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/069', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"hello"\nOutput:\n"hheelllloo"
    check(call(m, TASK, ('hello',), {}), 'hheelllloo', 'eq')


def test_t2(m):
    # release: Input:\n"abc"\nOutput:\n"aabbcc"
    check(call(m, TASK, ('abc',), {}), 'aabbcc', 'eq')


def test_t3(m):
    # release: Input:\n"!"\nOutput:\n"!!"
    check(call(m, TASK, ('!',), {}), '!!', 'eq')


def test_t4(m):
    # release: Input:\n"double"\nOutput:\n"ddoouubbllee"
    check(call(m, TASK, ('double',), {}), 'ddoouubbllee', 'eq')


def test_t5(m):
    # release: Input:\n"space "\nOutput:\n"ssppacee "
    check(call(m, TASK, ('space ',), {}), 'ssppacee ', 'eq')
