# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/084 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; release test 5 breaks the prompt's constraint (length not divisible by k)
# Prompt: Consider a string, s="AABCAAADA" and an integer, k=3. We can split s into n/k=3 substrings where each subtring, ti, consists of a contiguous block ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/084', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\ns="AABCAAADA", k=3\nOutput:\n"AB", "CA", "AD"
    check_stdout(run_program(candidate_path, stdin='AABCAAADA\n3\n'), 'AB\nCA\nAD', 'tail')


def test_t2(candidate_path):
    # release: Input:\ns="AABBCCDDEE", k=2\nOutput:\n"AB", "AB", "BC", "CD", "DE", "EE"
    check_stdout(run_program(candidate_path, stdin='AABBCCDDEE\n2\n'), 'AB\nAB\nBC\nCD\nDE\nEE', 'tail')


def test_t3(candidate_path):
    # release: Input:\ns="XYZXYZXYZ", k=3\nOutput:\n"XYZ", "XYZ", "XYZ"
    check_stdout(run_program(candidate_path, stdin='XYZXYZXYZ\n3\n'), 'XYZ\nXYZ\nXYZ', 'tail')


def test_t4(candidate_path):
    # release: Input:\ns="ABCDE", k=1\nOutput:\n"A", "B", "C", "D", "E"
    check_stdout(run_program(candidate_path, stdin='ABCDE\n1\n'), 'A\nB\nC\nD\nE', 'tail')


def test_t5(candidate_path):
    # release: Input:\ns="WWEELLCCOOMMEE", k=5\nOutput:\n"WELC", "OMME", "E"
    check_stdout(run_program(candidate_path, stdin='WWEELLCCOOMMEE\n5\n'), 'WELC\nOMME\nE', 'tail')
