# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/032 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given 2 ints, a and b, return True if one if them is 10 or if their sum is 10.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/032', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: a = 5, b = 5\nOutput: True (Because 5 + 5 = 10)
    check(call(m, TASK, (5, 5), {}), True, 'eq')


def test_t2(m):
    # release: Input: a = 10, b = 3\nOutput: True (Because one of them is 10)
    check(call(m, TASK, (10, 3), {}), True, 'eq')


def test_t3(m):
    # release: Input: a = 4, b = 3\nOutput: False (Neither is 10, and their sum isn't 10)
    check(call(m, TASK, (4, 3), {}), False, 'eq')


def test_t4(m):
    # release: Input: a = 7, b = 10\nOutput: True (Because one of them is 10)
    check(call(m, TASK, (7, 10), {}), True, 'eq')


def test_t5(m):
    # release: Input: a = 2, b = 8\nOutput: True (Because 2 + 8 = 10)
    check(call(m, TASK, (2, 8), {}), True, 'eq')
