# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/037 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: NO -- missing_context: the prompt refers to starter code or data that it does not include (the LearnPython starter code with the print statement)
# Prompt: Add the numbers 1, 2, and 3 to the "numbers" list, and see what the "print" statement outputs

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/037', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: numbers = []\nOutput: [1, 2, 3]
    check_stdout(run_program(candidate_path, assignments={'numbers': '[]'}), '[1, 2, 3]', 'tail')


def test_t2(candidate_path):
    # release: Input: numbers = [0]\nOutput: [0, 1, 2, 3]
    check_stdout(run_program(candidate_path, assignments={'numbers': '[0]'}), '[0, 1, 2, 3]', 'tail')


def test_t3(candidate_path):
    # release: Input: numbers = [4, 5, 6]\nOutput: [4, 5, 6, 1, 2, 3]
    check_stdout(run_program(candidate_path, assignments={'numbers': '[4, 5, 6]'}), '[4, 5, 6, 1, 2, 3]', 'tail')


def test_t4(candidate_path):
    # release: Input: numbers = [3, 2, 1]\nOutput: [3, 2, 1, 1, 2, 3]
    check_stdout(run_program(candidate_path, assignments={'numbers': '[3, 2, 1]'}), '[3, 2, 1, 1, 2, 3]', 'tail')


def test_t5(candidate_path):
    # release: Input: numbers = [-1, -2, -3]\nOutput: [-1, -2, -3, 1, 2, 3]
    check_stdout(run_program(candidate_path, assignments={'numbers': '[-1, -2, -3]'}), '[-1, -2, -3, 1, 2, 3]', 'tail')
