# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/097 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes two arguments: the original price and the discount percentage as integers and returns the final price after the discount.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/097', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n100, 10\nOutput:\n90.0
    check(call(m, TASK, (100, 10), {}), 90.0, 'eq')


def test_t2(m):
    # release: Input:\n500, 50\nOutput:\n250.0
    check(call(m, TASK, (500, 50), {}), 250.0, 'eq')


def test_t3(m):
    # release: Input:\n79, 5\nOutput:\n75.05
    check(call(m, TASK, (79, 5), {}), 75.05, 'eq')


def test_t4(m):
    # release: Input:\n200, 0\nOutput:\n200.0
    check(call(m, TASK, (200, 0), {}), 200.0, 'eq')


def test_t5(m):
    # release: Input:\n1000, 100\nOutput:\n0.0
    check(call(m, TASK, (1000, 100), {}), 0.0, 'eq')
