# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/025 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes a number as its only argument and returns True if it's less than or equal to zero, otherwise return False.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/025', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: -5\nOutput: True
    check(call(m, TASK, (-5,), {}), True, 'eq')


def test_t2(m):
    # release: Input: 1\nOutput: False
    check(call(m, TASK, (1,), {}), False, 'eq')


def test_t3(m):
    # release: Input: 0\nOutput: True
    check(call(m, TASK, (0,), {}), True, 'eq')


def test_t4(m):
    # release: Input: -0.1\nOutput: True
    check(call(m, TASK, (-0.1,), {}), True, 'eq')


def test_t5(m):
    # release: Input: 10\nOutput: False
    check(call(m, TASK, (10,), {}), False, 'eq')
