# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/063 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the required return/print format is not stated (the release tests assume one); input_not_python: city names are unquoted
# Prompt: Given a list of cities and the distances between each pair of cities, what is the shortest possible route that visits each city and returns to the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/063', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nCities: [A, B, C]\nDistances: {(A, B): 1, (B, C): 2, (A, C): 2}\nOutput:\nA -> B -> C -> A ...
    check(call(m, TASK, (['A', 'B', 'C'], {('A', 'B'): 1, ('B', 'C'): 2, ('A', 'C'): 2}), {}), 'A -> B -> C -> A with a distance of 5', 'eq')


def test_t2(m):
    # release: Input:\nCities: [A, B, C, D]\nDistances: {(A, B): 10, (A, C): 15, (A, D): 20, (B, C): 35, (B, D): ...
    check(call(m, TASK, (['A', 'B', 'C', 'D'], {('A', 'B'): 10, ('A', 'C'): 15, ('A', 'D'): 20, ('B', 'C'): 35, ('B', 'D'): 25, ('C', 'D'): 30}), {}), 'A -> B -> D -> C -> A with a distance of 80', 'eq')


def test_t3(m):
    # release: Input:\nCities: [W, X, Y, Z]\nDistances: {(W, X): 2, (W, Y): 9, (W, Z): 10, (X, Y): 6, (X, Z): 4, ...
    check(call(m, TASK, (['W', 'X', 'Y', 'Z'], {('W', 'X'): 2, ('W', 'Y'): 9, ('W', 'Z'): 10, ('X', 'Y'): 6, ('X', 'Z'): 4, ('Y', 'Z'): 3}), {}), 'W -> X -> Z -> Y -> W with a distance of 15', 'eq')


def test_t4(m):
    # release: Input:\nCities: [P, Q, R]\nDistances: {(P, Q): 5, (P, R): 9, (Q, R): 6}\nOutput:\nP -> Q -> R -> P ...
    check(call(m, TASK, (['P', 'Q', 'R'], {('P', 'Q'): 5, ('P', 'R'): 9, ('Q', 'R'): 6}), {}), 'P -> Q -> R -> P with a distance of 20', 'eq')


def test_t5(m):
    # release: Input:\nCities: [M, N, O, P, Q]\nDistances: {(M, N): 2, (M, O): 9, (M, P): 10, (M, Q): 15, (N, O): ...
    check(call(m, TASK, (['M', 'N', 'O', 'P', 'Q'], {('M', 'N'): 2, ('M', 'O'): 9, ('M', 'P'): 10, ('M', 'Q'): 15, ('N', 'O'): 4, ('N', 'P'): 8, ('N', 'Q'): 14, ('O', 'P'): 6, ('O', 'Q'): 5, ('P', 'Q'): 3}), {}), 'M -> N -> O -> Q -> P -> M with a distance of 20', 'eq')
