# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/074 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Return True if the given string contains an appearance of "xyz" where the xyz is not directly preceeded by a period (.). So "xxyz" counts but ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/074', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"abcxyz"\nOutput:\nTrue
    check(call(m, TASK, ('abcxyz',), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n"abc.xxyz"\nOutput:\nFalse
    check(call(m, TASK, ('abc.xxyz',), {}), False, 'eq')


def test_t3(m):
    # release: Input:\n"xyz.abc"\nOutput:\nTrue
    check(call(m, TASK, ('xyz.abc',), {}), True, 'eq')


def test_t4(m):
    # release: Input:\n"x.xyzxyz"\nOutput:\nTrue
    check(call(m, TASK, ('x.xyzxyz',), {}), True, 'eq')


def test_t5(m):
    # release: Input:\n"xy.zxzy"\nOutput:\nTrue
    check(call(m, TASK, ('xy.zxzy',), {}), True, 'eq')
