# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/061 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: The Towers of Hanoi is a puzzle where we have three rods and n disks. The objective of the puzzle is to move the entire stack to another rod. You ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/061', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n1\nOutput:\n1
    check(call(m, TASK, (1,), {}), 1, 'eq')


def test_t2(m):
    # release: Input:\n2\nOutput:\n3
    check(call(m, TASK, (2,), {}), 3, 'eq')


def test_t3(m):
    # release: Input:\n3\nOutput:\n7
    check(call(m, TASK, (3,), {}), 7, 'eq')


def test_t4(m):
    # release: Input:\n4\nOutput:\n15
    check(call(m, TASK, (4,), {}), 15, 'eq')


def test_t5(m):
    # release: Input:\n5\nOutput:\n31\n\nThese test cases will help in validating the solution to the Towers of ...
    check(call(m, TASK, (5,), {}), 31, 'eq')
