# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/065 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal to given sum.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/065', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nSet: [3, 34, 4, 12, 5, 2]\nSum: 9\nOutput:\nTrue
    check(call(m, TASK, ([3, 34, 4, 12, 5, 2], 9), {}), True, 'eq')


def test_t2(m):
    # release: Input:\nSet: [1, 2, 3, 5]\nSum: 8\nOutput:\nTrue
    check(call(m, TASK, ([1, 2, 3, 5], 8), {}), True, 'eq')


def test_t3(m):
    # release: Input:\nSet: [1, 1, 1, 1]\nSum: 5\nOutput:\nFalse
    check(call(m, TASK, ([1, 1, 1, 1], 5), {}), False, 'eq')


def test_t4(m):
    # release: Input:\nSet: [7, 14, 3, 8, 10]\nSum: 21\nOutput:\nTrue
    check(call(m, TASK, ([7, 14, 3, 8, 10], 21), {}), True, 'eq')


def test_t5(m):
    # release: Input:\nSet: [2, 5, 8, 13, 21]\nSum: 50\nOutput:\nFalse
    check(call(m, TASK, ([2, 5, 8, 13, 21], 50), {}), False, 'eq')
