# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/051 | mode: original | kind: function | entry: mid | comparison: eq
# Well-posed: yes
# Prompt: Write a function named mid that takes a string as its parameter. Your function should extract and return the middle letter. If the length of the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/051', 'kind': 'function', 'entry': 'mid'}
ENV = None


def test_t1(m):
    # release: Input:\n"hello"\nOutput:\n"l"
    check(call(m, TASK, ('hello',), {}), 'l', 'eq')


def test_t2(m):
    # release: Input:\n"worlds"\nOutput:\n"rl"
    check(call(m, TASK, ('worlds',), {}), 'rl', 'eq')


def test_t3(m):
    # release: Input:\n"python"\nOutput:\n"th"
    check(call(m, TASK, ('python',), {}), 'th', 'eq')


def test_t4(m):
    # release: Input:\n"A"\nOutput:\n"A"
    check(call(m, TASK, ('A',), {}), 'A', 'eq')


def test_t5(m):
    # release: Input:\n"middle"\nOutput:\n"d"
    check(call(m, TASK, ('middle',), {}), 'd', 'eq')
