# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/028 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: We have two monkeys, a and b, and the parameters a_smile and b_smile indicate if each is smiling. We are in trouble if they are both smiling or if ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/028', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: a_smile = True, b_smile = True\nOutput: True (Both are smiling)
    check(call(m, TASK, (True, True), {}), True, 'eq')


def test_t2(m):
    # release: Input: a_smile = False, b_smile = False\nOutput: True (Neither is smiling)
    check(call(m, TASK, (False, False), {}), True, 'eq')


def test_t3(m):
    # release: Input: a_smile = True, b_smile = False\nOutput: False (Only one is smiling)
    check(call(m, TASK, (True, False), {}), False, 'eq')


def test_t4(m):
    # release: Input: a_smile = False, b_smile = True\nOutput: False (Only one is smiling)
    check(call(m, TASK, (False, True), {}), False, 'eq')


def test_t5(m):
    # release: Input: a_smile = False, b_smile = False\nOutput: True (Neither is smiling)
    check(call(m, TASK, (False, False), {}), True, 'eq')
