# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/005 | mode: original | kind: function | entry: only_ints | comparison: eq
# Well-posed: yes
# Prompt: Write a function named only_ints that takes two parameters. Your function should return True if both parameters are integers, and False otherwise.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/005', 'kind': 'function', 'entry': 'only_ints'}
ENV = None


def test_t1(m):
    # release: Input: (5, 10)\nOutput: True
    check(call(m, TASK, (5, 10), {}), True, 'eq')


def test_t2(m):
    # release: Input: (5, "10")\nOutput: False
    check(call(m, TASK, (5, '10'), {}), False, 'eq')


def test_t3(m):
    # release: Input: ("Hello", "World")\nOutput: False
    check(call(m, TASK, ('Hello', 'World'), {}), False, 'eq')


def test_t4(m):
    # release: Input: (7.5, 10)\nOutput: False
    check(call(m, TASK, (7.5, 10), {}), False, 'eq')


def test_t5(m):
    # release: Input: (-5, 0)\nOutput: True
    check(call(m, TASK, (-5, 0), {}), True, 'eq')
