# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/089 | mode: original | kind: program | entry: None | comparison: nums_in
# Well-posed: NO -- no_task_statement: the prompt only names numpy's inner and outer; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: The tools inner and outer return the inner and outer product of two arrays.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/089', 'kind': 'program', 'entry': None}
ENV = None


def test_t2(candidate_path):
    # release: Input:\na = [1, 2], b = [3, 4]\nOutput:\n11
    check_stdout(run_program(candidate_path, stdin='1 2\n3 4\n'), [11], 'nums_in')


def test_t3(candidate_path):
    # release: Input:\na = [0, 0], b = [5, 6]\nOutput:\n0
    check_stdout(run_program(candidate_path, stdin='0 0\n5 6\n'), [0], 'nums_in')


def test_t4(candidate_path):
    # release: Input:\na = [3, 4], b = [2, 2]\nOutput:\n14\n\n**
    check_stdout(run_program(candidate_path, stdin='3 4\n2 2\n'), [14], 'nums_in')


def test_t5(candidate_path):
    # release: **\nInput:\na = [1, 3], b = [5, 7]\nOutput:\n26
    check_stdout(run_program(candidate_path, stdin='1 3\n5 7\n'), [26], 'nums_in')


def test_t6(candidate_path):
    # release: Input:\na = [-1, 2], b = [4, -2]\nOutput:\n-8\n\nOuter Product Test Cases:
    check_stdout(run_program(candidate_path, stdin='-1 2\n4 -2\n'), [-8], 'nums_in')


def test_t7(candidate_path):
    # release: Input:\na = [1, 2], b = [3, 4]\nOutput:\n[[3, 4],\n[6, 8]]
    check_stdout(run_program(candidate_path, stdin='1 2\n3 4\n'), [3, 4, 6, 8], 'nums_in')


def test_t8(candidate_path):
    # release: Input:\na = [0, 0], b = [5, 6]\nOutput:\n[[0, 0],\n[0, 0]]
    check_stdout(run_program(candidate_path, stdin='0 0\n5 6\n'), [0, 0, 0, 0], 'nums_in')


def test_t9(candidate_path):
    # release: Input:\na = [3, 4], b = [1, 0]\nOutput:\n[[3, 0],\n[4, 0]]
    check_stdout(run_program(candidate_path, stdin='3 4\n1 0\n'), [3, 0, 4, 0], 'nums_in')


def test_t10(candidate_path):
    # release: Input:\na = [1, 3], b = [5, 7]\nOutput:\n[[5, 7],\n[15, 21]]
    check_stdout(run_program(candidate_path, stdin='1 3\n5 7\n'), [5, 7, 15, 21], 'nums_in')


def test_t11(candidate_path):
    # release: Input:\na = [-1, 2], b = [4, -2]\nOutput:\n[[-4, 2],\n[8, -4]]
    check_stdout(run_program(candidate_path, stdin='-1 2\n4 -2\n'), [-4, 2, 8, -4], 'nums_in')
