# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/104 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the required return/print format is not stated (the release tests assume one)
# Prompt: Create a function that takes an object and returns the keys and values as separate arrays.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/104', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n{"a": 1, "b": 2, "c": 3}\nOutput:\nKeys: ["a", "b", "c"], Values: [1, 2, 3]
    check(call(m, TASK, ({'a': 1, 'b': 2, 'c': 3},), {}), 'Keys: ["a", "b", "c"], Values: [1, 2, 3]', 'eq')


def test_t2(m):
    # release: Input:\n{"name": "Alice", "age": 25, "city": "New York"}\nOutput:\nKeys: ["name", "age", "city"], ...
    check(call(m, TASK, ({'name': 'Alice', 'age': 25, 'city': 'New York'},), {}), 'Keys: ["name", "age", "city"], Values: ["Alice", 25, "New York"]', 'eq')


def test_t3(m):
    # release: Input:\n{"x": true, "y": false, "z": true}\nOutput:\nKeys: ["x", "y", "z"], Values: [true, false, true]
    check(call(m, TASK, ({'x': True, 'y': False, 'z': True},), {}), 'Keys: ["x", "y", "z"], Values: [true, false, true]', 'eq')


def test_t4(m):
    # release: Input:\n{"a": [1, 2, 3], "b": [4, 5], "c": [6]}\nOutput:\nKeys: ["a", "b", "c"], Values: [[1, 2, 3], ...
    check(call(m, TASK, ({'a': [1, 2, 3], 'b': [4, 5], 'c': [6]},), {}), 'Keys: ["a", "b", "c"], Values: [[1, 2, 3], [4, 5], [6]]', 'eq')


def test_t5(m):
    # release: Input:\n{}\nOutput:\nKeys: [], Values: []
    check(call(m, TASK, ({},), {}), 'Keys: [], Values: []', 'eq')
