# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/031 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: We have a loud talking parrot. The "hour" parameter is the current hour time in the range 0..23. We are in trouble if the parrot is talking and ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/031', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: talking = True, hour = 6\nOutput: True (The parrot is talking before 7)
    check(call(m, TASK, (True, 6), {}), True, 'eq')


def test_t2(m):
    # release: Input: talking = True, hour = 7\nOutput: False (The parrot is talking but it's not before 7 or after 20)
    check(call(m, TASK, (True, 7), {}), False, 'eq')


def test_t3(m):
    # release: Input: talking = True, hour = 21\nOutput: True (The parrot is talking after 20)
    check(call(m, TASK, (True, 21), {}), True, 'eq')


def test_t4(m):
    # release: Input: talking = False, hour = 5\nOutput: False (The parrot isn't talking)
    check(call(m, TASK, (False, 5), {}), False, 'eq')


def test_t5(m):
    # release: Input: talking = True, hour = 12\nOutput: False (The parrot is talking but it's during allowed hours)
    check(call(m, TASK, (True, 12), {}), False, 'eq')
