# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/093 | mode: original | kind: function | entry: is_anagram | comparison: eq
# Well-posed: yes
# Prompt: Two strings are anagrams if you can make one from the other by rearranging the letters. Write a function named is_anagram that takes two strings ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/093', 'kind': 'function', 'entry': 'is_anagram'}
ENV = None


def test_t1(m):
    # release: Input:\n"listen", "silent"\nOutput:\nTrue
    check(call(m, TASK, ('listen', 'silent'), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n"hello", "world"\nOutput:\nFalse
    check(call(m, TASK, ('hello', 'world'), {}), False, 'eq')


def test_t3(m):
    # release: Input:\n"evil", "vile"\nOutput:\nTrue
    check(call(m, TASK, ('evil', 'vile'), {}), True, 'eq')


def test_t4(m):
    # release: Input:\n"looped", "poodle"\nOutput:\nTrue
    check(call(m, TASK, ('looped', 'poodle'), {}), True, 'eq')


def test_t5(m):
    # release: Input:\n"apple", "pale"\nOutput:\nFalse
    check(call(m, TASK, ('apple', 'pale'), {}), False, 'eq')
