# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/086 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print
# Prompt: Given the coefficients of the polynomial P, and the value for x, find the value of P when x = k.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/086', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nCoefficients: [2, -3, 4], x=2\nOutput:\n6\n\nExplanation:\nP(x) = 2x^2 - 3x + 4\nP(2) = ...
    check(call(m, TASK, ([2, -3, 4], 2), {}), 6, 'eq')


def test_t2(m):
    # release: Input:\nCoefficients: [1, 0, -1], x=3\nOutput:\n8\n\nExplanation:\nP(x) = x^2 - 1\nP(3) = (3^2) - 1 ...
    check(call(m, TASK, ([1, 0, -1], 3), {}), 8, 'eq')


def test_t3(m):
    # release: Input:\nCoefficients: [-1, 2, 1], x=0\nOutput:\n1\n\nExplanation:\nP(x) = -x^2 + 2x + 1\nP(0) = -0 + ...
    check(call(m, TASK, ([-1, 2, 1], 0), {}), 1, 'eq')


def test_t4(m):
    # release: Input:\nCoefficients: [3], x=5\nOutput:\n3\n\nExplanation:\nP(x) = 3 (A constant polynomial)\nP(5) = 3
    check(call(m, TASK, ([3], 5), {}), 3, 'eq')


def test_t5(m):
    # release: Input:\nCoefficients: [1, -2, 1], x=1\nOutput:\n0\n\nExplanation:\nP(x) = x^2 - 2x + 1\nP(1) = 1^2 - ...
    check(call(m, TASK, ([1, -2, 1], 1), {}), 0, 'eq')
