# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/022 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: There is a single operator in Python, capable of providing the remainder of a division operation. Two numbers are passed as parameters. The first ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/022', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 5, 2\nOutput: 1 (Because 5 divided by 2 leaves a remainder of 1)
    check(call(m, TASK, (5, 2), {}), 1, 'eq')


def test_t2(m):
    # release: Input: 7, 3\nOutput: 1 (Because 7 divided by 3 leaves a remainder of 1)
    check(call(m, TASK, (7, 3), {}), 1, 'eq')


def test_t3(m):
    # release: Input: 10, 4\nOutput: 2 (Because 10 divided by 4 leaves a remainder of 2)
    check(call(m, TASK, (10, 4), {}), 2, 'eq')


def test_t4(m):
    # release: Input: 8, 2\nOutput: 0 (Because 8 divided by 2 leaves no remainder)
    check(call(m, TASK, (8, 2), {}), 0, 'eq')


def test_t5(m):
    # release: Input: 15, 5\nOutput: 0 (Because 15 divided by 5 leaves no remainder)
    check(call(m, TASK, (15, 5), {}), 0, 'eq')
