# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/066 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- ambiguous: the prompt admits several readings that give different expected values ('make up this quantity exactly': 0/1 vs unbounded; the release values fit neither)
# Prompt: Given a knapsack weight W and a set of n items with certain value val[i] and weight wt[i], we need to calculate the maximum amount that could make ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/066', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nW: 50\nwt: [10, 20, 30]\nval: [60, 100, 120]\nOutput:\n220
    check(call(m, TASK, (50, [10, 20, 30], [60, 100, 120]), {}), 220, 'eq')


def test_t2(m):
    # release: Input:\nW: 8\nwt: [2, 3, 4, 5]\nval: [1, 2, 5, 6]\nOutput:\n7
    check(call(m, TASK, (8, [2, 3, 4, 5], [1, 2, 5, 6]), {}), 7, 'eq')


def test_t3(m):
    # release: Input:\nW: 4\nwt: [4, 5, 1]\nval: [1, 2, 3]\nOutput:\n3
    check(call(m, TASK, (4, [4, 5, 1], [1, 2, 3]), {}), 3, 'eq')


def test_t4(m):
    # release: Input:\nW: 15\nwt: [3, 5, 4, 6]\nval: [2, 4, 3, 5]\nOutput:\n9
    check(call(m, TASK, (15, [3, 5, 4, 6], [2, 4, 3, 5]), {}), 9, 'eq')


def test_t5(m):
    # release: Input:\nW: 6\nwt: [1, 3, 4, 5]\nval: [1, 4, 5, 7]\nOutput:\n9
    check(call(m, TASK, (6, [1, 3, 4, 5], [1, 4, 5, 7]), {}), 9, 'eq')
