# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/015 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: Read an integer N. For all non-negative integers i<N, print i^2.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/015', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\n3\nOutput:\n0\n1\n4
    check_stdout(run_program(candidate_path, stdin='3\n'), '0\n1\n4', 'tail')


def test_t2(candidate_path):
    # release: Input:\n5\nOutput:\n0\n1\n4\n9\n16
    check_stdout(run_program(candidate_path, stdin='5\n'), '0\n1\n4\n9\n16', 'tail')


def test_t3(candidate_path):
    # release: Input:\n0\nOutput:\n(No output as the range is empty for i<N)
    check_stdout(run_program(candidate_path, stdin='0\n'), '', 'empty')


def test_t4(candidate_path):
    # release: Input:\n1\nOutput:\n0
    check_stdout(run_program(candidate_path, stdin='1\n'), '0', 'tail')


def test_t5(candidate_path):
    # release: Input:\n4\nOutput:\n0\n1\n4\n9
    check_stdout(run_program(candidate_path, stdin='4\n'), '0\n1\n4\n9', 'tail')
