# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/053 | mode: original | kind: function | entry: random_number | comparison: eq
# Well-posed: yes
# Prompt: Define a function random_number that takes no parameters, and returns a random integer between 1 and 100 (inclusive).

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/053', 'kind': 'function', 'entry': 'random_number'}
ENV = None


def test_t1(m):
    # release: Call:\nrandom_number()\nExpected Output:\nAn integer between 1 and 100 (inclusive).
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r


def test_t2(m):
    # release: Call:\nrandom_number()\nExpected Output:\nAn integer between 1 and 100 (inclusive).
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r


def test_t3(m):
    # release: Call:\nrandom_number()\nExpected Output:\nAn integer between 1 and 100 (inclusive).
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r


def test_t4(m):
    # release: Call:\nrandom_number()\nExpected Output:\nAn integer between 1 and 100 (inclusive).
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r


def test_t5(m):
    # release: Call:\nrandom_number()\nExpected Output:\nAn integer between 1 and 100 (inclusive).
    r = call(m, TASK)
    assert isinstance(r, int) and not isinstance(r, bool) and 1 <= r <= 100, r
