# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/014 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- io_unspecified: the input format (how the values are read) is not stated (one line or two lines)
# Prompt: Read two integers and print two lines. The first line should contain integer division, a//b. The second line should contain float division, a/b.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/014', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\n4 3\nOutput:\n1\n1.3333333333333333
    check_stdout(run_program(candidate_path, stdin='4 3\n'), '1\n1.3333333333333333', 'tail')


def test_t2(candidate_path):
    # release: Input:\n10 2\nOutput:\n5\n5.0
    check_stdout(run_program(candidate_path, stdin='10 2\n'), '5\n5.0', 'tail')


def test_t3(candidate_path):
    # release: Input:\n5 4\nOutput:\n1\n1.25
    check_stdout(run_program(candidate_path, stdin='5 4\n'), '1\n1.25', 'tail')


def test_t4(candidate_path):
    # release: Input:\n22 7\nOutput:\n3\n3.142857142857143
    check_stdout(run_program(candidate_path, stdin='22 7\n'), '3\n3.142857142857143', 'tail')


def test_t5(candidate_path):
    # release: Input:\n9 4\nOutput:\n2\n2.25
    check_stdout(run_program(candidate_path, stdin='9 4\n'), '2\n2.25', 'tail')
