# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/034 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given 2 int values, return True if one is negative and one is positive. Except if the parameter "negative" is True, then return True only if both ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/034', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: a = 5, b = -5, negative = False\nOutput: True (One is positive and one is negative)
    check(call(m, TASK, (5, -5, False), {}), True, 'eq')


def test_t2(m):
    # release: Input: a = -5, b = -5, negative = True\nOutput: True (Both are negative and the "negative" parameter ...
    check(call(m, TASK, (-5, -5, True), {}), True, 'eq')


def test_t3(m):
    # release: Input: a = 5, b = 5, negative = False\nOutput: False (Both are positive)
    check(call(m, TASK, (5, 5, False), {}), False, 'eq')


def test_t4(m):
    # release: Input: a = -5, b = 5, negative = True\nOutput: False (One is negative, one is positive but the ...
    check(call(m, TASK, (-5, 5, True), {}), False, 'eq')


def test_t5(m):
    # release: Input: a = -5, b = -7, negative = False\nOutput: False (Both are negative but the "negative" ...
    check(call(m, TASK, (-5, -7, False), {}), False, 'eq')
