# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/111 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a string, return a version without the first and last char, so "Hello" yields "ell". The string length will be at least 2.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/111', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"Hello"\nOutput:\n"ell"
    check(call(m, TASK, ('Hello',), {}), 'ell', 'eq')


def test_t2(m):
    # release: Input:\n"python"\nOutput:\n"ytho"
    check(call(m, TASK, ('python',), {}), 'ytho', 'eq')


def test_t3(m):
    # release: Input:\n"programming"\nOutput:\n"rogrammin"
    check(call(m, TASK, ('programming',), {}), 'rogrammin', 'eq')


def test_t4(m):
    # release: Input:\n"openai"\nOutput:\n"pena"
    check(call(m, TASK, ('openai',), {}), 'pena', 'eq')


def test_t5(m):
    # release: Input:\n"abcdef"\nOutput:\n"bcde"
    check(call(m, TASK, ('abcdef',), {}), 'bcde', 'eq')
