# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/050 | mode: original | kind: function | entry: capital_indexes | comparison: eq
# Well-posed: yes
# Prompt: Write a function named capital_indexes. The function takes a single parameter, which is a string. Your function should return a list of all the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/050', 'kind': 'function', 'entry': 'capital_indexes'}
ENV = None


def test_t1(m):
    # release: Input:\n"HelloWorld"\nOutput:\n[0, 5]
    check(call(m, TASK, ('HelloWorld',), {}), [0, 5], 'eq')


def test_t2(m):
    # release: Input:\n"PythonIsFun"\nOutput:\n[0, 6, 8]
    check(call(m, TASK, ('PythonIsFun',), {}), [0, 6, 8], 'eq')


def test_t3(m):
    # release: Input:\n"JAVA"\nOutput:\n[0, 1, 2, 3]
    check(call(m, TASK, ('JAVA',), {}), [0, 1, 2, 3], 'eq')


def test_t4(m):
    # release: Input:\n"capitalIndexes"\nOutput:\n[]
    check(call(m, TASK, ('capitalIndexes',), {}), [], 'eq')


def test_t5(m):
    # release: Input:\n"mIxEdCaSe"\nOutput:\n[1, 4, 6]
    check(call(m, TASK, ('mIxEdCaSe',), {}), [1, 4, 6], 'eq')
