# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/059 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that finds how many steps it takes from a number to reach 1 by following Collatz Conjecture rules.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/059', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n6\nOutput:\n8\n(Explanation: 6 → 3 → 10 → 5 → 16 → 8 → 4 → 2 → 1)
    check(call(m, TASK, (6,), {}), 8, 'eq')


def test_t2(m):
    # release: Input:\n1\nOutput:\n0\n(Explanation: 1 is already at the target)
    check(call(m, TASK, (1,), {}), 0, 'eq')


def test_t3(m):
    # release: Input:\n12\nOutput:\n9\n(Explanation: 12 → 6 → 3 → 10 → 5 → 16 → 8 → 4 → 2 → 1)
    check(call(m, TASK, (12,), {}), 9, 'eq')


def test_t4(m):
    # release: Input:\n19\nOutput:\n20\n(Explanation: 19 → 58 → 29 → 88 → 44 → 22 → 11 → 34 → 17 → 52 → 26 → 13 → ...
    check(call(m, TASK, (19,), {}), 20, 'eq')


def test_t5(m):
    # release: Input:\n27\nOutput:\n111\n(Explanation: 27 goes through a long sequence before reaching 1.)
    check(call(m, TASK, (27,), {}), 111, 'eq')
