# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/006 | mode: original | kind: function | entry: add_dots | comparison: eq
# Well-posed: yes
# Prompt: Write a function named add_dots that takes a string and adds "." in between each letter. For example, calling add_dots("test") should return the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/006', 'kind': 'function', 'entry': 'add_dots'}
ENV = None


def test_t1(m):
    # release: Input: "test"\nOutput: "t.e.s.t"
    check(call(m, TASK, ('test',), {}), 't.e.s.t', 'eq')


def test_t2(m):
    # release: Input: "hello"\nOutput: "h.e.l.l.o"
    check(call(m, TASK, ('hello',), {}), 'h.e.l.l.o', 'eq')


def test_t3(m):
    # release: Input: "a"\nOutput: "a"
    check(call(m, TASK, ('a',), {}), 'a', 'eq')


def test_t4(m):
    # release: Input: "ab"\nOutput: "a.b"
    check(call(m, TASK, ('ab',), {}), 'a.b', 'eq')


def test_t5(m):
    # release: Input: "dot"\nOutput: "d.o.t"\n\nFor the remove_dots function:
    check(call(m, TASK, ('dot',), {}), 'd.o.t', 'eq')


def test_t6(m):
    # release: Input: "t.e.s.t"\nOutput: "test"
    check(call(m, TASK, ('t.e.s.t',), {}, entry='remove_dots'), 'test', 'eq')


def test_t7(m):
    # release: Input: "h.e.l.l.o"\nOutput: "hello"
    check(call(m, TASK, ('h.e.l.l.o',), {}, entry='remove_dots'), 'hello', 'eq')


def test_t8(m):
    # release: Input: "a"\nOutput: "a"
    check(call(m, TASK, ('a',), {}, entry='remove_dots'), 'a', 'eq')


def test_t9(m):
    # release: Input: "..a.b.."\nOutput: "ab"
    check(call(m, TASK, ('..a.b..',), {}, entry='remove_dots'), 'ab', 'eq')


def test_t10(m):
    # release: Input: "n.o.d.o.t.s"\nOutput: "nodots"
    check(call(m, TASK, ('n.o.d.o.t.s',), {}, entry='remove_dots'), 'nodots', 'eq')
