# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/068 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- ambiguous: the prompt admits several readings that give different expected values (the signature is not given, and 'n' disagrees with the number of items in test 1)
# Prompt: Given n items of different weights and bins each of capacity c, assign each item to a bin such that number of total used bins is minimized.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/068', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nn: 4\nItems: [4, 8, 1, 4, 2, 1]\nc: 10\nOutput:\n3
    check(call(m, TASK, ([4, 8, 1, 4, 2, 1], 10), {}), 3, 'eq')


def test_t2(m):
    # release: Input:\nn: 5\nItems: [9, 8, 7, 6, 5]\nc: 10\nOutput:\n5
    check(call(m, TASK, ([9, 8, 7, 6, 5], 10), {}), 5, 'eq')


def test_t3(m):
    # release: Input:\nn: 3\nItems: [2, 5, 4]\nc: 6\nOutput:\n2
    check(call(m, TASK, ([2, 5, 4], 6), {}), 2, 'eq')


def test_t4(m):
    # release: Input:\nn: 4\nItems: [7, 8, 3, 5]\nc: 15\nOutput:\n2
    check(call(m, TASK, ([7, 8, 3, 5], 15), {}), 2, 'eq')


def test_t5(m):
    # release: Input:\nn: 6\nItems: [1, 2, 3, 4, 5, 10]\nc: 10\nOutput:\n3
    check(call(m, TASK, ([1, 2, 3, 4, 5, 10], 10), {}), 3, 'eq')
