# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/112 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given 2 strings, a and b, return a string of the form short+long+short, with the shorter string on the outside and the longer string on the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/112', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"Hello", "Python"\nOutput:\n"HelloPythonHello"
    check(call(m, TASK, ('Hello', 'Python'), {}), 'HelloPythonHello', 'eq')


def test_t2(m):
    # release: Input:\n"openai", "AI"\nOutput:\n"AIopenaiAI"
    check(call(m, TASK, ('openai', 'AI'), {}), 'AIopenaiAI', 'eq')


def test_t3(m):
    # release: Input:\n"apple", "banana"\nOutput:\n"applebananapple"
    check(call(m, TASK, ('apple', 'banana'), {}), 'applebananapple', 'eq')


def test_t4(m):
    # release: Input:\n"longstring", "short"\nOutput:\n"shortlongstringshort"
    check(call(m, TASK, ('longstring', 'short'), {}), 'shortlongstringshort', 'eq')


def test_t5(m):
    # release: Input:\n"", "empty"\nOutput:\n"empty"
    check(call(m, TASK, ('', 'empty'), {}), 'empty', 'eq')
