# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/056 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: The goal of this challenge is to analyze a binary string consisting of only zeros and ones. Your code should find the biggest number of ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/056', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"1000111011100"\nOutput:\n3
    check(call(m, TASK, ('1000111011100',), {}), 3, 'eq')


def test_t2(m):
    # release: Input:\n"1100111111001101"\nOutput:\n4
    check(call(m, TASK, ('1100111111001101',), {}), 4, 'eq')


def test_t3(m):
    # release: Input:\n"1001"\nOutput:\n2
    check(call(m, TASK, ('1001',), {}), 2, 'eq')


def test_t4(m):
    # release: Input:\n"1111111"\nOutput:\n0
    check(call(m, TASK, ('1111111',), {}), 0, 'eq')


def test_t5(m):
    # release: Input:\n"01111000001111"\nOutput:\n5
    check(call(m, TASK, ('01111000001111',), {}), 5, 'eq')
