# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/054 | mode: original | kind: function | entry: only_ints | comparison: eq
# Well-posed: yes
# Prompt: Write a function named only_ints that takes two parameters. Your function should return True if both parameters are integers, and False otherwise.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/054', 'kind': 'function', 'entry': 'only_ints'}
ENV = None


def test_t1(m):
    # release: Input:\n5, 10\nOutput:\nTrue
    check(call(m, TASK, (5, 10), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n5, "hello"\nOutput:\nFalse
    check(call(m, TASK, (5, 'hello'), {}), False, 'eq')


def test_t3(m):
    # release: Input:\n"10", 20\nOutput:\nFalse
    check(call(m, TASK, ('10', 20), {}), False, 'eq')


def test_t4(m):
    # release: Input:\n-5, 0\nOutput:\nTrue
    check(call(m, TASK, (-5, 0), {}), True, 'eq')


def test_t5(m):
    # release: Input:\n3.5, 4\nOutput:\nFalse
    check(call(m, TASK, (3.5, 4), {}), False, 'eq')
