# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/101 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Write a function that takes an array of strings and returns the words that are exactly four letters.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/101', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n["apple", "banana", "pear", "grape"]\nOutput:\n["pear", "grape"]
    check(call(m, TASK, (['apple', 'banana', 'pear', 'grape'],), {}), ['pear', 'grape'], 'eq')


def test_t2(m):
    # release: Input:\n["cat", "dog", "fish", "bird"]\nOutput:\n["fish", "bird"]
    check(call(m, TASK, (['cat', 'dog', 'fish', 'bird'],), {}), ['fish', 'bird'], 'eq')


def test_t3(m):
    # release: Input:\n["red", "blue", "green", "yellow"]\nOutput:\n["blue"]
    check(call(m, TASK, (['red', 'blue', 'green', 'yellow'],), {}), ['blue'], 'eq')


def test_t4(m):
    # release: Input:\n["book", "pen", "desk", "chair"]\nOutput:\n["book", "desk"]
    check(call(m, TASK, (['book', 'pen', 'desk', 'chair'],), {}), ['book', 'desk'], 'eq')


def test_t5(m):
    # release: Input:\n["apple", "banana", "pear", "grape", "melon"]\nOutput:\n["pear", "grape"]
    check(call(m, TASK, (['apple', 'banana', 'pear', 'grape', 'melon'],), {}), ['pear', 'grape'], 'eq')
