# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/118 | mode: original | kind: vars | entry: None | comparison: nums_in2
# Well-posed: NO -- missing_context: the prompt refers to starter code or data that it does not include; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: Convert the list of weights from a list to a Numpy array. Then, convert all of the weights from kilograms to pounds. Use the scalar conversion of ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/118', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nweight_list = [70, 60, 85, 50, 95]\nweight_array = ...
    check_stdout(run_program(candidate_path, assignments={'weight_list': '[70, 60, 85, 50, 95]'}), [154, 132, 187, 110, 209], 'nums_in2')


def test_t2(candidate_path):
    # release: Input:\nweight_list = [55, 62, 80, 48, 90]\nweight_array = ...
    check_stdout(run_program(candidate_path, assignments={'weight_list': '[55, 62, 80, 48, 90]'}), [121, 136.4, 176, 105.6, 198], 'nums_in2')


def test_t3(candidate_path):
    # release: Input:\nweight_list = [58, 72, 50, 85, 46]\nweight_array = ...
    check_stdout(run_program(candidate_path, assignments={'weight_list': '[58, 72, 50, 85, 46]'}), [127.6, 158.4, 110, 187, 101.2], 'nums_in2')


def test_t4(candidate_path):
    # release: Input:\nweight_list = [65, 68, 55, 75, 52]\nweight_array = ...
    check_stdout(run_program(candidate_path, assignments={'weight_list': '[65, 68, 55, 75, 52]'}), [143, 149.6, 121, 165, 114.4], 'nums_in2')


def test_t5(candidate_path):
    # release: Input:\nweight_list = [80, 92, 78, 105, 75]\nweight_array = ...
    check_stdout(run_program(candidate_path, assignments={'weight_list': '[80, 92, 78, 105, 75]'}), [176, 202.4, 171.6, 231, 165], 'nums_in2')
