# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/021 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Write a function that takes an integer minutes and converts it to seconds.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/021', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 5\nOutput: 300 (5 minutes * 60 seconds/minute)
    check(call(m, TASK, (5,), {}), 300, 'eq')


def test_t2(m):
    # release: Input: 1\nOutput: 60 (1 minute * 60 seconds/minute)
    check(call(m, TASK, (1,), {}), 60, 'eq')


def test_t3(m):
    # release: Input: 45\nOutput: 2700 (45 minutes * 60 seconds/minute)
    check(call(m, TASK, (45,), {}), 2700, 'eq')


def test_t4(m):
    # release: Input: 0\nOutput: 0
    check(call(m, TASK, (0,), {}), 0, 'eq')


def test_t5(m):
    # release: Input: 120\nOutput: 7200 (120 minutes * 60 seconds/minute)
    check(call(m, TASK, (120,), {}), 7200, 'eq')
