# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/092 | mode: original | kind: function | entry: count | comparison: eq
# Well-posed: NO -- incomplete_task: the statement stops after describing the input; it never says what count should return (the tests assume the number of syllables)
# Prompt: Define a function named count that takes a single parameter. The parameter is a string. The string will contain a single word divided into ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/092', 'kind': 'function', 'entry': 'count'}
ENV = None


def test_t1(m):
    # release: Input:\n"ho-tel"\nOutput:\n2
    check(call(m, TASK, ('ho-tel',), {}), 2, 'eq')


def test_t2(m):
    # release: Input:\n"cat"\nOutput:\n1
    check(call(m, TASK, ('cat',), {}), 1, 'eq')


def test_t3(m):
    # release: Input:\n"in-ter-est-ing"\nOutput:\n4
    check(call(m, TASK, ('in-ter-est-ing',), {}), 4, 'eq')


def test_t4(m):
    # release: Input:\n"hel-lo"\nOutput:\n2
    check(call(m, TASK, ('hel-lo',), {}), 2, 'eq')


def test_t5(m):
    # release: Input:\n"a-b-c-d-e"\nOutput:\n5
    check(call(m, TASK, ('a-b-c-d-e',), {}), 5, 'eq')
