# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/085 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; release timestamps do not follow the formats the prompt names
# Prompt: When users post an update on social media,such as a URL, image, status update etc., other users in their network are able to view this new post on ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/085', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"Tue 01 Jan 2019 12:00:00 +0530", "Day, 01 Jan 2019 12:05:00 +0530"\nOutput:\n300
    check(call(m, TASK, ('Tue 01 Jan 2019 12:00:00 +0530', 'Day, 01 Jan 2019 12:05:00 +0530'), {}), 300, 'eq')


def test_t2(m):
    # release: Input:\n"Sat 15 Feb 2020 18:30:00 +0000", "Day, 15 Feb 2020 18:45:00 +0000"\nOutput:\n900
    check(call(m, TASK, ('Sat 15 Feb 2020 18:30:00 +0000', 'Day, 15 Feb 2020 18:45:00 +0000'), {}), 900, 'eq')


def test_t3(m):
    # release: Input:\n"Sun 20 Dec 2021 05:00:00 +0430", "Day, 20 Dec 2021 05:10:00 +0430"\nOutput:\n600
    check(call(m, TASK, ('Sun 20 Dec 2021 05:00:00 +0430', 'Day, 20 Dec 2021 05:10:00 +0430'), {}), 600, 'eq')


def test_t4(m):
    # release: Input:\n"Fri 25 Jun 2023 01:00:00 +0200", "Day, 25 Jun 2023 01:20:00 +0200"\nOutput:\n1200
    check(call(m, TASK, ('Fri 25 Jun 2023 01:00:00 +0200', 'Day, 25 Jun 2023 01:20:00 +0200'), {}), 1200, 'eq')


def test_t5(m):
    # release: Input:\n"Wed 10 Nov 2022 09:15:00 +0630", "Day, 10 Nov 2022 09:35:00 +0630"\nOutput:\n1200
    check(call(m, TASK, ('Wed 10 Nov 2022 09:15:00 +0630', 'Day, 10 Nov 2022 09:35:00 +0630'), {}), 1200, 'eq')
