# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/008 | mode: original | kind: function | entry: longest_word | comparison: eq
# Well-posed: yes
# Prompt: Write a function called longest_word that takes one argument, a list of words, and returns the length of the longest word in the list.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/008', 'kind': 'function', 'entry': 'longest_word'}
ENV = None


def test_t1(m):
    # release: Input: ["apple", "banana", "cherry"]\nOutput: 6
    check(call(m, TASK, (['apple', 'banana', 'cherry'],), {}), 6, 'eq')


def test_t2(m):
    # release: Input: ["a", "ab", "abc", "abcd"]\nOutput: 4
    check(call(m, TASK, (['a', 'ab', 'abc', 'abcd'],), {}), 4, 'eq')


def test_t3(m):
    # release: Input: ["short", "longer", "longest"]\nOutput: 7
    check(call(m, TASK, (['short', 'longer', 'longest'],), {}), 7, 'eq')


def test_t4(m):
    # release: Input: ["one", "two", "three", "four", "five"]\nOutput: 5
    check(call(m, TASK, (['one', 'two', 'three', 'four', 'five'],), {}), 5, 'eq')


def test_t5(m):
    # release: Input: ["hippopotamus", "cat", "horse"]\nOutput: 12
    check(call(m, TASK, (['hippopotamus', 'cat', 'horse'],), {}), 12, 'eq')
