# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/048 | mode: original | kind: program | entry: None | comparison: num
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: You are given a 2-D array with dimensions N x M. Your task is to perform the min function over axis 1 and then find the max of that.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/048', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nArray:\n[[1, 3, 5],\n[2, 4, 6]]\nOutput:\nResult after min along axis 1: [1, 2]\nMax of the ...
    check_stdout(run_program(candidate_path, stdin='2 3\n1 3 5\n2 4 6\n'), '2', 'num')


def test_t2(candidate_path):
    # release: Input:\nArray:\n[[10, 20, 30],\n[5, 15, 25]]\nOutput:\nResult after min along axis 1: [10, 5]\nMax ...
    check_stdout(run_program(candidate_path, stdin='2 3\n10 20 30\n5 15 25\n'), '10', 'num')


def test_t3(candidate_path):
    # release: Input:\nArray:\n[[1, 0, -1],\n[2, -2, 4],\n[5, 6, -3]]\nOutput:\nResult after min along axis 1: [-1, ...
    check_stdout(run_program(candidate_path, stdin='3 3\n1 0 -1\n2 -2 4\n5 6 -3\n'), '-1', 'num')


def test_t4(candidate_path):
    # release: Input:\nArray:\n[[4, 8],\n[1, 2]]\nOutput:\nResult after min along axis 1: [4, 1]\nMax of the result: 4
    check_stdout(run_program(candidate_path, stdin='2 2\n4 8\n1 2\n'), '4', 'num')


def test_t5(candidate_path):
    # release: Input:\nArray:\n[[0, 0, 0],\n[0, 0, 0],\n[0, 0, 0]]\nOutput:\nResult after min along axis 1: [0, 0, ...
    check_stdout(run_program(candidate_path, stdin='3 3\n0 0 0\n0 0 0\n0 0 0\n'), '0', 'num')
