# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/019 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes a number as an argument. Add up all the numbers from 1 to the number you passed to the function.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/019', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 4\nOutput: 10 (1 + 2 + 3 + 4)
    check(call(m, TASK, (4,), {}), 10, 'eq')


def test_t2(m):
    # release: Input: 5\nOutput: 15 (1 + 2 + 3 + 4 + 5)
    check(call(m, TASK, (5,), {}), 15, 'eq')


def test_t3(m):
    # release: Input: 1\nOutput: 1
    check(call(m, TASK, (1,), {}), 1, 'eq')


def test_t4(m):
    # release: Input: 10\nOutput: 55 (1 + 2 + 3 + ... + 10)
    check(call(m, TASK, (10,), {}), 55, 'eq')


def test_t5(m):
    # release: Input: 100\nOutput: 5050 (1 + 2 + 3 + ... + 100)
    check(call(m, TASK, (100,), {}), 5050, 'eq')
