# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/096 | mode: original | kind: function | entry: up_down | comparison: eq
# Well-posed: yes
# Prompt: Define a function named up_down that takes a single number as its parameter. Your function return a tuple containing two numbers; the first should ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/096', 'kind': 'function', 'entry': 'up_down'}
ENV = None


def test_t1(m):
    # release: Input:\n5\nOutput:\n(4, 6)
    check(call(m, TASK, (5,), {}), (4, 6), 'eq')


def test_t2(m):
    # release: Input:\n0\nOutput:\n(-1, 1)
    check(call(m, TASK, (0,), {}), (-1, 1), 'eq')


def test_t3(m):
    # release: Input:\n-3\nOutput:\n(-4, -2)
    check(call(m, TASK, (-3,), {}), (-4, -2), 'eq')


def test_t4(m):
    # release: Input:\n1\nOutput:\n(0, 2)
    check(call(m, TASK, (1,), {}), (0, 2), 'eq')


def test_t5(m):
    # release: Input:\n10\nOutput:\n(9, 11)
    check(call(m, TASK, (10,), {}), (9, 11), 'eq')
