# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/076 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Write a lambda function that takes two numbers and returns their sum.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/076', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n3, 4\nOutput:\n7
    check(call(m, TASK, (3, 4), {}), 7, 'eq')


def test_t2(m):
    # release: Input:\n-5, 5\nOutput:\n0
    check(call(m, TASK, (-5, 5), {}), 0, 'eq')


def test_t3(m):
    # release: Input:\n10, 15\nOutput:\n25
    check(call(m, TASK, (10, 15), {}), 25, 'eq')


def test_t4(m):
    # release: Input:\n0, 0\nOutput:\n0
    check(call(m, TASK, (0, 0), {}), 0, 'eq')


def test_t5(m):
    # release: Input:\n7, -3\nOutput:\n4
    check(call(m, TASK, (7, -3), {}), 4, 'eq')
