# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/038 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- missing_context: the prompt refers to starter code or data that it does not include (the code whose last line must be fixed)
# Prompt: Fix the last line so that it outputs the sum of 1 and 2

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/038', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\na = 1\nb = 2\nprint(a - b)\nOutput:\n3
    check_stdout(run_program(candidate_path, stdin=''), '3', 'tail')


def test_t2(candidate_path):
    # release: Input:\nx = 1\ny = 2\nprint(x * y)\nOutput:\n3
    check_stdout(run_program(candidate_path, stdin=''), '3', 'tail')


def test_t3(candidate_path):
    # release: Input:\nnum1 = 1\nnum2 = 2\nprint(num1 / num2)\nOutput:\n3
    check_stdout(run_program(candidate_path, stdin=''), '3', 'tail')


def test_t4(candidate_path):
    # release: Input:\nfirst = 1\nsecond = 2\nprint(first)\nOutput:\n3
    check_stdout(run_program(candidate_path, stdin=''), '3', 'tail')


def test_t5(candidate_path):
    # release: Input:\none = 1\ntwo = 2\nprint(one % two)\nOutput:\n3
    check_stdout(run_program(candidate_path, stdin=''), '3', 'tail')
