# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/080 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Write a function that takes a Python object, serializes it to JSON, and returns the JSON string.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/080', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n{"name": "John", "age": 30, "city": "New York"}\nOutput:\n'{"name": "John", "age": 30, ...
    check(call(m, TASK, ({'name': 'John', 'age': 30, 'city': 'New York'},), {}), '{"name": "John", "age": 30, "city": "New York"}', 'eq')


def test_t2(m):
    # release: Input:\n[1, 2, 3, 4, 5]\nOutput:\n'[1, 2, 3, 4, 5]'
    check(call(m, TASK, ([1, 2, 3, 4, 5],), {}), '[1, 2, 3, 4, 5]', 'eq')


def test_t3(m):
    # release: Input:\n(True, False, None)\nOutput:\n'[true, false, null]'
    check(call(m, TASK, ((True, False, None),), {}), '[true, false, null]', 'eq')


def test_t4(m):
    # release: Input:\n{"students": [{"name": "Alice"}, {"name": "Bob"}], "teacher": "Mr. ...
    check(call(m, TASK, ({'students': [{'name': 'Alice'}, {'name': 'Bob'}], 'teacher': 'Mr. Smith'},), {}), '{"students": [{"name": "Alice"}, {"name": "Bob"}], "teacher": "Mr. Smith"}', 'eq')


def test_t5(m):
    # release: Input:\n42\nOutput:\n'42'
    check(call(m, TASK, (42,), {}), '42', 'eq')
