# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/041 | mode: original | kind: function | entry: list_benefits | comparison: eq
# Well-posed: yes
# Prompt: Add a function named list_benefits() that returns the following list of strings: "More organized code", "More readable code", "Easier code reuse", ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/041', 'kind': 'function', 'entry': 'list_benefits'}
ENV = None


def test_t1(m):
    # release: Function Call:\nlist_benefits()\nOutput:\n["More organized code", "More readable code", "Easier code ...
    check(call(m, TASK, (), {}, entry='list_benefits'), ['More organized code', 'More readable code', 'Easier code reuse', 'Allowing programmers to share and connect code together'], 'eq')


def test_t2(m):
    # release: Function Call:\nbuild_sentence("More organized code")\nOutput:\n"More organized code is a benefit of ...
    check(call(m, TASK, ('More organized code',), {}, entry='build_sentence'), 'More organized code is a benefit of functions!', 'eq')


def test_t3(m):
    # release: Function Call:\nbuild_sentence("More readable code")\nOutput:\n"More readable code is a benefit of ...
    check(call(m, TASK, ('More readable code',), {}, entry='build_sentence'), 'More readable code is a benefit of functions!', 'eq')


def test_t4(m):
    # release: Function Call:\nbuild_sentence("Easier code reuse")\nOutput:\n"Easier code reuse is a benefit of ...
    check(call(m, TASK, ('Easier code reuse',), {}, entry='build_sentence'), 'Easier code reuse is a benefit of functions!', 'eq')


def test_t5(m):
    # release: Function Call:\nbuild_sentence("Allowing programmers to share and connect code ...
    check(call(m, TASK, ('Allowing programmers to share and connect code together',), {}, entry='build_sentence'), 'Allowing programmers to share and connect code together is a benefit of functions!', 'eq')
