# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/009 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Write a function that counts how many different countries are represented in a list of country IDs.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/009', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: ["US", "CA", "US", "MX", "CA"]\nOutput: 3
    check(call(m, TASK, (['US', 'CA', 'US', 'MX', 'CA'],), {}), 3, 'eq')


def test_t2(m):
    # release: Input: ["FR", "FR", "FR", "FR"]\nOutput: 1
    check(call(m, TASK, (['FR', 'FR', 'FR', 'FR'],), {}), 1, 'eq')


def test_t3(m):
    # release: Input: ["JP", "CN", "AU", "NZ", "IN", "SA", "ZA"]\nOutput: 7
    check(call(m, TASK, (['JP', 'CN', 'AU', 'NZ', 'IN', 'SA', 'ZA'],), {}), 7, 'eq')


def test_t4(m):
    # release: Input: []\nOutput: 0
    check(call(m, TASK, ([],), {}), 0, 'eq')


def test_t5(m):
    # release: Input: ["BR", "AR", "VE", "CO", "PE", "BR", "AR"]\nOutput: 5
    check(call(m, TASK, (['BR', 'AR', 'VE', 'CO', 'PE', 'BR', 'AR'],), {}), 5, 'eq')
