# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/103 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes a string and returns the middle character(s). If the word's length is odd, return the middle character. If the word's ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/103', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"hello"\nOutput:\n"l"
    check(call(m, TASK, ('hello',), {}), 'l', 'eq')


def test_t2(m):
    # release: Input:\n"world"\nOutput:\n"rl"
    check(call(m, TASK, ('world',), {}), 'rl', 'eq')


def test_t3(m):
    # release: Input:\n"apple"\nOutput:\n"p"
    check(call(m, TASK, ('apple',), {}), 'p', 'eq')


def test_t4(m):
    # release: Input:\n"banana"\nOutput:\n"an"
    check(call(m, TASK, ('banana',), {}), 'an', 'eq')


def test_t5(m):
    # release: Input:\n"programming"\nOutput:\n"a"
    check(call(m, TASK, ('programming',), {}), 'a', 'eq')
