# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/036 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a non-empty string and an int n, return a new string where the char at index n has been removed. The value of n will be a valid index of a ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/036', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: str = "hello", n = 1\nOutput: "hllo" (Because the character at index 1 is 'e')
    check(call(m, TASK, ('hello', 1), {}), 'hllo', 'eq')


def test_t2(m):
    # release: Input: str = "world", n = 3\nOutput: "worl" (Because the character at index 3 is 'l')
    check(call(m, TASK, ('world', 3), {}), 'worl', 'eq')


def test_t3(m):
    # release: Input: str = "python", n = 0\nOutput: "ython" (Because the character at index 0 is 'p')
    check(call(m, TASK, ('python', 0), {}), 'ython', 'eq')


def test_t4(m):
    # release: Input: str = "example", n = 6\nOutput: "exampl" (Because the character at index 6 is 'e')
    check(call(m, TASK, ('example', 6), {}), 'exampl', 'eq')


def test_t5(m):
    # release: Input: str = "remove", n = 2\nOutput: "remve" (Because the character at index 2 is 'o')
    check(call(m, TASK, ('remove', 2), {}), 'remve', 'eq')
