# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/073 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given two strings, return True if either of the strings appears at the very end of the other string, ignoring upper/lower case differences (in ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/073', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nString 1: "Hiabc"\nString 2: "abc"\nOutput:\nTrue
    check(call(m, TASK, ('Hiabc', 'abc'), {}), True, 'eq')


def test_t2(m):
    # release: Input:\nString 1: "abc"\nString 2: "ABCHI"\nOutput:\nFalse
    check(call(m, TASK, ('abc', 'ABCHI'), {}), False, 'eq')


def test_t3(m):
    # release: Input:\nString 1: "Hello"\nString 2: "lo"\nOutput:\nTrue
    check(call(m, TASK, ('Hello', 'lo'), {}), True, 'eq')


def test_t4(m):
    # release: Input:\nString 1: "Python"\nString 2: "THON"\nOutput:\nTrue
    check(call(m, TASK, ('Python', 'THON'), {}), True, 'eq')


def test_t5(m):
    # release: Input:\nString 1: "abcXYZ"\nString 2: "xyz"\nOutput:\nTrue
    check(call(m, TASK, ('abcXYZ', 'xyz'), {}), True, 'eq')
