# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/040 | mode: original | kind: vars | entry: None | comparison: tail
# Well-posed: NO -- missing_context: the prompt refers to starter code or data that it does not include (the numbers list)
# Prompt: Loop through and print out all even numbers from the numbers list in the same order they are received. Don't print any numbers that come after 237 ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/040', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\n[2, 4, 6, 8, 237, 10, 12]\nOutput:\n2\n4\n6\n8
    check_stdout(run_program(candidate_path, assignments={'numbers': '[2, 4, 6, 8, 237, 10, 12]'}), '2\n4\n6\n8', 'tail')


def test_t2(candidate_path):
    # release: Input:\n[1, 3, 5, 7, 9, 2, 4, 6, 237, 238, 240]\nOutput:\n2\n4\n6
    check_stdout(run_program(candidate_path, assignments={'numbers': '[1, 3, 5, 7, 9, 2, 4, 6, 237, 238, 240]'}), '2\n4\n6', 'tail')


def test_t3(candidate_path):
    # release: Input:\n[237, 2, 4, 6, 8, 10]\nOutput:\n\n(Note: No numbers should be printed since 237 is the first ...
    check_stdout(run_program(candidate_path, assignments={'numbers': '[237, 2, 4, 6, 8, 10]'}), '', 'empty')


def test_t4(candidate_path):
    # release: Input:\n[2, 4, 6, 237, 8, 10, 12, 14, 16]\nOutput:\n2\n4\n6
    check_stdout(run_program(candidate_path, assignments={'numbers': '[2, 4, 6, 237, 8, 10, 12, 14, 16]'}), '2\n4\n6', 'tail')


def test_t5(candidate_path):
    # release: Input:\n[1, 3, 237, 5, 238, 240, 242, 244]\nOutput:\n\n(Note: No even numbers before 237 in this ...
    check_stdout(run_program(candidate_path, assignments={'numbers': '[1, 3, 237, 5, 238, 240, 242, 244]'}), '', 'empty')
