# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/058 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Write a function that takes a list of lists and flattens it into a one-dimensional list.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/058', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n[[1, 2, 3], [4, 5, 6], [7, 8, 9]]\nOutput:\n[1, 2, 3, 4, 5, 6, 7, 8, 9]
    check(call(m, TASK, ([[1, 2, 3], [4, 5, 6], [7, 8, 9]],), {}), [1, 2, 3, 4, 5, 6, 7, 8, 9], 'eq')


def test_t2(m):
    # release: Input:\n[["a", "b", "c"], ["d", "e"], ["f"]]\nOutput:\n["a", "b", "c", "d", "e", "f"]
    check(call(m, TASK, ([['a', 'b', 'c'], ['d', 'e'], ['f']],), {}), ['a', 'b', 'c', 'd', 'e', 'f'], 'eq')


def test_t3(m):
    # release: Input:\n[[1, 2], [3, 4], [5, 6], [7, 8]]\nOutput:\n[1, 2, 3, 4, 5, 6, 7, 8]
    check(call(m, TASK, ([[1, 2], [3, 4], [5, 6], [7, 8]],), {}), [1, 2, 3, 4, 5, 6, 7, 8], 'eq')


def test_t4(m):
    # release: Input:\n[[], [], [1, 2, 3], [], [4, 5]]\nOutput:\n[1, 2, 3, 4, 5]
    check(call(m, TASK, ([[], [], [1, 2, 3], [], [4, 5]],), {}), [1, 2, 3, 4, 5], 'eq')


def test_t5(m):
    # release: Input:\n[[1], [2], [3], [4], [5]]\nOutput:\n[1, 2, 3, 4, 5]
    check(call(m, TASK, ([[1], [2], [3], [4], [5]],), {}), [1, 2, 3, 4, 5], 'eq')
