# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/083 | mode: original | kind: program | entry: None | comparison: nums_in
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; io_unspecified: the required return/print format is not stated (the release tests assume one)
# Prompt: Kevin and Stuart want to play the 'The Minion Game'. Game Rules: Both players are given the same string, S. Both players have to make substrings ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/083', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\n"BANANA"\nOutput:\nStuart: 12, Kevin: 9\n\nExplanation: Some of Kevin's words are 'A', 'AN', ...
    check_stdout(run_program(candidate_path, stdin='BANANA\n'), [12, 9], 'nums_in')


def test_t2(candidate_path):
    # release: Input:\n"APPLE"\nOutput:\nStuart: 11, Kevin: 8\n\nExplanation: Some of Kevin's words are 'A', 'AP', ...
    check_stdout(run_program(candidate_path, stdin='APPLE\n'), [11, 8], 'nums_in')


def test_t3(candidate_path):
    # release: Input:\n"ORANGE"\nOutput:\nStuart: 12, Kevin: 15\n\nExplanation: Some of Kevin's words are 'O', ...
    check_stdout(run_program(candidate_path, stdin='ORANGE\n'), [12, 15], 'nums_in')


def test_t4(candidate_path):
    # release: Input:\n"STUART"\nOutput:\nStuart: 21, Kevin: 1\n\nExplanation: Kevin's only word is 'A'. For ...
    check_stdout(run_program(candidate_path, stdin='STUART\n'), [21, 1], 'nums_in')


def test_t5(candidate_path):
    # release: Input:\n"KEVIN"\nOutput:\nStuart: 8, Kevin: 5\n\nExplanation: Some of Kevin's words are 'E', 'EVI'. ...
    check_stdout(run_program(candidate_path, stdin='KEVIN\n'), [8, 5], 'nums_in')
