# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/046 | mode: original | kind: program | entry: None | comparison: nums_in
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Note: HackerRank stdin assumed: A on line 1, B on line 2; checks inner then outer product numbers.
# Prompt: You are given two arrays: A and B. Your task is to compute their inner and outer product.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/046', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nArray A: [1]\nArray B: [2]\nOutput:\nInner Product: 2\nOuter Product:\n[[2]]
    check_stdout(run_program(candidate_path, stdin='1\n2\n'), [2, 2], 'nums_in')


def test_t2(candidate_path):
    # release: Input:\nArray A: [1, 2]\nArray B: [3, 4]\nOutput:\nInner Product: 11\nOuter Product:\n[[3, 4],\n[6, 8]]
    check_stdout(run_program(candidate_path, stdin='1 2\n3 4\n'), [11, 3, 4, 6, 8], 'nums_in')


def test_t3(candidate_path):
    # release: Input:\nArray A: [1, 2, 3]\nArray B: [4, 5, 6]\nOutput:\nInner Product: 32\nOuter Product:\n[[ 4, 5, ...
    check_stdout(run_program(candidate_path, stdin='1 2 3\n4 5 6\n'), [32, 4, 5, 6, 8, 10, 12, 12, 15, 18], 'nums_in')


def test_t4(candidate_path):
    # release: Input:\nArray A: [2, 4, 6]\nArray B: [1, 3, 5]\nOutput:\nInner Product: 44\nOuter Product:\n[[ 2, 6, ...
    check_stdout(run_program(candidate_path, stdin='2 4 6\n1 3 5\n'), [44, 2, 6, 10, 4, 12, 20, 6, 18, 30], 'nums_in')


def test_t5(candidate_path):
    # release: Input:\nArray A: [1, 0, -1]\nArray B: [0, 1, 2]\nOutput:\nInner Product: -1\nOuter Product:\n[[ 0, ...
    check_stdout(run_program(candidate_path, stdin='1 0 -1\n0 1 2\n'), [-1, 0, 1, 2, 0, 0, 0, 0, -1, -2], 'nums_in')
