# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/113 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given 2 strings, return their concatenation, except omit the first char of each. The strings will be at least length 1.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/113', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"Hello", "Python"\nOutput:\n"elloython"
    check(call(m, TASK, ('Hello', 'Python'), {}), 'elloython', 'eq')


def test_t2(m):
    # release: Input:\n"openai", "AI"\nOutput:\n"penaiI"
    check(call(m, TASK, ('openai', 'AI'), {}), 'penaiI', 'eq')


def test_t3(m):
    # release: Input:\n"apple", "banana"\nOutput:\n"ppleanana"
    check(call(m, TASK, ('apple', 'banana'), {}), 'ppleanana', 'eq')


def test_t4(m):
    # release: Input:\n"longstring", "short"\nOutput:\n"ongstringhort"
    check(call(m, TASK, ('longstring', 'short'), {}), 'ongstringhort', 'eq')


def test_t5(m):
    # release: Input:\n"abcdef", "ghijkl"\nOutput:\n"bcdefhijkl"
    check(call(m, TASK, ('abcdef', 'ghijkl'), {}), 'bcdefhijkl', 'eq')
