# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/010 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: A palindrome is a word that is the same forwards as backwards. If the word is the same backwards as forwards, you should return True. Otherwise, ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/010', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: "radar"\nOutput: True
    check(call(m, TASK, ('radar',), {}), True, 'eq')


def test_t2(m):
    # release: Input: "apple"\nOutput: False
    check(call(m, TASK, ('apple',), {}), False, 'eq')


def test_t3(m):
    # release: Input: "level"\nOutput: True
    check(call(m, TASK, ('level',), {}), True, 'eq')


def test_t4(m):
    # release: Input: "deified"\nOutput: True
    check(call(m, TASK, ('deified',), {}), True, 'eq')


def test_t5(m):
    # release: Input: "palindrome"\nOutput: False
    check(call(m, TASK, ('palindrome',), {}), False, 'eq')
