# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/106 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes a word and returns true if the word has two consecutive identical letters.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/106', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"hello"\nOutput:\nTrue
    check(call(m, TASK, ('hello',), {}), True, 'eq')


def test_t2(m):
    # release: Input:\n"apple"\nOutput:\nTrue
    check(call(m, TASK, ('apple',), {}), True, 'eq')


def test_t3(m):
    # release: Input:\n"banana"\nOutput:\nTrue
    check(call(m, TASK, ('banana',), {}), True, 'eq')


def test_t4(m):
    # release: Input:\n"programming"\nOutput:\nFalse
    check(call(m, TASK, ('programming',), {}), False, 'eq')


def test_t5(m):
    # release: Input:\n"openai"\nOutput:\nFalse
    check(call(m, TASK, ('openai',), {}), False, 'eq')
