# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/055 | mode: original | kind: function | entry: add_dots | comparison: eq
# Well-posed: yes
# Note: Each release test holds one add_dots and one remove_dots case.
# Prompt: Write a function named add_dots that takes a string and adds "." in between each letter. Write another function named remove_dots that removes all ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/055', 'kind': 'function', 'entry': 'add_dots'}
ENV = None


def test_t1a(m):
    check(call(m, TASK, ('test',), {}), 't.e.s.t', 'eq')


def test_t1b(m):
    check(call(m, TASK, ('t.e.s.t',), {}, entry='remove_dots'), 'test', 'eq')


def test_t2a(m):
    check(call(m, TASK, ('hello',), {}), 'h.e.l.l.o', 'eq')


def test_t2b(m):
    check(call(m, TASK, ('h.e.l.l.o',), {}, entry='remove_dots'), 'hello', 'eq')


def test_t3a(m):
    check(call(m, TASK, ('a',), {}), 'a', 'eq')


def test_t3b(m):
    check(call(m, TASK, ('a.b.c',), {}, entry='remove_dots'), 'abc', 'eq')


def test_t4a(m):
    check(call(m, TASK, ('dot',), {}), 'd.o.t', 'eq')


def test_t4b(m):
    check(call(m, TASK, ('d.o.t',), {}, entry='remove_dots'), 'dot', 'eq')


def test_t5a(m):
    check(call(m, TASK, ('abc',), {}), 'a.b.c', 'eq')


def test_t5b(m):
    check(call(m, TASK, ('a..b..c',), {}, entry='remove_dots'), 'abc', 'eq')
