# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/011 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: yes
# Prompt: Print Hello, World! to stdout.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/011', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input: (no input since the function doesn't take any parameters)\nOutput: "Hello, World!"
    check_stdout(run_program(candidate_path, stdin=''), 'Hello, World!', 'tail')


def test_t2(candidate_path):
    # release: Input: (no input since the function doesn't take any parameters)\nOutput: "Hello, World!"
    check_stdout(run_program(candidate_path, stdin=''), 'Hello, World!', 'tail')


def test_t3(candidate_path):
    # release: Input: (no input since the function doesn't take any parameters)\nOutput: "Hello, World!"
    check_stdout(run_program(candidate_path, stdin=''), 'Hello, World!', 'tail')


def test_t4(candidate_path):
    # release: Input: (no input since the function doesn't take any parameters)\nOutput: "Hello, World!"
    check_stdout(run_program(candidate_path, stdin=''), 'Hello, World!', 'tail')


def test_t5(candidate_path):
    # release: Input: (no input since the function doesn't take any parameters)\nOutput: "Hello, World!"
    check_stdout(run_program(candidate_path, stdin=''), 'Hello, World!', 'tail')
