# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/116 | mode: original | kind: vars | entry: None | comparison: nums_in2
# Well-posed: NO -- missing_context: the prompt refers to starter code or data that it does not include; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: Perform element-wise calculations on height and weight. For example, you could take all 6 of the height and weight observations above, and ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/116', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nheight_array = np.array([170, 165, 180, 155, 190])\nweight_array = np.array([70, 60, 85, 50, ...
    check_stdout(run_program(candidate_path, assignments={'height_array': 'np.array([170, 165, 180, 155, 190])', 'weight_array': 'np.array([70, 60, 85, 50, 95])'}), [24.22, 22.04, 26.23, 20.81, 26.32], 'nums_in2')


def test_t2(candidate_path):
    # release: Input:\nheight_array = np.array([150, 160, 175, 140, 185])\nweight_array = np.array([55, 62, 80, 48, ...
    check_stdout(run_program(candidate_path, assignments={'height_array': 'np.array([150, 160, 175, 140, 185])', 'weight_array': 'np.array([55, 62, 80, 48, 90])'}), [24.44, 24.22, 26.12, 24.49, 26.34], 'nums_in2')


def test_t3(candidate_path):
    # release: Input:\nheight_array = np.array([160, 170, 155, 180, 145])\nweight_array = np.array([58, 72, 50, 85, ...
    check_stdout(run_program(candidate_path, assignments={'height_array': 'np.array([160, 170, 155, 180, 145])', 'weight_array': 'np.array([58, 72, 50, 85, 46])'}), [22.66, 24.92, 20.85, 26.23, 21.85], 'nums_in2')


def test_t4(candidate_path):
    # release: Input:\nheight_array = np.array([165, 175, 160, 185, 150])\nweight_array = np.array([65, 68, 55, 75, ...
    check_stdout(run_program(candidate_path, assignments={'height_array': 'np.array([165, 175, 160, 185, 150])', 'weight_array': 'np.array([65, 68, 55, 75, 52])'}), [23.88, 22.2, 21.48, 21.93, 23.11], 'nums_in2')


def test_t5(candidate_path):
    # release: Input:\nheight_array = np.array([180, 190, 175, 200, 170])\nweight_array = np.array([80, 92, 78, ...
    check_stdout(run_program(candidate_path, assignments={'height_array': 'np.array([180, 190, 175, 200, 170])', 'weight_array': 'np.array([80, 92, 78, 105, 75])'}), [24.69, 25.46, 25.47, 26.25, 25.95], 'nums_in2')
