# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/013 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- io_unspecified: the input format (how the values are read) is not stated (the release puts both integers on one line; HackerRank uses two lines)
# Prompt: Read two integers from STDIN and print three lines where: The first line contains the sum of the two numbers. The second line contains the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/013', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\n3 2\nOutput:\n5\n1\n6
    check_stdout(run_program(candidate_path, stdin='3 2\n'), '5\n1\n6', 'tail')


def test_t2(candidate_path):
    # release: Input:\n-5 4\nOutput:\n-1\n-9\n-20
    check_stdout(run_program(candidate_path, stdin='-5 4\n'), '-1\n-9\n-20', 'tail')


def test_t3(candidate_path):
    # release: Input:\n7 0\nOutput:\n7\n7\n0
    check_stdout(run_program(candidate_path, stdin='7 0\n'), '7\n7\n0', 'tail')


def test_t4(candidate_path):
    # release: Input:\n-3 -7\nOutput:\n-10\n4\n21
    check_stdout(run_program(candidate_path, stdin='-3 -7\n'), '-10\n4\n21', 'tail')


def test_t5(candidate_path):
    # release: Input:\n10 5\nOutput:\n15\n5\n50
    check_stdout(run_program(candidate_path, stdin='10 5\n'), '15\n5\n50', 'tail')
