# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/039 | mode: original | kind: program | entry: None | comparison: tail
# Well-posed: NO -- missing_context: the prompt refers to starter code or data that it does not include (the string and the values to insert)
# Prompt: Use the 'format' method to print out the specified string with the correct values inserted

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/039', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\n"Hello, {}!"\nOutput:\n"Hello, World!"
    check_stdout(run_program(candidate_path, stdin=''), 'Hello, World!', 'tail')


def test_t2(candidate_path):
    # release: Input:\n"I have {} apples and {} oranges."\nOutput:\n"I have 5 apples and 6 oranges."
    check_stdout(run_program(candidate_path, stdin=''), 'I have 5 apples and 6 oranges.', 'tail')


def test_t3(candidate_path):
    # release: Input:\n"My favorite color is {}."\nOutput:\n"My favorite color is blue."
    check_stdout(run_program(candidate_path, stdin=''), 'My favorite color is blue.', 'tail')


def test_t4(candidate_path):
    # release: Input:\n"{} + {} = {}"\nOutput:\n"3 + 4 = 7"
    check_stdout(run_program(candidate_path, stdin=''), '3 + 4 = 7', 'tail')


def test_t5(candidate_path):
    # release: Input:\n"{} is the capital of {}."\nOutput:\n"Paris is the capital of France."
    check_stdout(run_program(candidate_path, stdin=''), 'Paris is the capital of France.', 'tail')
