# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/105 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- ambiguous: the prompt admits several readings that give different expected values (what to return when the item is missing: the tests assume -1)
# Prompt: Create a function that finds the index of a given item.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/105', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n[1, 2, 3, 4, 5], 3\nOutput:\n2
    check(call(m, TASK, ([1, 2, 3, 4, 5], 3), {}), 2, 'eq')


def test_t2(m):
    # release: Input:\n["apple", "banana", "cherry"], "banana"\nOutput:\n1
    check(call(m, TASK, (['apple', 'banana', 'cherry'], 'banana'), {}), 1, 'eq')


def test_t3(m):
    # release: Input:\n[10, 20, 30, 40, 50], 60\nOutput:\n-1
    check(call(m, TASK, ([10, 20, 30, 40, 50], 60), {}), -1, 'eq')


def test_t4(m):
    # release: Input:\n["a", "b", "c", "d"], "e"\nOutput:\n-1
    check(call(m, TASK, (['a', 'b', 'c', 'd'], 'e'), {}), -1, 'eq')


def test_t5(m):
    # release: Input:\n[True, False, True], False\nOutput:\n1
    check(call(m, TASK, ([True, False, True], False), {}), 1, 'eq')
