# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/099 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Write a function that takes a positive integer and return its factorial.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/099', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n5\nOutput:\n120
    check(call(m, TASK, (5,), {}), 120, 'eq')


def test_t2(m):
    # release: Input:\n1\nOutput:\n1
    check(call(m, TASK, (1,), {}), 1, 'eq')


def test_t3(m):
    # release: Input:\n10\nOutput:\n3628800
    check(call(m, TASK, (10,), {}), 3628800, 'eq')


def test_t4(m):
    # release: Input:\n7\nOutput:\n5040
    check(call(m, TASK, (7,), {}), 5040, 'eq')


def test_t5(m):
    # release: Input:\n0\nOutput:\n1
    check(call(m, TASK, (0,), {}), 1, 'eq')
