# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/018 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Take a list of integers (positive or negative or both) and return the sum of the absolute value of each element.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/018', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: [2, -3, 4, -1]\nOutput: 10
    check(call(m, TASK, ([2, -3, 4, -1],), {}), 10, 'eq')


def test_t2(m):
    # release: Input: [-5, -4, -3, -2, -1]\nOutput: 15
    check(call(m, TASK, ([-5, -4, -3, -2, -1],), {}), 15, 'eq')


def test_t3(m):
    # release: Input: [5, 4, 3, 2, 1]\nOutput: 15
    check(call(m, TASK, ([5, 4, 3, 2, 1],), {}), 15, 'eq')


def test_t4(m):
    # release: Input: [0, -1, 1, 0]\nOutput: 2
    check(call(m, TASK, ([0, -1, 1, 0],), {}), 2, 'eq')


def test_t5(m):
    # release: Input: [-10, 20, -30, 40]\nOutput: 100
    check(call(m, TASK, ([-10, 20, -30, 40],), {}), 100, 'eq')
