# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/081 | mode: original | kind: custom | entry: None | comparison: eq
# Well-posed: NO -- release_tests_incoherent: tests 1-2 call a 2- or 3-argument function with 4 arguments
# Prompt: Write a function that takes a function and some arguments, and returns a new function that can be called with additional arguments.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/081', 'kind': 'custom', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nFunction: lambda x, y: x + y, Arguments: 2, 3\nNew Function Call with Arguments: 4, ...
    f = call(m, TASK, (lambda x, y: x + y, 2, 3))
    check(f(4, 5), 14)


def test_t2(m):
    # release: Input:\nFunction: lambda x, y, z: x * y - z, Arguments: 2, 3\nNew Function Call with Arguments: 4, ...
    f = call(m, TASK, (lambda x, y, z: x * y - z, 2, 3))
    check(f(4, 5), 6)


def test_t3(m):
    # release: Input:\nFunction: str.join, Arguments: ","\nNew Function Call with Arguments: ["a", "b", ...
    f = call(m, TASK, (str.join, ','))
    check(f(['a', 'b', 'c']), 'a,b,c')


def test_t4(m):
    # release: Input:\nFunction: math.pow, Arguments: 2\nNew Function Call with Arguments: 3\nOutput:\n8
    import math
    f = call(m, TASK, (math.pow, 2))
    check(f(3), 8)


def test_t5(m):
    # release: Input:\nFunction: lambda x, y: x / y, Arguments: 5\nNew Function Call with Arguments: 2\nOutput:\n2.5
    f = call(m, TASK, (lambda x, y: x / y, 5))
    check(f(2), 2.5)
