# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/075 | mode: original | kind: function | entry: None | comparison: seq
# Well-posed: NO -- ambiguous: the prompt admits several readings that give different expected values ('up to n': the first n numbers or the numbers <= n; tests assume the first n)
# Prompt: Write a generator function that generates the Fibonacci sequence up to n.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/075', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n5\nOutput:\n0, 1, 1, 2, 3
    check(call(m, TASK, (5,), {}), (0, 1, 1, 2, 3), 'seq')


def test_t2(m):
    # release: Input:\n1\nOutput:\n0
    check(call(m, TASK, (1,), {}), [0], 'seq')


def test_t3(m):
    # release: Input:\n10\nOutput:\n0, 1, 1, 2, 3, 5, 8, 13, 21, 34
    check(call(m, TASK, (10,), {}), (0, 1, 1, 2, 3, 5, 8, 13, 21, 34), 'seq')


def test_t4(m):
    # release: Input:\n3\nOutput:\n0, 1, 1
    check(call(m, TASK, (3,), {}), (0, 1, 1), 'seq')


def test_t5(m):
    # release: Input:\n7\nOutput:\n0, 1, 1, 2, 3, 5, 8
    check(call(m, TASK, (7,), {}), (0, 1, 1, 2, 3, 5, 8), 'seq')
