# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/047 | mode: original | kind: program | entry: None | comparison: nums_in
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Note: HackerRank stdin assumed ('N M' then rows); release numbers without the 'axis' labels.
# Prompt: You are given a 2-D array of size N x M. Your task is to find: The mean along axis 1. The var along axis 0. The std along axis None.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/047', 'kind': 'program', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nArray:\n[[1, 2, 3],\n[4, 5, 6]]\nOutput:\nMean along axis 1: [2. 5.]\nVariance along axis 0: ...
    check_stdout(run_program(candidate_path, stdin='2 3\n1 2 3\n4 5 6\n'), [2, 5, 2.25, 2.25, 2.25, 1.8708286933869707], 'nums_in')


def test_t2(candidate_path):
    # release: Input:\nArray:\n[[10, 20, 30, 40],\n[50, 60, 70, 80]]\nOutput:\nMean along axis 1: [ 25. ...
    check_stdout(run_program(candidate_path, stdin='2 4\n10 20 30 40\n50 60 70 80\n'), [25, 65, 625, 625, 625, 625, 27.386127875258307], 'nums_in')


def test_t3(candidate_path):
    # release: Input:\nArray:\n[[1, 2],\n[3, 4],\n[5, 6]]\nOutput:\nMean along axis 1: [1.5 3.5 5.5]\nVariance ...
    check_stdout(run_program(candidate_path, stdin='3 2\n1 2\n3 4\n5 6\n'), [1.5, 3.5, 5.5, 4.66666667, 4.66666667, 1.8708286933869707], 'nums_in')


def test_t4(candidate_path):
    # release: Input:\nArray:\n[[1, 1, 1],\n[2, 2, 2],\n[3, 3, 3]]\nOutput:\nMean along axis 1: [1. 2. ...
    check_stdout(run_program(candidate_path, stdin='3 3\n1 1 1\n2 2 2\n3 3 3\n'), [1, 2, 3, 0.66666667, 0.66666667, 0.66666667, 0.816496580927726], 'nums_in')


def test_t5(candidate_path):
    # release: Input:\nArray:\n[[4, 8],\n[12, 16]]\nOutput:\nMean along axis 1: [ 6. 14.]\nVariance along axis 0: ...
    check_stdout(run_program(candidate_path, stdin='2 2\n4 8\n12 16\n'), [6, 14, 16, 16, 5.656854249492381], 'nums_in')
