# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/052 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the required return/print format is not stated (the release tests assume one); release test 1 passes an empty dict although the prompt says 'called without any arguments'
# Prompt: The aim of this challenge is to write a function that determines who is online, offline and away. If your function is called without any ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/052', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n{}\nOutput:\n"no one online"
    check(call(m, TASK, ({},), {}), 'no one online', 'eq')


def test_t2(m):
    # release: Input:\n{\n"Alice": "online",\n"Bob": "offline",\n"Charlie": "away"\n}\nOutput:\nOnline: ["Alice"], ...
    check(call(m, TASK, ({'Alice': 'online', 'Bob': 'offline', 'Charlie': 'away'},), {}), 'Online: ["Alice"], Offline: ["Bob"], Away: ["Charlie"]', 'eq')


def test_t3(m):
    # release: Input:\n{\n"David": "online",\n"Eve": "online",\n"Frank": "away",\n"Grace": ...
    check(call(m, TASK, ({'David': 'online', 'Eve': 'online', 'Frank': 'away', 'Grace': 'away'},), {}), 'Online: ["David", "Eve"], Offline: [], Away: ["Frank", "Grace"]', 'eq')


def test_t4(m):
    # release: Input:\n{\n"Hannah": "offline",\n"Isaac": "offline"\n}\nOutput:\nOnline: [], Offline: ["Hannah", ...
    check(call(m, TASK, ({'Hannah': 'offline', 'Isaac': 'offline'},), {}), 'Online: [], Offline: ["Hannah", "Isaac"], Away: []', 'eq')


def test_t5(m):
    # release: Input:\n{\n"Jack": "away"\n}\nOutput:\nOnline: [], Offline: [], Away: ["Jack"]
    check(call(m, TASK, ({'Jack': 'away'},), {}), 'Online: [], Offline: [], Away: ["Jack"]', 'eq')
