# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/043 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: NO -- io_unspecified: the prompt does not say whether to write a function or a program, or what to return/print; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: You are given the coefficients of a polynomial P. Your task is to find the value of P at point x.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/043', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nCoefficients: [1, 0, -1]\nx = 2\nOutput:\n3
    check(call(m, TASK, ([1, 0, -1], 2), {}), 3, 'eq')


def test_t2(m):
    # release: Input:\nCoefficients: [1, -3, 2]\nx = 1\nOutput:\n0
    check(call(m, TASK, ([1, -3, 2], 1), {}), 0, 'eq')


def test_t3(m):
    # release: Input:\nCoefficients: [1, 0, 0, 0, -1]\nx = -1\nOutput:\n0
    check(call(m, TASK, ([1, 0, 0, 0, -1], -1), {}), 0, 'eq')


def test_t4(m):
    # release: Input:\nCoefficients: [3, 0, 2]\nx = 0\nOutput:\n2
    check(call(m, TASK, ([3, 0, 2], 0), {}), 2, 'eq')


def test_t5(m):
    # release: Input:\nCoefficients: [2, -4, 1, -5]\nx = 3\nOutput:\n16
    check(call(m, TASK, ([2, -4, 1, -5], 3), {}), 16, 'eq')
