# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/023 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes length and width and finds the perimeter of a rectangle.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/023', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 5, 3\nOutput: 16 (Because 2*(5+3) = 16)
    check(call(m, TASK, (5, 3), {}), 16, 'eq')


def test_t2(m):
    # release: Input: 7, 2\nOutput: 18 (Because 2*(7+2) = 18)
    check(call(m, TASK, (7, 2), {}), 18, 'eq')


def test_t3(m):
    # release: Input: 10, 4\nOutput: 28 (Because 2*(10+4) = 28)
    check(call(m, TASK, (10, 4), {}), 28, 'eq')


def test_t4(m):
    # release: Input: 6, 6\nOutput: 24 (Because 2*(6+6) = 24)
    check(call(m, TASK, (6, 6), {}), 24, 'eq')


def test_t5(m):
    # release: Input: 8, 5\nOutput: 26 (Because 2*(8+5) = 26)
    check(call(m, TASK, (8, 5), {}), 26, 'eq')
