# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/024 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given two numbers, return True if the sum of both numbers is less than 100. Otherwise return False.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/024', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 45, 50\nOutput: False (Because 45 + 50 = 95, which is less than 100)
    check(call(m, TASK, (45, 50), {}), False, 'eq')


def test_t2(m):
    # release: Input: 30, 20\nOutput: True (Because 30 + 20 = 50, which is less than 100)
    check(call(m, TASK, (30, 20), {}), True, 'eq')


def test_t3(m):
    # release: Input: 90, 10\nOutput: False (Because 90 + 10 = 100, which is not less than 100)
    check(call(m, TASK, (90, 10), {}), False, 'eq')


def test_t4(m):
    # release: Input: -10, 5\nOutput: True (Because -10 + 5 = -5, which is less than 100)
    check(call(m, TASK, (-10, 5), {}), True, 'eq')


def test_t5(m):
    # release: Input: 50, 49\nOutput: True (Because 50 + 49 = 99, which is less than 100)
    check(call(m, TASK, (50, 49), {}), True, 'eq')
