# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/088 | mode: original | kind: program | entry: None | comparison: nums_in
# Well-posed: NO -- no_task_statement: the prompt only names numpy's dot and cross; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: The tools dot and cross returns the dot and cross product of two arrays respectively.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/088', 'kind': 'program', 'entry': None}
ENV = None


def test_t2(candidate_path):
    # release: Input:\na = [1, 2], b = [3, 4]\nOutput:\n11\n\nExplanation:\nDot product = 13 + 24 = 3 + 8 = 11
    check_stdout(run_program(candidate_path, stdin='1 2\n3 4\n'), [11], 'nums_in')


def test_t3(candidate_path):
    # release: Input:\na = [0, 0], b = [5, 6]\nOutput:\n0\n\nExplanation:\nDot product of vectors with a zero ...
    check_stdout(run_program(candidate_path, stdin='0 0\n5 6\n'), [0], 'nums_in')


def test_t4(candidate_path):
    # release: Input:\na = [2, 3], b = [-2, -3]\nOutput:\n-13\n\nExplanation:\nDot product = 2*(-2) + 3*(-3) = -4 ...
    check_stdout(run_program(candidate_path, stdin='2 3\n-2 -3\n'), [-13], 'nums_in')


def test_t5(candidate_path):
    # release: Input:\na = [1, 2, 3], b = [4, 5, 6]\nOutput:\n[-3, 6, -3]\n\nExplanation:\nCross product formula ...
    check_stdout(run_program(candidate_path, stdin='1 2 3\n4 5 6\n'), [-3, 6, -3], 'nums_in')


def test_t6(candidate_path):
    # release: Input:\na = [0, 0, 0], b = [5, 6, 7]\nOutput:\n[0, 0, 0]\n\nExplanation:\nCross product with a zero ...
    check_stdout(run_program(candidate_path, stdin='0 0 0\n5 6 7\n'), [0, 0, 0], 'nums_in')


def test_t7(candidate_path):
    # release: Input:\na = [1, 0, 0], b = [0, 1, 0]\nOutput:\n[0, 0, 1]\n\nExplanation:\nCross product of two ...
    check_stdout(run_program(candidate_path, stdin='1 0 0\n0 1 0\n'), [0, 0, 1], 'nums_in')
