# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/020 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes a number as an argument, increments the number by +1 and returns the result.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/020', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 5\nOutput: 6
    check(call(m, TASK, (5,), {}), 6, 'eq')


def test_t2(m):
    # release: Input: -1\nOutput: 0
    check(call(m, TASK, (-1,), {}), 0, 'eq')


def test_t3(m):
    # release: Input: 0\nOutput: 1
    check(call(m, TASK, (0,), {}), 1, 'eq')


def test_t4(m):
    # release: Input: 99\nOutput: 100
    check(call(m, TASK, (99,), {}), 100, 'eq')


def test_t5(m):
    # release: Input: -101\nOutput: -100
    check(call(m, TASK, (-101,), {}), -100, 'eq')
