# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/002 | mode: original | kind: function | entry: mid | comparison: eq
# Well-posed: yes
# Prompt: Write a function named mid that takes a string as its parameter. Your function should extract and return the middle letter. If the length of the ...

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/002', 'kind': 'function', 'entry': 'mid'}
ENV = None


def test_t1(m):
    # release: Input: "hello"\nOutput: "l"
    check(call(m, TASK, ('hello',), {}), 'l', 'eq')


def test_t2(m):
    # release: Input: "abcdef"\nOutput: "cd"
    check(call(m, TASK, ('abcdef',), {}), 'cd', 'eq')


def test_t3(m):
    # release: Input: "a"\nOutput: "a"
    check(call(m, TASK, ('a',), {}), 'a', 'eq')


def test_t4(m):
    # release: Input: "ChatGPT"\nOutput: "tG"
    check(call(m, TASK, ('ChatGPT',), {}), 'tG', 'eq')


def test_t5(m):
    # release: Input: "programming"\nOutput: "g"
    check(call(m, TASK, ('programming',), {}), 'g', 'eq')
