# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/030 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given an int n, return the absolute difference between n and 21, except return double the absolute difference if n is over 21.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/030', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 18\nOutput: 3 (Because 21 - 18 = 3)
    check(call(m, TASK, (18,), {}), 3, 'eq')


def test_t2(m):
    # release: Input: 25\nOutput: 8 (Because (25 - 21) * 2 = 8)
    check(call(m, TASK, (25,), {}), 8, 'eq')


def test_t3(m):
    # release: Input: 21\nOutput: 0 (No difference)
    check(call(m, TASK, (21,), {}), 0, 'eq')


def test_t4(m):
    # release: Input: 30\nOutput: 18 (Because (30 - 21) * 2 = 18)
    check(call(m, TASK, (30,), {}), 18, 'eq')


def test_t5(m):
    # release: Input: 15\nOutput: 6 (Because 21 - 15 = 6)
    check(call(m, TASK, (15,), {}), 6, 'eq')
