# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/108 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a string, return a new string made of 3 copies of the last 2 chars of the original string. The string length will be at least 2.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/108', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"hello"\nOutput:\n"lololo"
    check(call(m, TASK, ('hello',), {}), 'lololo', 'eq')


def test_t2(m):
    # release: Input:\n"python"\nOutput:\n"ononon"
    check(call(m, TASK, ('python',), {}), 'ononon', 'eq')


def test_t3(m):
    # release: Input:\n"programming"\nOutput:\n"ngngng"
    check(call(m, TASK, ('programming',), {}), 'ngngng', 'eq')


def test_t4(m):
    # release: Input:\n"openai"\nOutput:\n"aiiaii"
    check(call(m, TASK, ('openai',), {}), 'aiiaii', 'eq')


def test_t5(m):
    # release: Input:\n"abcd"\nOutput:\n"cdcdcd"
    check(call(m, TASK, ('abcd',), {}), 'cdcdcd', 'eq')
