# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/098 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes a string and returns a string with its letters in alphabetical order.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/098', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"hello"\nOutput:\n"ehllo"
    check(call(m, TASK, ('hello',), {}), 'ehllo', 'eq')


def test_t2(m):
    # release: Input:\n"zebra"\nOutput:\n"aberz"
    check(call(m, TASK, ('zebra',), {}), 'aberz', 'eq')


def test_t3(m):
    # release: Input:\n"banana"\nOutput:\n"aaabnn"
    check(call(m, TASK, ('banana',), {}), 'aaabnn', 'eq')


def test_t4(m):
    # release: Input:\n"programming"\nOutput:\n"aggimmnoprr"
    check(call(m, TASK, ('programming',), {}), 'aggimmnoprr', 'eq')


def test_t5(m):
    # release: Input:\n"openai"\nOutput:\n"aeinop
    check(call(m, TASK, ('openai',), {}), '"aeinop', 'eq')
