# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/114 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a string, return a "rotated left 2" version where the first 2 chars are moved to the end. The string length will be at least 2.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/114', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"Hello"\nOutput:\n"lloHe"
    check(call(m, TASK, ('Hello',), {}), 'lloHe', 'eq')


def test_t2(m):
    # release: Input:\n"python"\nOutput:\n"thonpy"
    check(call(m, TASK, ('python',), {}), 'thonpy', 'eq')


def test_t3(m):
    # release: Input:\n"programming"\nOutput:\n"ogrammingpr"
    check(call(m, TASK, ('programming',), {}), 'ogrammingpr', 'eq')


def test_t4(m):
    # release: Input:\n"openai"\nOutput:\n"enaiop"
    check(call(m, TASK, ('openai',), {}), 'enaiop', 'eq')


def test_t5(m):
    # release: Input:\n"abcdef"\nOutput:\n"cdefab"
    check(call(m, TASK, ('abcdef',), {}), 'cdefab', 'eq')
