# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/062 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Note: Argument order follows the prompt: weights, values, capacity.
# Prompt: Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/062', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\nWeights: [10, 20, 30]\nValues: [60, 100, 120]\nCapacity (W): 50\nOutput:\n220
    check(call(m, TASK, ([10, 20, 30], [60, 100, 120], 50), {}), 220, 'eq')


def test_t2(m):
    # release: Input:\nWeights: [5, 10, 15]\nValues: [10, 20, 30]\nCapacity (W): 20\nOutput:\n40
    check(call(m, TASK, ([5, 10, 15], [10, 20, 30], 20), {}), 40, 'eq')


def test_t3(m):
    # release: Input:\nWeights: [2, 3, 4, 5]\nValues: [1, 2, 5, 6]\nCapacity (W): 8\nOutput:\n8
    check(call(m, TASK, ([2, 3, 4, 5], [1, 2, 5, 6], 8), {}), 8, 'eq')


def test_t4(m):
    # release: Input:\nWeights: [1, 2, 5, 6, 7]\nValues: [1, 6, 18, 22, 28]\nCapacity (W): 11\nOutput:\n40
    check(call(m, TASK, ([1, 2, 5, 6, 7], [1, 6, 18, 22, 28], 11), {}), 40, 'eq')


def test_t5(m):
    # release: Input:\nWeights: [4, 5, 1]\nValues: [1, 2, 3]\nCapacity (W): 4\nOutput:\n3
    check(call(m, TASK, ([4, 5, 1], [1, 2, 3], 4), {}), 3, 'eq')
