# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/016 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Write a function to check if the given year is leap or not.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/016', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: 2000\nOutput: True
    check(call(m, TASK, (2000,), {}), True, 'eq')


def test_t2(m):
    # release: Input: 1900\nOutput: False
    check(call(m, TASK, (1900,), {}), False, 'eq')


def test_t3(m):
    # release: Input: 2004\nOutput: True
    check(call(m, TASK, (2004,), {}), True, 'eq')


def test_t4(m):
    # release: Input: 2100\nOutput: False
    check(call(m, TASK, (2100,), {}), False, 'eq')


def test_t5(m):
    # release: Input: 2023\nOutput: False
    check(call(m, TASK, (2023,), {}), False, 'eq')
