# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/110 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Given a string of even length, return the first half. So the string "WooHoo" yields "Woo".

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/110', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input:\n"WooHoo"\nOutput:\n"Woo"
    check(call(m, TASK, ('WooHoo',), {}), 'Woo', 'eq')


def test_t2(m):
    # release: Input:\n"python"\nOutput:\n"pyt"
    check(call(m, TASK, ('python',), {}), 'pyt', 'eq')


def test_t3(m):
    # release: Input:\n"programming"\nOutput:\n"progra"
    check(call(m, TASK, ('programming',), {}), 'progra', 'eq')


def test_t4(m):
    # release: Input:\n"openai"\nOutput:\n"ope"
    check(call(m, TASK, ('openai',), {}), 'ope', 'eq')


def test_t5(m):
    # release: Input:\n"abcdef"\nOutput:\n"abc"
    check(call(m, TASK, ('abcdef',), {}), 'abc', 'eq')
