# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/115 | mode: original | kind: vars | entry: None | comparison: nums_in
# Well-posed: NO -- missing_context: the prompt refers to starter code or data that it does not include; numpy_exercise: DataCamp/HackerRank NumPy exercise whose I/O conventions are not in the prompt
# Prompt: Create two Python lists for height and weight. Then, import the numpy package and create numpy arrays out of the newly created lists

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/115', 'kind': 'vars', 'entry': None}
ENV = None


def test_t1(candidate_path):
    # release: Input:\nheight_list = [170, 165, 180, 155, 190]\nweight_list = [70, 60, 85, 50, 95]\nOutput:\nHeight ...
    check_stdout(run_program(candidate_path, assignments={'height_list': '[170, 165, 180, 155, 190]', 'weight_list': '[70, 60, 85, 50, 95]'}), [170, 165, 180, 155, 190, 70, 60, 85, 50, 95], 'nums_in')


def test_t2(candidate_path):
    # release: Input:\nheight_list = [150, 160, 175, 140, 185]\nweight_list = [55, 62, 80, 48, 90]\nOutput:\nHeight ...
    check_stdout(run_program(candidate_path, assignments={'height_list': '[150, 160, 175, 140, 185]', 'weight_list': '[55, 62, 80, 48, 90]'}), [150, 160, 175, 140, 185, 55, 62, 80, 48, 90], 'nums_in')


def test_t3(candidate_path):
    # release: Input:\nheight_list = [160, 170, 155, 180, 145]\nweight_list = [58, 72, 50, 85, 46]\nOutput:\nHeight ...
    check_stdout(run_program(candidate_path, assignments={'height_list': '[160, 170, 155, 180, 145]', 'weight_list': '[58, 72, 50, 85, 46]'}), [160, 170, 155, 180, 145, 58, 72, 50, 85, 46], 'nums_in')


def test_t4(candidate_path):
    # release: Input:\nheight_list = [165, 175, 160, 185, 150]\nweight_list = [65, 68, 55, 75, 52]\nOutput:\nHeight ...
    check_stdout(run_program(candidate_path, assignments={'height_list': '[165, 175, 160, 185, 150]', 'weight_list': '[65, 68, 55, 75, 52]'}), [165, 175, 160, 185, 150, 65, 68, 55, 75, 52], 'nums_in')


def test_t5(candidate_path):
    # release: Input:\nheight_list = [180, 190, 175, 200, 170]\nweight_list = [80, 92, 78, 105, ...
    check_stdout(run_program(candidate_path, assignments={'height_list': '[180, 190, 175, 200, 170]', 'weight_list': '[80, 92, 78, 105, 75]'}), [180, 190, 175, 200, 170, 80, 92, 78, 105, 75], 'nums_in')
