# AUTO-GENERATED by scripts/build_tasks.py -- do not edit.
# Edit data/curation/codingsites.py (and data/reference/codingsites/) instead, then rebuild.
# Task codingsites/026 | mode: original | kind: function | entry: None | comparison: eq
# Well-posed: yes
# Prompt: Create a function that takes a list and returns the first element.

import pytest  # noqa: F401
from cse_runtime import call, call_or_arg, check, check_stdout, run_program  # noqa: F401

TASK = {'uid': 'codingsites/026', 'kind': 'function', 'entry': None}
ENV = None


def test_t1(m):
    # release: Input: [5, 4, 3, 2, 1]\nOutput: 5
    check(call(m, TASK, ([5, 4, 3, 2, 1],), {}), 5, 'eq')


def test_t2(m):
    # release: Input: ["apple", "banana", "cherry"]\nOutput: "apple"
    check(call(m, TASK, (['apple', 'banana', 'cherry'],), {}), 'apple', 'eq')


def test_t3(m):
    # release: Input: [1]\nOutput: 1
    check(call(m, TASK, ([1],), {}), 1, 'eq')


def test_t4(m):
    # release: Input: [True, False, True]\nOutput: True
    check(call(m, TASK, ([True, False, True],), {}), True, 'eq')


def test_t5(m):
    # release: Input: [3.5, 4.6, 5.7]\nOutput: 3.5
    check(call(m, TASK, ([3.5, 4.6, 5.7],), {}), 3.5, 'eq')
